### ISSUE TITLE
Thread 'pty reader' panicked at 'not yet implemented'

### ISSUE THREAD

**Issue by poppingtonic** [jwilm/alacritty#102]
I just built alacritty (on Arch Linux, with a fresh `nightly rust`), and an attempt at running it with `~/alacritty/target/release/alacritty`   failed with  

```bash
device_pixel_ratio: 1
width: 1024, height: 768
Initializing glyph cache
num fonts = 144
num fonts = 144
num fonts = 144
Finished initializing glyph cache in 0.010874721
set_inner_size: 644px × 436px
width: 644, height: 436
Cell Size: (8 x 18)
PTY Dimensions: Line(24) x Column(80)
[unhandled osc_start]
[unhandled osc_put] byte='0'
[unhandled osc_put] byte=';'
[unhandled osc_put] byte='b'
[unhandled osc_put] byte='r'
[unhandled osc_put] byte='i'
[unhandled osc_put] byte='a'
[unhandled osc_put] byte='n'
[unhandled osc_put] byte='@'
[unhandled osc_put] byte='r'
[unhandled osc_put] byte='o'
[unhandled osc_put] byte='s'
[unhandled osc_put] byte='e'
[unhandled osc_put] byte='t'
[unhandled osc_put] byte='t'
[unhandled osc_put] byte='a'
[unhandled osc_put] byte='b'
[unhandled osc_put] byte='r'
[unhandled osc_put] byte='a'
[unhandled osc_put] byte='i'
[unhandled osc_put] byte='n'
[unhandled osc_put] byte=':'
[unhandled osc_put] byte='~'
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='a'
[unhandled osc_put] byte='l'
[unhandled osc_put] byte='a'
[unhandled osc_put] byte='c'
[unhandled osc_put] byte='r'
[unhandled osc_put] byte='i'
[unhandled osc_put] byte='t'
[unhandled osc_put] byte='t'
[unhandled osc_put] byte='y'
[unhandled osc_end] byte=0
thread 'pty reader' panicked at 'not yet implemented', /home/brian/.cargo/git/checkouts/glutin-2b5ecc80feb2e4c5/af7fe34/src/api/wayland/window.rs:26
note: Run with `RUST_BACKTRACE=1` for a backtrace.

thread 'pty reader' panicked at 'not yet implemented', /home/brian/.cargo/git/checkouts/glutin-2b5ecc80feb2e4c5/af7fe34/src/api/wayland/window.rs:26
stack backtrace:
xkbcommon: ERROR: Key "<LFSH>" added to modifier map for multiple modifiers; Using Lock, ignoring Shift
thread 'main' panicked at 'not yet implemented', /home/brian/.cargo/git/checkouts/glutin-2b5ecc80feb2e4c5/af7fe34/src/api/wayland/window.rs:26
   1:     0x55c2b68582ca - std::sys::imp::backtrace::tracing::imp::write::h2b860f17b6b0f511
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55c2b685d63f - std::panicking::default_hook::{{closure}}::hedea7d569eb1e6b8
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:349
   3:     0x55c2b685d23e - std::panicking::default_hook::he87e0c76c89c52a4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:365
   4:     0x55c2b685dae7 - std::panicking::rust_panic_with_hook::h304127bde2d3d5e2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:553
   5:     0x55c2b67615d4 - std::panicking::begin_panic::h1dc990fced681ffe
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:515
   6:     0x55c2b677acd6 - alacritty::display::Notifier::notify::h3a4ca8681676ba22
                        at /home/brian/alacritty/<panic macros>:3
                        at /home/brian/.cargo/git/checkouts/glutin-2b5ecc80feb2e4c5/af7fe34/src/platform/linux/api_dispatch.rs:68
                        at /home/brian/.cargo/git/checkouts/glutin-2b5ecc80feb2e4c5/af7fe34/src/window.rs:556
                        at /home/brian/alacritty/src/window.rs:293
                        at /home/brian/alacritty/src/display.rs:113
   7:     0x55c2b674c049 - <alacritty::event_loop::EventLoop<Io>>::spawn::{{closure}}::h363f1a7097a6e863
                        at /home/brian/alacritty/src/event_loop.rs:219
                        at /home/brian/alacritty/src/event_loop.rs:308
   8:     0x55c2b673762b - std::panicking::try::do_call::h389b90bf0f081aa8
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:295
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:458
   9:     0x55c2b6864a2a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  10:     0x55c2b6749bba - <F as alloc::boxed::FnBox<A>>::call_box::h4877e9fed6201b2d
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:434
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/mod.rs:287
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:605
  11:     0x55c2b685c934 - std::sys::imp::thread::Thread::new::thread_start::h460a0adc61139b06
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  12:     0x7fcc51b5a453 - start_thread
  13:     0x7fcc516867de - __GI___clone
  14:                0x0 - <unknown>
stack backtrace:
   1:     0x55c2b68582ca - std::sys::imp::backtrace::tracing::imp::write::h2b860f17b6b0f511
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55c2b685d63f - std::panicking::default_hook::{{closure}}::hedea7d569eb1e6b8
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:349
   3:     0x55c2b685d23e - std::panicking::default_hook::he87e0c76c89c52a4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:365
   4:     0x55c2b685dae7 - std::panicking::rust_panic_with_hook::h304127bde2d3d5e2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:553
   5:     0x55c2b67615d4 - std::panicking::begin_panic::h1dc990fced681ffe
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:515
   6:     0x55c2b677dfd4 - alacritty::display::Display::new::{{closure}}::habc75f3d435ea1d8
                        at /home/brian/alacritty/<panic macros>:3
                        at /home/brian/.cargo/git/checkouts/glutin-2b5ecc80feb2e4c5/af7fe34/src/platform/linux/api_dispatch.rs:68
                        at /home/brian/.cargo/git/checkouts/glutin-2b5ecc80feb2e4c5/af7fe34/src/window.rs:556
                        at /home/brian/alacritty/src/window.rs:293
                        at /home/brian/alacritty/src/display.rs:220
   7:     0x55c2b67fecb7 - glutin::api::wayland::window::Window::next_event::h27aa352e5ab71059
child finished with error '1'

```

**Comment by d3rrial** [comment]
Are you trying to run it within wayland?
Wayland is not yet supported

**Comment by Palmitoxico** [comment]
I've the same problem, and yes I'm running it on Wayland. But by my understanding, an application that  only supports X11 should run under XWayland without problems, so why the crash?

**Comment by d3rrial** [comment]
It's apparently using a deprecated version of glutin (for some reason), which does not support wayland.

**Comment by Palmitoxico** [comment]
@d3rrial this deprecated version of glutin cannot run under XWayland?

**Comment by d3rrial** [comment]
@Palmitoxico Well, apparently not :/
I'm sorry, I'm not the developer here, I'm just relaying what I'm reading in the documentation and other issues :)

**Comment by polyzen** [comment]
Try this: https://github.com/jwilm/alacritty/issues/112#issuecomment-271039271

**Comment by jwilm** [comment]
The comment linked by @polyzen gives a workaround. As we already [have a tracking issue](https://github.com/jwilm/alacritty/issues/97) for Wayland support, I'm going to close this as a duplicate.
