### ISSUE TITLE
Protocol error, panic on wayland

### ISSUE THREAD

**Issue by petoknm** [jwilm/alacritty#1068]
Just trying to start alacritty but it panics every time.

OS: linux (manjaro/arch)
Display server: Wayland (way-cooler)
Exit code: 101
```shell
> env RUST_BACKTRACE=1 alacritty 
wl_registry@2: error 0: invalid version for global wl_seat (5): have 4, wanted 5
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 71, m
essage: "Protocol error" } }', /checkout/src/libcore/result.rs:916:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:397
             at /checkout/src/libstd/panicking.rs:577
   4: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   5: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   6: core::panicking::panic_fmt
             at /checkout/src/libstd/panicking.rs:498
             at /checkout/src/libcore/panicking.rs:71
   7: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
   8: winit::platform::platform::wayland::window::Window::new
             at /checkout/src/libcore/result.rs:782
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.10.0/src/platform/linux/wayl
and/window.rs:75
   9: winit::window::<impl winit::WindowBuilder>::build
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.10.0/src/platform/linux/mod.
rs:116
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.10.0/src/window.rs:119
  10: glutin::platform::platform::wayland::Context::new
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.12.0/src/platform/linux/way
land.rs:23
  11: glutin::GlWindow::new
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.12.0/src/platform/linux/mod
.rs:47
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.12.0/src/lib.rs:323
  12: alacritty::window::Window::new
             at src/window.rs:204
  13: alacritty::display::Display::new
             at src/display.rs:140
  14: alacritty::main
             at src/main.rs:104
             at src/main.rs:62
  15: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  16: std::panicking::try::do_call
             at /checkout/src/libstd/rt.rs:59
             at /checkout/src/libstd/panicking.rs:480
  17: std::rt::lang_start_internal
             at /checkout/src/libpanic_unwind/lib.rs:101
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:58
  18: main
  19: __libc_start_main
  20: _start

```

**Comment by jwilm** [comment]
Maybe a dupe of #97? If not, I know at least the issue of wl_seat global is discussed there.

**Comment by chrisduerr** [comment]
Is this still present? There have been a lot of updates since this issue was created.

**Comment by petoknm** [comment]
No... I switched to sway and the current version of sway seems to launch without the crash... its still not usable and doesn't look right under wayland but that's another issue.
