### ISSUE TITLE
Thai text displayed incorrectly

### ISSUE THREAD

**Issue by rspeer** [jwilm/alacritty#108]
I work with multilingual data. I was excited to have a terminal that would not slow to a pathetic crawl just because it was asked to show some words in Thai, and saw that Alacritty was doing pretty well at keeping up the frame rate in uncooperative languages.

Two problems, though, which might be related:

* The text rendering in Thai doesn't look right. I think the characters are taking up more character cells than they're supposed to, wrapping in unexpected places, and generally getting smeared all over the screen.
* After a few seconds of displaying Thai text, it crashes.

I'm running on Ubuntu 16.04, and my font is Unifont.

Here's the backtrace:

```
thread 'pty reader' panicked at 'index out of bounds: the len is 231 but the index is 234', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcollections/vec.rs:1371
stack backtrace:
   1:     0x55e76d0b8fca - std::sys::imp::backtrace::tracing::imp::write::h2b860f17b6b0f511
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55e76d0be33f - std::panicking::default_hook::{{closure}}::hedea7d569eb1e6b8
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:349
   3:     0x55e76d0bdf3e - std::panicking::default_hook::he87e0c76c89c52a4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:365
   4:     0x55e76d0be7e7 - std::panicking::rust_panic_with_hook::h304127bde2d3d5e2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:553
   5:     0x55e76d0be674 - std::panicking::begin_panic::h814f60faa3ce8314
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:515
   6:     0x55e76d0be599 - std::panicking::begin_panic_fmt::hf4f7d700fa077693
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:499
   7:     0x55e76d0be527 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:475
   8:     0x55e76d0ea5ed - core::panicking::panic_fmt::hee207ff21fb62166
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x55e76d0ea598 - core::panicking::panic_bounds_check::hca28eae069525a56
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:56
  10:     0x55e76cfb4572 - <alacritty::ansi::Performer<'a, H, W> as vte::Perform>::print::hc3f37ea7fe292a15
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcollections/vec.rs:1371
                        at /home/rspeer/src/alacritty/src/grid.rs:311
                        at /home/rspeer/src/alacritty/src/grid.rs:225
                        at /home/rspeer/src/alacritty/src/term/mod.rs:638
                        at /home/rspeer/src/alacritty/src/ansi.rs:438
  11:     0x55e76cfad00d - <alacritty::event_loop::EventLoop<Io>>::spawn::{{closure}}::h48d857cbcad6c3a4
                        at /home/rspeer/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.1.2/src/lib.rs:167
                        at /home/rspeer/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.1.2/src/lib.rs:137
                        at /home/rspeer/src/alacritty/src/ansi.rs:85
                        at /home/rspeer/src/alacritty/src/event_loop.rs:211
                        at /home/rspeer/src/alacritty/src/event_loop.rs:308
  12:     0x55e76cf9868b - std::panicking::try::do_call::h0f1252efbc6ce7c2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:295
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:458
  13:     0x55e76d0c572a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  14:     0x55e76cfaac3a - <F as alloc::boxed::FnBox<A>>::call_box::h356923938038b1e5
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:434
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/mod.rs:287
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:605
  15:     0x55e76d0bd634 - std::sys::imp::thread::Thread::new::thread_start::h460a0adc61139b06
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  16:     0x7f50f3fc36b9 - start_thread
  17:     0x7f50f3ae382c - clone
  18:                0x0 - <unknown>
child finished with error '1'
```

The Thai text I've got is just sampled from the Common Crawl, so I can point you to the exact file I'm trying to display:

https://s3.amazonaws.com/uploads.hipchat.com/11494/33245/TSThk9XemC0LX6B/thai-example.txt

**Comment by jwilm** [comment]
This is probably an issue with not properly supporting wide characters. This likely needs fallback fonts to be supported correctly.

Does the sample you provided reliably crash Alacritty? If yes, can we make an appropriate subset of it part of Alacritty's test suite?

Supporting international users is important to the project. We've already had requests for supporting IMEs and some exotic keyboard layouts, and I would like to support all of these users.

**Comment by brasilikum** [comment]
Works as reliable big .zip-files too

```
thread 'pty reader' panicked at 'cursor fell off grid', src/term/mod.rs:634
note: Run with `RUST_BACKTRACE=1` for a backtrace.
child finished with error '256'
```

**Comment by Silur** [comment]
also confirmed for /dev/urandom, and any non-ascii file

**Comment by rspeer** [comment]
Yep, just running 'cat' on that file crashes Alacritty every time for me.

**Comment by rspeer** [comment]
What's probably relevant is that Thai has strange text metrics.

It doesn't have wide characters (those that are supposed to take up 2 character cells). What it has is marks that go *between* characters, and therefore are supposed to take up 0 character cells.

**Comment by vks** [comment]
This does not crash for me with the default fonts. (No Thai letters are displayed though.)

**Comment by jwilm** [comment]
@rspeer would you mind testing this on latest master?

**Comment by rspeer** [comment]
Great, it doesn't crash! The Thai text still looks wrong and doesn't scroll or wrap correctly, but that should probably be a separate bug.

**Comment by jwilm** [comment]
Thanks for testing!

Since there's context here, we can just keep this issue going for the display part.

**Comment by rspeer** [comment]
I've concluded that the display part is just the same issue as #265, so closing could also make sense.

**Comment by jwilm** [comment]
Ah cool, and now the issues are linked so your test file is easy to find. Thanks!
