### ISSUE TITLE
Panic with 'capacity overflow'

### ISSUE THREAD

**Issue by vorner** [jwilm/alacritty#1122]
On one of my systems, current alacritty crashes at startup:

```

thread 'main' panicked at 'capacity overflow', libcore/option.rs:917:5
stack backtrace:
   0:     0x55912e09fd73 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h5be622d6bae271e4
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x55912e09e76d - std::panicking::default_hook::{{closure}}::h3dad42fd5277700a
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
                               at libstd/panicking.rs:380
   2:     0x55912e09d176 - std::panicking::rust_panic_with_hook::h17668d919cb963a0
                               at libstd/panicking.rs:396
                               at libstd/panicking.rs:576
   3:     0x55912e09cc02 - std::panicking::begin_panic::hc486239aa11674a1
                               at libstd/panicking.rs:537
   4:     0x55912e09cb79 - std::panicking::begin_panic_fmt::h2d2bb54c3df78ea1
                               at libstd/panicking.rs:521
   5:     0x55912e0b998a - core::panicking::panic_fmt::hee07a740495be6a3
                               at libstd/panicking.rs:497
   6:     0x55912e0c02a8 - core::option::expect_failed::h8c28a7270985f5ac
                               at libcore/option.rs:917
   7:     0x55912dec0e24 - <std::collections::hash::table::RawTable<K, V>>::new::h9be5b206095a0292
                               at /checkout/src/libcore/option.rs:302
                               at /checkout/src/libstd/collections/hash/table.rs:776
                               at /checkout/src/libstd/collections/hash/table.rs:816
   8:     0x55912deb825a - <std::collections::hash::map::HashMap<K, V, S>>::resize::hfcf2613f008e9ae5
                               at /checkout/src/libstd/collections/hash/map.rs:777
   9:     0x55912deb7fec - <std::collections::hash::map::HashMap<K, V, S>>::entry::h5422f5e504c51b41
                               at /checkout/src/libcore/cmp.rs:0
  10:     0x55912dea653b - alacritty::renderer::QuadRenderer::with_loader::hf63d8fc8d3d62172
                               at src/renderer/mod.rs:282
                               at src/renderer/mod.rs:214
                               at src/renderer/mod.rs:200
                               at src/display.rs:227
                               at src/renderer/mod.rs:686
  11:     0x55912ded5f4b - alacritty::display::Display::new::h18ace9deaccdd433
                               at src/display.rs:226
                               at src/display.rs:153
  12:     0x55912de09755 - alacritty::main::h023b5d1d018376be
                               at src/main.rs:104
                               at src/main.rs:62
  13:     0x55912e0f49f5 - std::rt::lang_start::{{closure}}::h924495c33c565557
                               at /checkout/src/libstd/rt.rs:74
  14:     0x55912de14f82 - main
  15:     0x7f30e925e010 - __libc_start_main
  16:     0x55912ddfaa39 - _start
  17:                0x0 - <unknown>
```

On others it is OK. Maybe it is related to the graphics card? The broken system is intel integrated card, while the others have AMDs.

Which operating system does the issue occur on?

Linux

If on linux, are you using X11 or Wayland?

X11.

**Comment by vorner** [comment]
The strange thing is, if I compile with stable, it works, but with nightly (`rustc 1.25.0-nightly (3ec5a99aa 2018-02-14)`) it is broken. Possibly some more UB in the code, or do you think it is the compiler to blame?

**Comment by chrisduerr** [comment]
I'm not sure but if it works with stable, I'd consider it "not our problem" (for now).

It might be interesting to see what the actual issue is though, it could be a problem with the compiler and reporting that would probably be a good idea, so it doesn't come back to bite us once things are stabilized.

**Comment by vorner** [comment]
Further update: before I managed to gather enough data to report it to rustc (finding which version it compiles correctly with, etc), it got fixed ‒ newest nightly works again.

**Comment by chrisduerr** [comment]
That's great to hear, thanks for the report! :)

**Comment by chrisduerr** [comment]
Closing this because it seems like a rust issue.
