### ISSUE TITLE
`ls` at ubuntu 16.10 crashes

### ISSUE THREAD

**Issue by chrmod** [jwilm/alacritty#116]
`RUST_BACKTRACE=1 ./alacritty` outputs that once running `ls`:

```
thread 'pty reader' panicked at 'index out of bounds: the len is 2 but the index is 2', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/slice.rs:640
stack backtrace:
   1:     0x55f57d115dea - std::sys::imp::backtrace::tracing::imp::write::h2b860f17b6b0f511
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55f57d11b15f - std::panicking::default_hook::{{closure}}::hedea7d569eb1e6b8
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:349
   3:     0x55f57d11ad5e - std::panicking::default_hook::he87e0c76c89c52a4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:365
   4:     0x55f57d11b607 - std::panicking::rust_panic_with_hook::h304127bde2d3d5e2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:553
   5:     0x55f57d11b494 - std::panicking::begin_panic::h814f60faa3ce8314
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:515
   6:     0x55f57d11b3b9 - std::panicking::begin_panic_fmt::hf4f7d700fa077693
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:499
   7:     0x55f57d11b347 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:475
   8:     0x55f57d14740d - core::panicking::panic_fmt::hee207ff21fb62166
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x55f57d1473b8 - core::panicking::panic_bounds_check::hca28eae069525a56
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:56
  10:     0x55f57d02df5d - alacritty::ansi::parse_color::he1f954b5b4f73a83
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/slice.rs:640
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/slice.rs:542
                        at /home/chrmod/Projects/opensource/alacritty/src/ansi.rs:732
  11:     0x55f57cff689c - vte::Parser::perform_action::ha595f6d3713fa1a4
                        at /home/chrmod/Projects/opensource/alacritty/src/ansi.rs:630
                        at /home/chrmod/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.1.2/src/lib.rs:205
  12:     0x55f57d009aba - <alacritty::event_loop::EventLoop<Io>>::spawn::{{closure}}::h8a87f59e0d85f278
                        at /home/chrmod/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.1.2/src/lib.rs:158
                        at /home/chrmod/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.1.2/src/lib.rs:137
                        at /home/chrmod/Projects/opensource/alacritty/src/ansi.rs:85
                        at /home/chrmod/Projects/opensource/alacritty/src/event_loop.rs:211
                        at /home/chrmod/Projects/opensource/alacritty/src/event_loop.rs:308
  13:     0x55f57cff518b - std::panicking::try::do_call::h36ad92b485fdc90c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:295
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:458
  14:     0x55f57d12254a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  15:     0x55f57d00797a - <F as alloc::boxed::FnBox<A>>::call_box::h9e0ff91ec3235773
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:434
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/mod.rs:287
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:605
  16:     0x55f57d11a454 - std::sys::imp::thread::Thread::new::thread_start::h460a0adc61139b06
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  17:     0x7f896b4fe709 - start_thread
  18:     0x7f896b0210ae - __clone
  19:                0x0 - <unknown>
child finished with error '1'
```

**Comment by chrmod** [comment]
once running tmux, ls works just fine

**Comment by holygeek** [comment]
repro (ubuntu 16.04.1):

```shell
$ mkdir foo
$ ls -d foo  # ok
$ chmod o+rw foo
$ ls -d foo  # crash
```

The default dircolors setting changes the color of the directory `foo` if it is other-writable (on my system in xterm it is shown in blue with gray background).

**Comment by rockneurotiko** [comment]
Same in archlinux, kernel 4.8.13

**Comment by chrmod** [comment]
https://github.com/jwilm/alacritty/pull/164/commits/180150bbc1b3d14f1a23f9762b7d0e9a9b3ee6ea did not fix the issue

**Comment by chrmod** [comment]
if the issue is related to `ls` colour configuration, here goes the link to my `.dircolors` https://github.com/chrmod/dotfiles/blob/master/.dircolors

**Comment by jwilm** [comment]
I'm aware of a bug that may be causing this; patch forthcoming.

**Comment by jwilm** [comment]
Added a patch to master, fancy giving it a try @chrmod?

**Comment by holygeek** [comment]
These steps no longer make it crash for me:

```
$ mkdir foo
$ ls -d foo  # ok
$ chmod o+rw foo
$ ls -d foo  # ok
```

So I think this issue is fixed

**Comment by jwilm** [comment]
Thanks for the follow-up @holygeek. Going to close this as fixed until we hear otherwise.

**Comment by chrmod** [comment]
can confirm the fix. Thanks! :+1:
