### ISSUE TITLE
Crash when resizing to smaller size

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#12]
```
num_cols, num_lines = Column(213), Line(59)
width: 2560, height: 1600
thread 'pty reader' panicked at 'index out of bounds: the len is 59 but the index is 73', ../src/libcollections/vec.rs:1316
note: Run with `RUST_BACKTRACE=1` for a backtrace.
child finished with error '256'
```

Unfortunately I didn't run with `RUST_BACKTRACE`. Judging by the indices, the cursor line was beyond the bottom of the screen after resizing.

**Comment by quininer** [comment]
I found a similar bug.

1. open `tmux`
2. resize `alacritty`, like <img width="547" alt="screenshot_20170104_211638" src="https://cloud.githubusercontent.com/assets/6286761/21643440/33522b94-d2c3-11e6-9bcd-15e7df6c36b0.png">
3. exit `tmux`

**Comment by sloopjon** [comment]
I built and ran Alacritty on OS X 10.11.6 after seeing it on HN, then crashed it immediately by resizing.  I can reproduce somewhat reliably, but I don't have the exact steps to reproduce.  I think I started a selection by resizing (see issue #47), then triggered this bug by making it smaller.  Here's the output with RUST_BACKTRACE=1:

	num_cols, num_lines = 125, 34
	width: 1750, height: 954
	num_cols, num_lines = 81, 22
	width: 1134, height: 632
	thread 'main' panicked at 'index out of bounds: the len is 22 but the index is 22', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcollections/vec.rs:1362
	stack backtrace:
	   1:        0x10ad0602a - std::sys::imp::backtrace::tracing::imp::write::h1461f67be4bf68a9
	   2:        0x10ad0820f - std::panicking::default_hook::{{closure}}::h6dba65b2b498d274
	   3:        0x10ad07eb7 - std::panicking::default_hook::ha8ecbcff1f59e805
	   4:        0x10ad086d6 - std::panicking::rust_panic_with_hook::h5ceed7bd7aef311a
	   5:        0x10ad08524 - std::panicking::begin_panic::h091a980eb2ddd29a
	   6:        0x10ad08492 - std::panicking::begin_panic_fmt::h063a49cc71e3d103
	   7:        0x10ad083f7 - rust_begin_unwind
	   8:        0x10ad305b0 - core::panicking::panic_fmt::h59374b8a88ef3536
	   9:        0x10ad30528 - core::panicking::panic_bounds_check::h78cc4243bb390438
	  10:        0x10ac94b00 - <collections::string::String as alacritty::term::Term::string_from_selection::Append<core::ops::Range<alacritty::index::Column>>>::append::h153b51df0ccd79d3
	  11:        0x10ac948bb - alacritty::term::Term::string_from_selection::h20bb221207b9a02e
	  12:        0x10ac4f8f1 - <alacritty::event::Processor<N>>::handle_event::h1e7e30ba1888252f
	  13:        0x10ac6a0d3 - alacritty::run::h0e504c85ed6c95f9
	  14:        0x10ac67f5b - alacritty::main::h5f43ad1d1556571c
	  15:        0x10ad095aa - __rust_maybe_catch_panic
	  16:        0x10ad08a76 - std::rt::lang_start::ha9be7b379cf1665e

**Comment by sloopjon** [comment]
I can reproduce this crash reliably as follows:

1. Make a small resize, bigger or smaller doesn't matter. Notice that the mouse is now in select mode.
2. Reduce the height of the window.
3. Click in the window.

**Comment by sliceofcode** [comment]
I have also gotten this strange backtrace using @quininer's `tmux` method.

```
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
[Unhandled CSI] action='l', args=[1005], intermediates=[63]
[unhandled osc_start]
[unhandled osc_put] byte='1'
[unhandled osc_put] byte='1'
[unhandled osc_put] byte='2'
[unhandled osc_end] byte=0
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
[unhandled osc_start]
[unhandled osc_put] byte='1'
[unhandled osc_put] byte='1'
[unhandled osc_put] byte='2'
[unhandled osc_end] byte=0
[Unhandled CSI] action='l', args=[1005], intermediates=[63]
thread 'pty reader' panicked at 'slice index starts at 18446744073709551615 but ends at 2', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/slice.rs:566
stack backtrace:
   1:     0x563e77f442da - std::sys::imp::backtrace::tracing::imp::write::h2b860f17b6b0f511
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x563e77f4964f - std::panicking::default_hook::{{closure}}::hedea7d569eb1e6b8
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:349
   3:     0x563e77f4924e - std::panicking::default_hook::he87e0c76c89c52a4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:365
   4:     0x563e77f49af7 - std::panicking::rust_panic_with_hook::h304127bde2d3d5e2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:553
   5:     0x563e77f49984 - std::panicking::begin_panic::h814f60faa3ce8314
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:515
   6:     0x563e77f498a9 - std::panicking::begin_panic_fmt::hf4f7d700fa077693
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:499
   7:     0x563e77f49837 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:475
   8:     0x563e77f758fd - core::panicking::panic_fmt::hee207ff21fb62166
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x563e77f75a49 - core::slice::slice_index_order_fail::h82b04058aa2543c9
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/slice.rs:566
  10:     0x563e77e2715f - vte::Parser::perform_action::h9809fbd2f5f3f1a2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/slice.rs:701
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/slice.rs:777
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/slice.rs:553
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcollections/vec.rs:1449
                        at /home/cheesy/dev/prg/alacritty/src/grid.rs:388
                        at /home/cheesy/dev/prg/alacritty/src/term/mod.rs:923
                        at /home/cheesy/dev/prg/alacritty/src/ansi.rs:556
                        at /home/cheesy/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.1.2/src/lib.rs:205
  11:     0x563e77e37f5a - <alacritty::event_loop::EventLoop<Io>>::spawn::{{closure}}::h1d3fe9bebd8a0f1b
                        at /home/cheesy/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.1.2/src/lib.rs:158
                        at /home/cheesy/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.1.2/src/lib.rs:137
                        at /home/cheesy/dev/prg/alacritty/src/ansi.rs:85
                        at /home/cheesy/dev/prg/alacritty/src/event_loop.rs:211
                        at /home/cheesy/dev/prg/alacritty/src/event_loop.rs:308
  12:     0x563e77e2362b - std::panicking::try::do_call::h8d8e3af02009a9c0
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:295
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:458
  13:     0x563e77f50a3a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  14:     0x563e77e35e1a - <F as alloc::boxed::FnBox<A>>::call_box::ha052c9c415d3d598
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:434
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/mod.rs:287
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:605
  15:     0x563e77f48944 - std::sys::imp::thread::Thread::new::thread_start::h460a0adc61139b06
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  16:     0x7ffad1086453 - start_thread
  17:     0x7ffad0bb27de - __GI___clone
  18:                0x0 - <unknown>
thread 'main' panicked at 'index 18446744073709551614 out of range for slice of length 2', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/slice.rs:560
stack backtrace:
   1:     0x563e77f442da - std::sys::imp::backtrace::tracing::imp::write::h2b860f17b6b0f511
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x563e77f4964f - std::panicking::default_hook::{{closure}}::hedea7d569eb1e6b8
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:349
   3:     0x563e77f4924e - std::panicking::default_hook::he87e0c76c89c52a4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:365
   4:     0x563e77f49af7 - std::panicking::rust_panic_with_hook::h304127bde2d3d5e2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:child finished with error '256'
```

**Comment by CarwynNelson** [comment]
I am able to reproduce using @sloopjon's method. Here is a backtrace:

```
thread 'main' panicked at 'index out of bounds: the len is 22 but the index is 22', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcollections/vec.rs:1362
stack backtrace:
   1:        0x10b96f31a - std::sys::imp::backtrace::tracing::imp::write::h1461f67be4bf68a9
   2:        0x10b9716bf - std::panicking::default_hook::{{closure}}::h6dba65b2b498d274
   3:        0x10b971367 - std::panicking::default_hook::ha8ecbcff1f59e805
   4:        0x10b971b86 - std::panicking::rust_panic_with_hook::h5ceed7bd7aef311a
   5:        0x10b9719d4 - std::panicking::begin_panic::h091a980eb2ddd29a
   6:        0x10b971942 - std::panicking::begin_panic_fmt::h063a49cc71e3d103
   7:        0x10b9718a7 - rust_begin_unwind
   8:        0x10b999a60 - core::panicking::panic_fmt::h59374b8a88ef3536
   9:        0x10b9999d8 - core::panicking::panic_bounds_check::h78cc4243bb390438
  10:        0x10b766025 - <collections::vec::Vec<T> as core::ops::Index<usize>>::index::hfcf6f46dd9bd980c
  11:        0x10b7898b4 - <alacritty::grid::Grid<T> as core::ops::Index<alacritty::index::Line>>::index::h3345e7a3dd0120cf
  12:        0x10b796435 - <collections::string::String as alacritty::term::Term::string_from_selection::Append<core::ops::Range<alacritty::index::Column>>>::append::h1901765bef7da69f
  13:        0x10b796a8d - <collections::string::String as alacritty::term::Term::string_from_selection::Append<core::ops::RangeFull>>::append::h8b5d4b2c6f0558af
  14:        0x10b7961c8 - alacritty::term::Term::string_from_selection::h42a81022b5208efd
  15:        0x10b6b7290 - <alacritty::input::Processor<'a, N>>::on_mouse_release::haab609e4f8690224
  16:        0x10b6b641d - <alacritty::input::Processor<'a, N>>::mouse_input::h5ef4a6578e9bc6dc
  17:        0x10b67b4ec - <alacritty::event::Processor<N>>::handle_event::haf93bac7f1aa838d
  18:        0x10b67c0ac - <alacritty::event::Processor<N>>::process_events::h83f39aa23b7971d2
  19:        0x10b6e9004 - alacritty::run::hf662197f9afe91db
  20:        0x10b6e7c4f - alacritty::main::hb3261df89a837dbf
  21:        0x10b972a5a - __rust_maybe_catch_panic
  22:        0x10b971f26 - std::rt::lang_start::ha9be7b379cf1665e
  23:        0x10b6e98f9 - main
```

**Comment by robinduckett** [comment]
built from master yesterday, issue persists on Linux, resizing the window too small makes it crash. I kinda like this as a feature though.

**Comment by DivineGod** [comment]
I have been reproducing the issue with a release build and a debug build. Strangely enough using the same steps to reproduce as @sloopjon I get two different errors consistently. Might be related; haven't looked into it yet..

Release build:

```
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcollections/vec.rs:1362
stack backtrace:
   1:        0x1047d5736 - std::sys::imp::backtrace::tracing::imp::write::hd3b65cdfe843284c
   2:        0x1047d4b42 - std::panicking::default_hook::{{closure}}::hf2b7428652613d83
   3:        0x1047d3d63 - std::panicking::rust_panic_with_hook::hcef1e67c646c6802
   4:        0x1047d38f1 - std::panicking::begin_panic::hc2e8ca89533cd10d
   5:        0x1047d3862 - std::panicking::begin_panic_fmt::h60990696c3c3a88d
   6:        0x1047e56be - core::panicking::panic_fmt::h10231c789bd0e97d
   7:        0x1047e553c - core::panicking::panic_bounds_check::hb351a373447937ca
   8:        0x1047450b4 - <collections::string::String as alacritty::term::Term::string_from_selection::Append<core::ops::Range<alacritty::index::Column>>>::append::h2d59e95360631821
   9:        0x10468724e - <alacritty::event::ActionContext<'a, N> as alacritty::input::ActionContext>::copy_selection::h049f5cbde36a3418
  10:        0x10469ae6b - <alacritty::event::Processor<N>>::handle_event::h2fac0b85e4a49c21
  11:        0x1046b4fd2 - alacritty::run::h92e8477f003aa0bd
  12:        0x1046b0d1c - alacritty::main::h36dd76db3fb63abf
  13:        0x1046be0cf - main
```

Debug build:

```
thread 'main' panicked at 'attempt to subtract with overflow', src/index.rs:439
stack backtrace:
   1:        0x10cd018ba - std::sys::imp::backtrace::tracing::imp::write::hd3b65cdfe843284c
   2:        0x10cd0670f - std::panicking::default_hook::{{closure}}::hf2b7428652613d83
   3:        0x10cd063b7 - std::panicking::default_hook::h5da8f27db5582938
   4:        0x10cd06bd6 - std::panicking::rust_panic_with_hook::hcef1e67c646c6802
   5:        0x10cd06a74 - std::panicking::begin_panic::hc2e8ca89533cd10d
   6:        0x10cd06992 - std::panicking::begin_panic_fmt::h60990696c3c3a88d
   7:        0x10cd068f7 - rust_begin_unwind
   8:        0x10cd2ebc0 - core::panicking::panic_fmt::h10231c789bd0e97d
   9:        0x10cd2eac4 - core::panicking::panic::h5e44af975c0a7e4d
  10:        0x10ca2e019 - <alacritty::index::Line as core::ops::Sub<usize>>::sub::he957d381e2be1f57
  11:        0x10c9d73e5 - alacritty::term::SizeInfo::pixels_to_coords::h0a1452a3fb7a43b0
  12:        0x10c818102 - <alacritty::input::Processor<'a, A>>::mouse_moved::h26e7242f9b315467
  13:        0x10c7dafcc - <alacritty::event::Processor<N>>::handle_event::h1c8a06ede1c6af1f
  14:        0x10c7db879 - <alacritty::event::Processor<N>>::process_events::h8f79a85298a5777a
  15:        0x10c849409 - alacritty::run::h8bc6d95e75dbb4ca
  16:        0x10c847c91 - alacritty::main::h051f8b649317e25f
  17:        0x10cd07aaa - __rust_maybe_catch_panic
  18:        0x10cd06f76 - std::rt::lang_start::h87cb84a8b6cb187e
  19:        0x10c849d69 - main
```

**Comment by jwilm** [comment]
Should be fixed
