### ISSUE TITLE
scrollback: thread 'pty reader' panicked at 'attempt to subtract with overflow', src/index.rs:168:28

### ISSUE THREAD

**Issue by matthiaskrgr** [jwilm/alacritty#1515]
alacritty @ scrollback , 8e8ecdd, debug build 

````
RUST_BACKTRACE=full target/debug/alacritty  -vvvvvvvvvvvvvv
...
[unhandled] execute byte=06
[unhandled] execute byte=1f
[unhandled] execute byte=13
[unhandled] execute byte=95
[unhandled] execute byte=9c
[unhandled] execute byte=1e
[unhandled] execute byte=19
[unhandled] execute byte=95
[unhandled] execute byte=12
[unhandled] esc_dispatch params=[], ints=[42], byte='P' (50)
[unhandled] execute byte=10
[unhandled] execute byte=1f
[unhandled] execute byte=11
carriage_return
linefeed
scroll_up_relative: origin=0, lines=1
[unhandled] execute byte=11
[unhandled] execute byte=8b
[unhandled] execute byte=06
[unhandled] execute byte=8b
[unhandled] execute byte=02
[unhandled] execute byte=13
carriage_return
put_tab: 1
[unhandled] execute byte=8f
set_horizontal_tabstop
[unhandled] execute byte=99
[unhandled] execute byte=15
Activate G1 character set
carriage_return
[unhandled] execute byte=8d
[unhandled] execute byte=02
bell
[unhandled] execute byte=94
[unhandled] execute byte=9c
[unhandled] execute byte=06
[unhandled] execute byte=1e
carriage_return
Activate G1 character set
[unhandled] execute byte=16
[unhandled] execute byte=03
[unhandled] execute byte=03
[unhandled] execute byte=8c
[unhandled] execute byte=04
insert_blank_lines: 3
scroll_down_relative: origin=31, lines=3
thread 'pty reader' panicked at 'attempt to subtract with overflow', src/index.rs:168:28
stack backtrace:
   0:     0x55b47acc414e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h1410ee01a7694834
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x55b47acafcc6 - std::sys_common::backtrace::print::h1962f4c30d928b1d
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x55b47acadf1d - std::panicking::default_hook::{{closure}}::h66071f1a30ddacaa
                               at libstd/panicking.rs:211
   3:     0x55b47acadc90 - std::panicking::default_hook::h8288f681d56575d2
                               at libstd/panicking.rs:227
   4:     0x55b47acae58c - std::panicking::rust_panic_with_hook::h46fa5def146c1328
                               at libstd/panicking.rs:475
   5:     0x55b47acae189 - std::panicking::continue_panic_fmt::h9933c8abec1f0661
                               at libstd/panicking.rs:390
   6:     0x55b47acae085 - rust_begin_unwind
                               at libstd/panicking.rs:325
   7:     0x55b47ad0cb5b - core::panicking::panic_fmt::h380215f9f52a35ae
                               at libcore/panicking.rs:77
   8:     0x55b47ad0ca8a - core::panicking::panic::hfeaf7953a9669be7
                               at libcore/panicking.rs:52
   9:     0x55b47a537b43 - <alacritty::index::Line as core::ops::arith::Sub>::sub::hee42d53b1ad43d6b
                               at src/index.rs:168
  10:     0x55b47a41ccc0 - <alacritty::grid::storage::Storage<T> as core::ops::index::IndexMut<alacritty::index::Line>>::index_mut::h9e2a559a93584c63
                               at src/grid/storage.rs:304
  11:     0x55b47a345cbe - <alacritty::grid::Grid<T>>::scroll_down::h5fa0767da63d2333
                               at /home/matthias/vcs/github/alacritty/src/grid/mod.rs:341
  12:     0x55b47a313604 - alacritty::term::Term::scroll_down_relative::h5dfe11f171e7bf7f
                               at /home/matthias/vcs/github/alacritty/src/term/mod.rs:1217
  13:     0x55b47a30f688 - <alacritty::term::Term as alacritty::ansi::Handler>::insert_blank_lines::he44b6d631b7f9a5f
                               at /home/matthias/vcs/github/alacritty/src/term/mod.rs:1609
  14:     0x55b47a2e391c - <alacritty::ansi::Performer<'a, H, W> as vte::Perform>::csi_dispatch::hbd61a644d937236a
                               at /home/matthias/vcs/github/alacritty/src/ansi.rs:982
  15:     0x55b47a31c27f - vte::Parser::perform_action::hf0607860be14cde6
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.3.3/src/lib.rs:302
  16:     0x55b47a31c818 - vte::Parser::perform_state_change::hb54370ebca766a9e
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.3.3/src/lib.rs:177
  17:     0x55b47a31ca32 - vte::Parser::advance::ha95160097f280db7
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.3.3/src/lib.rs:156
  18:     0x55b47a2e9cec - alacritty::ansi::Processor::advance::h2d1b9b6bad770ef8
                               at /home/matthias/vcs/github/alacritty/src/ansi.rs:162
  19:     0x55b47a2ff979 - <alacritty::event_loop::EventLoop<Io>>::pty_read::hee6a7ef839c5ad07
                               at /home/matthias/vcs/github/alacritty/src/event_loop.rs:289
  20:     0x55b47a2fe911 - <alacritty::event_loop::EventLoop<Io>>::spawn::{{closure}}::h3dd1fb3f7baabde6
                               at /home/matthias/vcs/github/alacritty/src/event_loop.rs:405
  21:     0x55b47a2c533c - std::sys_common::backtrace::__rust_begin_short_backtrace::h9cdd912511cf94dc
                               at /checkout/src/libstd/sys_common/backtrace.rs:136
  22:     0x55b47a2fadbe - std::thread::Builder::spawn::{{closure}}::{{closure}}::h8af81224ab5ed292
                               at /checkout/src/libstd/thread/mod.rs:409
  23:     0x55b47a2e9d7e - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he07e358c15b64707
                               at /checkout/src/libstd/panic.rs:313
  24:     0x55b47a336e36 - std::panicking::try::do_call::h7056b8144f4498a9
                               at /checkout/src/libstd/panicking.rs:310
  25:     0x55b47acd4879 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  26:     0x55b47a336b0c - std::panicking::try::h4eba685fa36d9ad1
                               at /checkout/src/libstd/panicking.rs:289
  27:     0x55b47a2e9dce - std::panic::catch_unwind::h686899bd357654c9
                               at /checkout/src/libstd/panic.rs:392
  28:     0x55b47a2fab80 - std::thread::Builder::spawn::{{closure}}::h73119e89602807d1
                               at /checkout/src/libstd/thread/mod.rs:408
  29:     0x55b47a2faf04 - <F as alloc::boxed::FnBox<A>>::call_box::h55ea712babd979d1
                               at /checkout/src/liballoc/boxed.rs:642
  30:     0x55b47acc6c5a - std::sys_common::thread::start_thread::h3a34c6b444d6a7c4
                               at /checkout/src/liballoc/boxed.rs:652
                               at libstd/sys_common/thread.rs:24
  31:     0x55b47acaed05 - std::sys::unix::thread::Thread::new::thread_start::h72aa9e5ed18ab2e2
                               at libstd/sys/unix/thread.rs:90
  32:     0x7f5c9bc50a9c - start_thread
  33:     0x7f5c9bb64a42 - clone
  34:                0x0 - <unknown>
thread 'main' panicked at 'Error sending shutdown to event loop: Disconnected', libcore/result.rs:983:5
stack backtrace:
   0:     0x55b47acc414e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h1410ee01a7694834
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x55b47acafcc6 - std::sys_common::backtrace::print::h1962f4c30d928b1d
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x55b47acadf1d - std::panicking::default_hook::{{closure}}::h66071f1a30ddacaa
                               at libstd/panicking.rs:211
   3:     0x55b47acadc90 - std::panicking::default_hook::h8288f681d56575d2
                               at libstd/panicking.rs:227
   4:     0x55b47acae58c - std::panicking::rust_panic_with_hook::h46fa5def146c1328
                               at libstd/panicking.rs:475
   5:     0x55b47acae189 - std::panicking::continue_panic_fmt::h9933c8abec1f0661
                               at libstd/panicking.rs:390
   6:     0x55b47acae085 - rust_begin_unwind
                               at libstd/panicking.rs:325
   7:     0x55b47ad0cb5b - core::panicking::panic_fmt::h380215f9f52a35ae
                               at libcore/panicking.rs:77
   8:     0x55b47a35c2b5 - core::result::unwrap_failed::h1086413067e79e6b
                               at /checkout/src/libcore/macros.rs:26
   9:     0x55b47a3580ef - <core::result::Result<T, E>>::expect::h29a064c70f571125
                               at /checkout/src/libcore/result.rs:809
  10:     0x55b47a319801 - alacritty::run::h351d5eab68f2ccb0
                               at src/main.rs:210
  11:     0x55b47a318135 - alacritty::main::hd3f5b69239efe5a4
                               at src/main.rs:59
  12:     0x55b47a337def - std::rt::lang_start::{{closure}}::h80ee2703d4a00f38
                               at /checkout/src/libstd/rt.rs:74
  13:     0x55b47acae022 - std::panicking::try::do_call::hc3bbfe344c9dd679
                               at libstd/rt.rs:59
                               at libstd/panicking.rs:310
  14:     0x55b47acd4879 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  15:     0x55b47acbd735 - std::rt::lang_start_internal::h6831243cb445d5dc
                               at libstd/panicking.rs:289
                               at libstd/panic.rs:392
                               at libstd/rt.rs:58
  16:     0x55b47a337dc7 - std::rt::lang_start::hefe3975268cd17b7
                               at /checkout/src/libstd/rt.rs:74
  17:     0x55b47a319cb9 - main
  18:     0x7f5c9ba8d222 - __libc_start_main
  19:     0x55b47a2bf02d - _start
  20:                0x0 - <unknown>

````

in the new debug alacritty window:
````
cat /dev/urandom
[prints random chars]
wait until crash
````

**Comment by matthiaskrgr** [comment]
This probably only happens in alacritty verbose mode.

**Comment by chrisduerr** [comment]
I can reproduce it both with and without verbose output. However it only happens in debug mode for me, not in release mode.

I'll be looking into it, thanks for the report.

**Comment by chrisduerr** [comment]
This bug's origin is [here]() and can be reproduced by running `printf '\e[1000L'`. I'll look into writing up a quick fix.
