### ISSUE TITLE
benchmark term::benches::render_iter hits assertion

### ISSUE THREAD

**Issue by matthiaskrgr** [jwilm/alacritty#1604]
Linux, x11, alacritty 1887722ef5b6ac1c1f0e4e4f62cbb02b609c1d4b
````
RUST_BACKTRACE=full cargo test --features bench

test tty::test_get_pw_entry ... ok
test util::tests::limit_works ... ok
test term::tests::reset_font_size_works ... ok
test term::tests::semantic_selection_works ... ok
test term::benches::render_iter ... FAILED

failures:

---- term::benches::render_iter stdout ----
problem with config: env: invalid type: unit value, expected a map at line 17 column 1; Using default value
thread 'term::benches::render_iter' panicked at 'assertion failed: requested < self.len', src/grid/storage.rs:199:9
stack backtrace:
   0:     0x5650acce5b1e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hc8c91577d093e317
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x5650accdcc06 - std::sys_common::backtrace::print::hbc0beba32f0eb014
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x5650accd3aad - std::panicking::default_hook::{{closure}}::h972cd4d944f002f7
                               at libstd/panicking.rs:211
   3:     0x5650accd378f - std::panicking::default_hook::h42def9501b24a8c9
                               at libstd/panicking.rs:221
   4:     0x5650accd412c - std::panicking::rust_panic_with_hook::h509909925427996b
                               at libstd/panicking.rs:477
   5:     0x5650acca983f - std::panicking::begin_panic::h72a675c3b716466e
                               at libstd/panicking.rs:411
   6:     0x5650acaa7aae - <alacritty::grid::storage::Storage<T>>::compute_index::h7fd6b5626dd06a6a
                               at src/grid/storage.rs:199
   7:     0x5650acaa87ac - <alacritty::grid::storage::Storage<T> as core::ops::index::Index<usize>>::index::h544c5f0d9d96dbf2
                               at src/grid/storage.rs:280
   8:     0x5650acaa8923 - <alacritty::grid::storage::Storage<T> as core::ops::index::Index<alacritty::index::Line>>::index::hee8bd9c6f967eb6f
                               at src/grid/storage.rs:298
   9:     0x5650aca99bf9 - <alacritty::grid::Grid<T> as core::ops::index::Index<alacritty::index::Line>>::index::h27687ac52e3de389
                               at src/grid/mod.rs:502
  10:     0x5650aca99d6f - <alacritty::grid::Grid<T> as core::ops::index::Index<&'point alacritty::index::Point>>::index::h0b630f9af36ed97b
                               at src/grid/mod.rs:528
  11:     0x5650aca8bbea - alacritty::term::RenderableCellsIter::populate_char_cursor::h302c9e85ebebc266
                               at src/term/mod.rs:243
  12:     0x5650aca8bd57 - alacritty::term::RenderableCellsIter::populate_box_cursor::hf35aa1f4f44e159d
                               at src/term/mod.rs:265
  13:     0x5650aca8bfbf - alacritty::term::RenderableCellsIter::initialize::hac6cf1f8cc30af7f
                               at src/term/mod.rs:295
  14:     0x5650aca8b70e - alacritty::term::RenderableCellsIter::new::hf6230cb01360d9c8
                               at src/term/mod.rs:179
  15:     0x5650aca8ec0f - alacritty::term::Term::renderable_cells::h2785eac2bb933c38
                               at src/term/mod.rs:1072
  16:     0x5650aca8a848 - alacritty::term::benches::render_iter::{{closure}}::hc7bc8f675c8fbc42
                               at src/term/mod.rs:2287
  17:     0x5650acabd150 - test::ns_iter_inner::h339b327621fc6f3f
                               at libtest/lib.rs:1591
  18:     0x5650acabe1dd - test::Bencher::iter::hb9fcca0f84010df7
                               at libtest/lib.rs:1565
  19:     0x5650acb3d72a - alacritty::term::benches::render_iter::h6d37c9aea833b466
                               at src/term/mod.rs:2286
  20:     0x5650aca8a807 - alacritty::term::benches::render_iter::{{closure}}::hd7578232e6639f10
                               at src/term/mod.rs:2269
  21:     0x5650aca9fa97 - core::ops::function::FnOnce::call_once::h91d048a54bbc88de
                               at libcore/ops/function.rs:238
  22:     0x5650acbc3707 - <F as alloc::boxed::FnBox<A>>::call_box::h74be15bbe7f5a2f4
                               at libtest/lib.rs:1374
                               at libtest/lib.rs:1576
                               at libtest/lib.rs:1739
                               at libtest/lib.rs:1374
                               at libcore/ops/function.rs:238
                               at liballoc/boxed.rs:661
  23:     0x5650acbc3752 - <F as alloc::boxed::FnBox<A>>::call_box::ha375b85290684029
                               at libtest/lib.rs:1461
                               at liballoc/boxed.rs:661
  24:     0x5650accf62d9 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  25:     0x5650acbe833d - std::sys_common::backtrace::__rust_begin_short_backtrace::hf895f1b57b851c2a
                               at libstd/panicking.rs:289
                               at libstd/panic.rs:392
                               at libtest/lib.rs:1423
                               at libstd/sys_common/backtrace.rs:136
  26:     0x5650acbe7dc4 - std::panicking::try::do_call::h292103d54081997c
                               at libstd/thread/mod.rs:409
                               at libstd/panic.rs:313
                               at libstd/panicking.rs:310
  27:     0x5650accf62d9 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  28:     0x5650acbe3b16 - <F as alloc::boxed::FnBox<A>>::call_box::hf82eb4ccddcc5839
                               at libstd/panicking.rs:289
                               at libstd/panic.rs:392
                               at libstd/thread/mod.rs:408
                               at liballoc/boxed.rs:661
  29:     0x5650acce8e4a - std::sys_common::thread::start_thread::hf2bb3091b848c790
                               at liballoc/boxed.rs:671
                               at libstd/sys_common/thread.rs:24
  30:     0x5650accd53f5 - std::sys::unix::thread::Thread::new::thread_start::hef06cacd1edd972e
                               at libstd/sys/unix/thread.rs:90
  31:     0x7f7ba903da9c - start_thread
  32:     0x7f7ba8f53a42 - clone
  33:                0x0 - <unknown>


````

**Comment by chrisduerr** [comment]
Looks like it's failing trying to deserialize the grid:
https://github.com/jwilm/alacritty/blob/master/src/term/mod.rs#L2278.

I suspect that this might be related to the commit which dynamically initialized the grid and added the following (which is relevant for deserialization):
https://github.com/jwilm/alacritty/blob/master/src/grid/mod.rs#L99

Would you mind bisecting this? If I had to take a guess, I'd assume that [this](https://github.com/jwilm/alacritty/commit/3d7e88e8a975f40996aaa71d951842db6f2fccbb) commit broke it.

**Comment by matthiaskrgr** [comment]
The assertion is triggered already before the linked commit.

**Comment by matthiaskrgr** [comment]
Unfortunately there is a large timeframe with build failures :/
good = bench passes
bad = bench hits assertion
````
     1  1887722 // bad 
     2  8807693
     3  9383711
     4  5e97fcb
     5  593d771
     6  94b9345
     7  2ef376b
     8  ec3a804
     9  3d7e88e
    10  a752066
    11  cd79680
    12  9b694fc
    13  cee35b3
    14  6cfd7ae
    15  34ba485
    16  3b46859
    17  641f329
    18  417ad9d
    19  177a5c3
    20  6e98593
    21  ef06109
    22  a769e80
    23  26c4043
    24  bd6e5a9
    25  d387ebe
    26  f0ce64e
    27  05d40a8
    28  00bd098
    29  63a40df
    30  55e675a
    31  a10403b
    32  e2c1e56
    33  35ea0cd
    34  7a8a002
    35  1f24346
    36  8b71eed
    37  cff58e9
    38  054e38e
    39  ca1b75b
    40  43882ad
    41  7249517
    42  8e8ecdd
    43  7717bd7
    44  facab5b
    45  23601fb
    46  5d2faf4
    47  7c5585f
    48  c4a0f9c
    49  0ca5c7a
    50  b59fd21 // bad  
    51  f50ca1a // bad :(
    52  b05ad74
    53  cde1d8d // fails to build 
    54  07aaf05
    55  bfd62ef
    56  4631ca4
    57  24c50fa // fails to build 
    58  a2f9988
    59  9a98d5e
    60  efc568b
    61  169b87e
    62  5a11f85 // fails to build 
    63  c61a912
    64  4b1a3b1
    65  ac93f6d
    66  6cddceb
    67  eabd6bb
    68  a3c6c1d
    69  c01ce1e
    70  c3b7b98
    71  dec3ee2
    72  8168d85
    73  31c0f29 // fails to build 
    74  d393705
    75  2234234
    76  d8bda60
    77  bfa9265
    78  4df0912
    79  0d900cd
    80  fe749cf
    81  e615d11
    82  7f2fe5a
    83  334d50e
    84  b19045d // fails to build 
    85  f66e3e4
    86  5431438
    87  b0f655a
    88  688cabe
    89  4333b2f
    90  f463816 // fails to build
    91  0dcb9ca
    92  2c7bb9a
    93  e20aa55
    94  b0f272f
    95  58c69ca
    96  d9bd21d
    97  a238e9a
    98  d3f6407
    99  a2f127a
   100  dab0eca // fails to build 
   101  231ef51
   102  786e274
   103  9a5a0ec
   104  0408618
   105  dd60ea5
   106  0484a07
   107  c006dae
   108  4521260
   109  8018dee
   110  8ef062e
   111  ef3c384
   112  54d50ed
   113  c49a7e8 // fails to build 
   114  7fe6774
   115  f67b17c
   116  9b9b138
   117  5748066 // fails to build
   118  45c2b3f
   119  94796a7
   120  84769ce
   121  92b11cf // fails to build 
   122  f136859
   123  350bb8c // fails to build
   124  a88961b
   125  4ed2500  // fails to build 
   126  6fc0e1e
   127  2774259  // fails to build 
   128  bbe276e // good 
   129  fd7c1bf // good 
````

**Comment by chrisduerr** [comment]
That almost looks a bit arbitrary to me. With the latest master working on my machine, I wonder if it's actually an issue with the specific commits.

I've benchmarked multiple times, just to make sure this is completely reproducible and I haven't managed to make it fail once. So maybe it's system related?

**Comment by chrisduerr** [comment]
Looks like the issue is that `len` set on `Storage` is `0`, since it's marked `#[serde(skip)]` (see [here](https://github.com/jwilm/alacritty/blob/master/src/grid/storage.rs#L35-L36)). This is fine for the normal ref tests, since all they need to do with the serialized grid is compare it to the calculated one. However when doing anything with that deserialized grid, a length is required.

Changing this to `#[serde(default)]` and manually adding a `len` value to the serialized grid should fix this issue from what I can tell. It's possible that other issues might come up once that's resolved, but it should work for this case.
