### ISSUE TITLE
Crash when I `cat` a file

### ISSUE THREAD

**Issue by Geobert** [jwilm/alacritty#1674]
On windows, I tried cat attached txt file and it crashed.
[protonmail_gray.txt](https://github.com/jwilm/alacritty/files/2488781/protonmail_gray.txt)

**Comment by chrisduerr** [comment]
The only thing I can see with this which might cause issues is that it's missing a newline at the end of the file. That shouldn't crash anything, but would you mind adding a newline to the end of the file, just to troubleshoot where the issue is coming from?

Also, just to make sure: When you say 'it crashed', you're talking about Alacritty? Or are you talking about `cat`?

**Comment by Geobert** [comment]
I tried with missing newline and Alacritty still crashes, the window suddenly disap
[protonmail_gray.txt](https://github.com/jwilm/alacritty/files/2488813/protonmail_gray.txt)
pear.

**Comment by chrisduerr** [comment]
Does `cat` work with any other file? It looks like there should be nothing special about the new version of the file you've sent. No special characters, escape sequences or missing newlines.

**Comment by Geobert** [comment]
[tags.txt](https://github.com/jwilm/alacritty/files/2488826/tags.txt)
This file works fine, it's… really strange ^^'

**Comment by chrisduerr** [comment]
@Geobert When starting Alacritty from a different instance of Alacritty, is there any error output?

**Comment by Geobert** [comment]
Unfortunately, no :(

**Comment by chrisduerr** [comment]
I can't test on Windows, but it looks like Alacritty chooses to close down itself. It probably shouldn't be super complicated to figure out why that is, but it would require some debugging.

Maybe @zacps can take a look at this? Would be interesting to see if this can be reproduced first.

**Comment by Geobert** [comment]
I suppose on your system, it does not crash?

**Comment by PrsPrsBK** [comment]
Hi. @chrisduerr, I noticed both protonmail_gray.txt start with Byte Order Mark `EF BB BF`.
Is it problem?

**Comment by Geobert** [comment]
Good catch @PrsPrsBK I've changed the encoding and it does not crash any more!

**Comment by chrisduerr** [comment]
@Geobert It does not crash on my system, since I'm running Linux. But great catch @PrsPrsBK.

**Comment by PrsPrsBK** [comment]
@Geobert It's nice!

@chrisduerr I had bad experiences due to BOM. 
I see, it need to see `cat`'s  output (if exists). thanks.

**Comment by zacps** [comment]
I can't seem to reproduce this?

Under bash (WSL):

```
$ cat protonmail_gray.txt
﻿.conversation.read {
 background: #dddddd;!important
}

.conversation {
background: #dddddd;!important
}

#conversation-view .frame, #pm_main {
 background: #dddddd;!important
 }

.composer-container, .squire-container {
background-color: #dddddd;!important
```

Under cmd (using `type`):

```
F:\Downloads\Temp>type protonmail_gray.txt
´╗┐.conversation.read {
 background: #dddddd;!important
}

.conversation {
background: #dddddd;!important
}

#conversation-view .frame, #pm_main {
 background: #dddddd;!important
 }

.composer-container, .squire-container {
background-color: #dddddd;!important
}
```

**Comment by Geobert** [comment]
[ala.log](https://github.com/jwilm/alacritty/files/2493113/ala.log)
I got a panick message this time :D

**Comment by chrisduerr** [comment]
@Geobert If you could run this with `RUST_BACKTRACE=1`, that would be really helpful. Like this the full backtrace is unfortunately not shown.

**Comment by Geobert** [comment]
Of course!
```
J:\Downloads>thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore\option.rs:345:21
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: winpty_spawn_config_new
  15: BaseThreadInitThunk
  16: RtlUserThreadStart
```

**Comment by chrisduerr** [comment]
@Geobert Unfortunately it looks like the backtraces aren't available in the version of Alacritty you're running. If you could try running it in debug mode (`cargo run` instead of `cargo run --release`), the full backtrace should be available.

**Comment by Geobert** [comment]
I was running the bin from appveyor. I tried a compilation, but it fails:
```
--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any of [\'clang.dll\', \'libclang.dll\'], set the LIBCLANG_PATH environment variable to a path where one of these files can be found (skipped: [])"', libcore\result.rs:945:5
```

**Comment by zacps** [comment]
@Geobert Alacrity requires Clang for Windows builds. This is listed in INSTALL.md

@chrisduerr I think it might be a panic because of an exception raised in winpty.

**Comment by martin-sucha** [comment]
I was able to reproduce this today with latest master (commit `4380d0864b1098909bdcfec132b866c34924517e`), here is a backtrace:

```
$ RUST_BACKTRACE=1 ./target/debug/alacritty.exe
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore\option.rs:345:21
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:104
   1: std::sys::windows::backtrace::set_frames
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:104
   2: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   4: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:211
   5: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:227
   6: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:475
   7: std::panicking::continue_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:390
   8: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:325
   9: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:77
  10: core::panicking::panic
             at C:\projects\rust\src\libcore\panicking.rs:52
  11: core::option::Option<(usize, stb_truetype::{{impl}}::glyph_shape_positive_contours::FlagData)*>::unwrap<(usize, stb_truetype::{{impl}}::glyph_shape_positive_contours::FlagData)*>
             at C:\projects\rust\src\libcore\macros.rs:20
  12: stb_truetype::FontInfo<rusttype::SharedBytes>::glyph_shape_positive_contours<rusttype::SharedBytes>
             at C:\Users\Martin\.cargo\registry\src\github.com-1ecc6299db9ec823\stb_truetype-0.2.4\src\lib.rs:911
  13: stb_truetype::FontInfo<rusttype::SharedBytes>::get_glyph_shape<rusttype::SharedBytes>
             at C:\Users\Martin\.cargo\registry\src\github.com-1ecc6299db9ec823\stb_truetype-0.2.4\src\lib.rs:655
  14: rusttype::PositionedGlyph::draw<closure>
             at C:\Users\Martin\.cargo\registry\src\github.com-1ecc6299db9ec823\rusttype-0.4.3\src\lib.rs:786
  15: font::rusttype::{{impl}}::get_glyph
             at .\font\src\rusttype\mod.rs:122
  16: alacritty::renderer::{{impl}}::get::{{closure}}<alacritty::renderer::RenderApi>
             at .\src\renderer\mod.rs:280
  17: std::collections::hash::map::Entry<font::GlyphKey, alacritty::renderer::Glyph>::or_insert_with<font::GlyphKey,alacritty::renderer::Glyph,closure>
             at C:\projects\rust\src\libstd\collections\hash\map.rs:2120
  18: alacritty::renderer::GlyphCache::get<alacritty::renderer::RenderApi>
             at .\src\renderer\mod.rs:277
  19: alacritty::renderer::RenderApi::render_cells<core::slice::Iter<alacritty::term::RenderableCell>>
             at .\src\renderer\mod.rs:896
  20: alacritty::display::{{impl}}::draw::{{closure}}
             at .\src\display.rs:380
  21: alacritty::renderer::QuadRenderer::with_api<closure,()>
             at .\src\renderer\mod.rs:689
  22: alacritty::display::Display::draw
             at .\src\display.rs:378
  23: alacritty::run
             at .\src\main.rs:261
  24: alacritty::main
             at .\src\main.rs:80
  25: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  26: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  27: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  28: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:105
  29: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  30: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  31: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  32: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  33: main
  34: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  35: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  36: BaseThreadInitThunk
  37: RtlUserThreadStart
```

**Comment by zacps** [comment]
It seems like there is a glyph, or we would have bailed on `src/font/rusttype/mod.rs#103`, but trying to draw it fails for some reason.

What font are you using?

**Comment by martin-sucha** [comment]
The font is the default (I don't have a config file). It happens to be `Consolas`, here is the font from config printed:
```
Font { normal: FontDescription { family: "Consolas", style: None }, italic: FontDescription { family: "Consolas", style: None }, bold: FontDescription { family: "Consolas", style: None }, size: Size(22), offset: Delta { x: 0, y: 0 }, glyph_offset: Delta { x: 0, y: 0 }, use_thin_strokes: false, scale_with_dpi: true }
```

The panic occurs for `get_glyph` of
```
GlyphKey { c: '\u{feff}', font_key: FontKey { token: 3 }, size: Size(22) }
```

so this confirms it's caused by the BOM.

**Comment by martin-sucha** [comment]
I've created an issue in `stb_truetype-rs` at https://gitlab.redox-os.org/redox-os/stb_truetype-rs/issues/19

**Comment by VladPoenaru** [comment]
The same thing happens when using `less` and `cat`, with files generated by Visual Studio (.csproj, nuget.config, etc)

**Comment by chrisduerr** [comment]
@jabagawee Thanks for the info. I've pushed a PR to bump the version here: https://github.com/jwilm/alacritty/pull/1904.

Testing appreciated!

**Comment by milhnl** [comment]
It works for me now. Thanks!
