### ISSUE TITLE
Decreasing font size too much causes division by zero

### ISSUE THREAD

**Issue by martin-sucha** [jwilm/alacritty#1693]
Which operating system does the issue occur on?
Windows. I have also tested on Linux/X11 and could not reproduce there.

Version of alacritty:
4380d0864b1098909bdcfec132b866c34924517e

How to reproduce:
1. Open alacritty
2. Press `Ctrl`+`-` to scale the font down until it disappears
3. Move mouse over the window
4. alacritty crashes with the following stack trace:

```
$ RUST_BACKTRACE=1 ./target/debug/alacritty.exe
thread 'main' panicked at 'attempt to divide by zero', src\term\mod.rs:810:26
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:104
   1: std::sys::windows::backtrace::set_frames
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:104
   2: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   4: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:211
   5: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:227
   6: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:475
   7: std::panicking::continue_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:390
   8: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:325
   9: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:77
  10: core::panicking::panic
             at C:\projects\rust\src\libcore\panicking.rs:52
  11: alacritty::term::SizeInfo::pixels_to_coords
             at .\src\term\mod.rs:810
  12: alacritty::input::Processor<alacritty::event::ActionContext<alacritty::event_loop::Notifier>>::mouse_moved<alacritty::event::ActionContext<alacritty::event_loop::Notifier>>
             at .\src\input.rs:327
  13: alacritty::event::Processor<alacritty::event_loop::Notifier>::handle_event<alacritty::event_loop::Notifier>
             at .\src\event.rs:358
  14: alacritty::event::{{impl}}::process_events::{{closure}}<alacritty::event_loop::Notifier>
             at .\src\event.rs:461
  15: alacritty::event::Processor<alacritty::event_loop::Notifier>::process_events<alacritty::event_loop::Notifier>
             at .\src\event.rs:472
  16: alacritty::run
             at .\src\main.rs:231
  17: alacritty::main
             at .\src\main.rs:80
  18: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  19: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  20: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  21: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:105
  22: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  23: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  24: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  25: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  26: main
  27: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  28: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  29: BaseThreadInitThunk
  30: RtlUserThreadStart
```

When I add a following check, it hits the newly added panic on hitting the last `Ctrl`+`-` to scale the font down:
```diff
diff --git a/src/display.rs b/src/display.rs
index d5a2ea0..1896e88 100644
--- a/src/display.rs
+++ b/src/display.rs
@@ -261,6 +261,11 @@ impl Display {
         let metrics = cache.font_metrics();
         self.size_info.cell_width = ((metrics.average_advance + f64::from(config.font().offset().x)) as f32).floor();
         self.size_info.cell_height = ((metrics.line_height + f64::from(config.font().offset().y)) as f32).floor();
+
+        // Prevent invalid cell sizes
+        if self.size_info.cell_width < 1. || self.size_info.cell_height < 1. {
+            panic!("font offset is too small");
+        }
     }
 
     #[inline]
```

**Comment by martin-sucha** [comment]
There is a check for font size in [change_font_size](https://github.com/jwilm/alacritty/blob/4380d0864b1098909bdcfec132b866c34924517e/src/term/mod.rs#L895) that ensures font size is `FONT_SIZE_STEP` (0.5) at minimum. However, I think that a check for font size is not sufficient, since the cell size depends on the font metrics (and so only indirectly on font size). So I think a proper fix would be to calculate the font metrics for new size first and only update the font size and glyph cache if the new cell dimensions are valid.
