### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by martinlindhe** [jwilm/alacritty#177]
I know that Windows target is not supported at the moment, but since it was a stated goal, here's the current status.

    rustc 1.15.0-nightly (8f02c429a 2016-12-15)

Build fails on servo-fontconfig-sys:

```
error: failed to run custom build command for `servo-fontconfig-sys v2.11.3 (https://github.com/jwilm/libfontconfig#618a5297)`
process didn't exit successfully: `C:\Users\name\dev\rs\alacritty\target\release\build\servo-fontconfig-sys-15a0b66e991dea2e\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "The system cannot find the file specified." } }', C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libcore\result.rs:837
stack backtrace:
   0:     0x7ff7e6d3a86a - std::panicking::default_hook::{{closure}}
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:354
   1:     0x7ff7e6d39d76 - std::panicking::default_hook
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:365
   2:     0x7ff7e6d3d66d - std::panicking::rust_panic_with_hook
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:553
   3:     0x7ff7e6d3d4b8 - std::panicking::begin_panic<collections::string::String>
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:515
   4:     0x7ff7e6d3d424 - std::panicking::begin_panic_fmt
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:499
   5:     0x7ff7e6d3d3b9 - std::panicking::rust_begin_panic
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:475
   6:     0x7ff7e6d40147 - core::panicking::panic_fmt
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libcore\panicking.rs:69
   7:     0x7ff7e6d2128f - core::result::unwrap_failed<std::io::error::Error>
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libcore\macros.rs:29
   8:     0x7ff7e6d21dd2 - build_script_build::main
                        at C:\Users\name\.cargo\git\checkouts\libfontconfig-3d5e920c02c2e53f\618a529\build.rs:25
   9:     0x7ff7e6d3fac1 - panic_unwind::__rust_maybe_catch_panic
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libpanic_unwind\lib.rs:98
  10:     0x7ff7e6d3dc5a - std::rt::lang_start
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libstd\rt.rs:51
  11:     0x7ff7e6d43a48 - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  12:     0x7ffedc668363 - BaseThreadInitThunk
```

**Comment by jwilm** [comment]
Thanks for looking into it!

Since this is linked from the Windows Support issue and Windows support is a ways out, I'm just going to close this.

**Comment by flaki** [comment]
FWIW I actually managed to build this on WSL (`Ubuntu 16.04.1 LTS`), fully updated (`sudo apt-get update && sudo apt-get upgrade`) yesterday evening.

I'm on Insider Slow Ring (build `rs_prerelease 14986`).
