### ISSUE TITLE
Panic when running micro text editor

### ISSUE THREAD

**Issue by spytheman** [jwilm/alacritty#184]
https://micro-editor.github.io

```
$ micro --version
Version: 1.1.4-55
Commit hash: a3c58e5
Compiled on January 02, 2017

$ RUST_BACKTRACE=1 target/release/alacritty 
device_pixel_ratio: 1
width: 1024, height: 768
Initializing glyph cache
num fonts = 916
num fonts = 916
num fonts = 916
Finished initializing glyph cache in 0.048065535
set_inner_size: 644px × 436px
width: 644, height: 436
Cell Size: (8 x 18)
PTY Dimensions: Line(24) x Column(80)
num_cols, num_lines = 128, 42
width: 1024, height: 768
num_cols, num_lines = 80, 24
width: 644, height: 436
[Unhandled CSI] action='h', args=[1003], intermediates=[63]
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
thread 'pty reader' panicked at 'index out of bounds: the len is 3 but the index is 4', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/slice.rs:640
stack backtrace:
   1:     0x558e45deea1a - std::sys::imp::backtrace::tracing::imp::write::h2b860f17b6b0f511
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x558e45df3d8f - std::panicking::default_hook::{{closure}}::hedea7d569eb1e6b8
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:349
   3:     0x558e45df398e - std::panicking::default_hook::he87e0c76c89c52a4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:365
   4:     0x558e45df4237 - std::panicking::rust_panic_with_hook::h304127bde2d3d5e2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:553
   5:     0x558e45df40c4 - std::panicking::begin_panic::h814f60faa3ce8314
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:515
   6:     0x558e45df3fe9 - std::panicking::begin_panic_fmt::hf4f7d700fa077693
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:499
   7:     0x558e45df3f77 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:475
   8:     0x558e45e2003d - core::panicking::panic_fmt::hee207ff21fb62166
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x558e45e1ffe8 - core::panicking::panic_bounds_check::hca28eae069525a56
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:56
  10:     0x558e45d0668d - alacritty::ansi::parse_color::hc430a62794d53a39
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/slice.rs:640
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/slice.rs:542
                        at /13/home/delian/Work/alacritty/src/ansi.rs:732
  11:     0x558e45ccee7c - vte::Parser::perform_action::he65c63b8394f4232
                        at /13/home/delian/Work/alacritty/src/ansi.rs:646
                        at /home/delian/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.1.2/src/lib.rs:205
  12:     0x558e45ce200a - <alacritty::event_loop::EventLoop<Io>>::spawn::{{closure}}::hea55e6f19d8f9463
                        at /home/delian/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.1.2/src/lib.rs:158
                        at /home/delian/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.1.2/src/lib.rs:137
                        at /13/home/delian/Work/alacritty/src/ansi.rs:85
                        at /13/home/delian/Work/alacritty/src/event_loop.rs:211
                        at /13/home/delian/Work/alacritty/src/event_loop.rs:308
  13:     0x558e45ccd70b - std::panicking::try::do_call::h6d19ebed5c41899d
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:295
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:458
  14:     0x558e45dfb17a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  15:     0x558e45cdfeca - <F as alloc::boxed::FnBox<A>>::call_box::hd8775355f3c9dc97
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:434
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/mod.rs:287
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:605
  16:     0x558e45df3084 - std::sys::imp::thread::Thread::new::thread_start::h460a0adc61139b06
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  17:     0x7ff2845a76b9 - start_thread
  18:     0x7ff2840c782c - clone
  19:                0x0 - <unknown>
child finished with error '1'


```

**Comment by spytheman** [comment]
Alacritty 0.1.0 (62eb1e2) does run micro without panics:


RUST_BACKTRACE=1 target/release/alacritty
num_cols, num_lines = 128, 42
num_cols, num_lines = 80, 24
[Unhandled CSI] action='h', args=[1003], intermediates=[63]
[Unhandled CSI] action='l', args=[1003], intermediates=[63]
