### ISSUE TITLE
Panic when running doge command

### ISSUE THREAD

**Issue by Gonzih** [jwilm/alacritty#199]
Just after i compiled and tried terminal for the first time it panicked. I have `doge` (https://github.com/thiderman/doge) in my fish shell startup and it causes the crash. Crash happens when the face of the dog is being rendered. Looks like it might be related to the color or character used for the ASCII graphics.

Full output with backtrace:
```
device_pixel_ratio: 1
width: 1920, height: 1169
Initializing glyph cache
num fonts = 165
num fonts = 165
num fonts = 165
Finished initializing glyph cache in 0.014723604
set_inner_size: 644px × 436px
width: 644, height: 436
Cell Size: (8 x 18)
PTY Dimensions: Line(24) x Column(80)
num_cols, num_lines = 240, 64
width: 1920, height: 1169
[unhandled osc_start]
[unhandled osc_put] byte='0'
[unhandled osc_put] byte=';'
[unhandled osc_put] byte='f'
[unhandled osc_put] byte='i'
[unhandled osc_put] byte='s'
[unhandled osc_put] byte='h'
[unhandled osc_put] byte=' '
[unhandled osc_put] byte=' '
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='h'
[unhandled osc_put] byte='o'
[unhandled osc_put] byte='m'
[unhandled osc_put] byte='e'
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='g'
[unhandled osc_put] byte='n'
[unhandled osc_put] byte='z'
[unhandled osc_put] byte='h'
[unhandled osc_end] byte=0
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
[Unhandled CSI] action='q', args=[1], intermediates=[32]
[Unhandled CSI] action='q', args=[1], intermediates=[32]
[Unhandled CSI] action='q', args=[1], intermediates=[32]
[unhandled osc_start]
[unhandled osc_put] byte='7'
[unhandled osc_put] byte=';'
[unhandled osc_put] byte='f'
[unhandled osc_put] byte='i'
[unhandled osc_put] byte='l'
[unhandled osc_put] byte='e'
[unhandled osc_put] byte=':'
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='m'
[unhandled osc_put] byte='a'
[unhandled osc_put] byte='x'
[unhandled osc_put] byte='b'
[unhandled osc_put] byte='o'
[unhandled osc_put] byte='o'
[unhandled osc_put] byte='k'
[unhandled osc_put] byte='-'
[unhandled osc_put] byte='p'
[unhandled osc_put] byte='r'
[unhandled osc_put] byte='o'
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='h'
[unhandled osc_put] byte='o'
[unhandled osc_put] byte='m'
[unhandled osc_put] byte='e'
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='g'
[unhandled osc_put] byte='n'
[unhandled osc_put] byte='z'
[unhandled osc_put] byte='h'
[unhandled osc_end] byte=0
[unhandled osc_start]
[unhandled osc_put] byte='0'
[unhandled osc_put] byte=';'
[unhandled osc_put] byte='f'
[unhandled osc_put] byte='i'
[unhandled osc_put] byte='s'
[unhandled osc_put] byte='h'
[unhandled osc_put] byte=' '
[unhandled osc_put] byte=' '
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='h'
[unhandled osc_put] byte='o'
[unhandled osc_put] byte='m'
[unhandled osc_put] byte='e'
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='g'
[unhandled osc_put] byte='n'
[unhandled osc_put] byte='z'
[unhandled osc_put] byte='h'
[unhandled osc_end] byte=0
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
[Unhandled CSI] action='q', args=[1], intermediates=[32]
[unhandled osc_start]
[unhandled osc_put] byte='0'
[unhandled osc_put] byte=';'
[unhandled osc_put] byte='d'
[unhandled osc_put] byte='o'
[unhandled osc_put] byte='g'
[unhandled osc_put] byte='e'
[unhandled osc_put] byte=' '
[unhandled osc_put] byte=' '
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='h'
[unhandled osc_put] byte='o'
[unhandled osc_put] byte='m'
[unhandled osc_put] byte='e'
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='g'
[unhandled osc_put] byte='n'
[unhandled osc_put] byte='z'
[unhandled osc_put] byte='h'
[unhandled osc_end] byte=0
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
Unexpected color attr: 172
thread 'pty reader' panicked at 'index out of bounds: the len is 3 but the index is 4', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/slice.rs:644
stack backtrace:
   1:     0x55bdf2c1e41c - std::sys::imp::backtrace::tracing::imp::write::h2a972e172776bc73
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55bdf2c2376e - std::panicking::default_hook::{{closure}}::h3350be9abe4c8496
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x55bdf2c23374 - std::panicking::default_hook::h255964940ef72e84
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x55bdf2c23c17 - std::panicking::rust_panic_with_hook::ha02a85ff57cdb669
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x55bdf2c23a54 - std::panicking::begin_panic::h3472a76248a19370
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x55bdf2c239c9 - std::panicking::begin_panic_fmt::h353221386e3766a5
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x55bdf2c23957 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x55bdf2c4fa3d - core::panicking::panic_fmt::h2a5bed77fd55efc9
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x55bdf2c4f9e8 - core::panicking::panic_bounds_check::h9cc2800ddc8a467d
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:56
  10:     0x55bdf2b375cd - alacritty::ansi::parse_color::h4866de22b677e43e
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/slice.rs:644
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/slice.rs:546
                        at /home/gnzh/mydev/alacritty/src/ansi.rs:732
  11:     0x55bdf2b009b8 - vte::Parser::perform_action::hf1320867736df0df
                        at /home/gnzh/mydev/alacritty/src/ansi.rs:630
                        at /home/gnzh/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.1.2/src/lib.rs:205
  12:     0x55bdf2b13129 - <alacritty::event_loop::EventLoop<Io>>::spawn::{{closure}}::h01f2d3e2971fa2ce
                        at /home/gnzh/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.1.2/src/lib.rs:158
                        at /home/gnzh/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.1.2/src/lib.rs:137
                        at /home/gnzh/mydev/alacritty/src/ansi.rs:85
                        at /home/gnzh/mydev/alacritty/src/event_loop.rs:211
                        at /home/gnzh/mydev/alacritty/src/event_loop.rs:308
  13:     0x55bdf2aff2ab - std::panicking::try::do_call::h1b3a9ca1e5d9038c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:296
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:460
  14:     0x55bdf2c2ab7a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  15:     0x55bdf2b1109a - <F as alloc::boxed::FnBox<A>>::call_box::h6335d48d53dc84d2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/mod.rs:302
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:605
  16:     0x55bdf2c22a64 - std::sys::imp::thread::Thread::new::thread_start::h27fa49fe81f658e4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  17:     0x7f6c6293f453 - start_thread
  18:     0x7f6c6246b7de - __GI___clone
  19:                0x0 - <unknown>
Goodbye
```

**Comment by jwilm** [comment]
Likely resolved.
