### ISSUE TITLE
alacritty fails to exit cleanly when shell is exited

### ISSUE THREAD

**Issue by rrichardson** [jwilm/alacritty#201]
when exiting via ctrl-d or exit,  the window hangs.. the pstack of the hanging threads is :

pstack : 
```
Thread 3 (Thread 0x7f75895ff700 (LWP 32051)):
#0  0x00007f759325d573 in epoll_wait () from /lib64/libc.so.6
#1  0x000055a6e708c61c in nix::sys::epoll::epoll_wait (epfd=<optimized out>, events=..., timeout_ms=<optimized out>) at /home/rick/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.5.1/src/sys/epoll.rs:91
#2  mio::sys::unix::epoll::Selector::select (self=<optimized out>, evts=<optimized out>, timeout_ms=...) at /home/rick/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.5.1/src/sys/unix/epoll.rs:52
#3  mio::poll::Poll::poll (self=0x7f75895fe788, timeout_ms=...) at /home/rick/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.5.1/src/poll.rs:52
#4  0x000055a6e707a3d8 in mio::event_loop::EventLoop<notify::inotify::INotifyHandler>::io_poll<notify::inotify::INotifyHandler> (timeout=..., self=<optimized out>) at /home/rick/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.5.1/src/event_loop.rs:317
#5  mio::event_loop::EventLoop<notify::inotify::INotifyHandler>::run_once<notify::inotify::INotifyHandler> (timeout_ms=..., self=<optimized out>, handler=<optimized out>) at /home/rick/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.5.1/src/event_loop.rs:279
#6  mio::event_loop::EventLoop<notify::inotify::INotifyHandler>::run<notify::inotify::INotifyHandler> (handler=<optimized out>, self=<optimized out>) at /home/rick/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.5.1/src/event_loop.rs:247
#7  notify::inotify::{{impl}}::new::{{closure}}::{{closure}} () at /home/rick/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-2.6.3/src/inotify/mod.rs:243
#8  std::panic::{{impl}}::call_once<core::result::Result<(), std::io::error::Error>,closure> (self=..., _args=<optimized out>) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:296
#9  std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,core::result::Result<(), std::io::error::Error>> (data=0x7f75895fea20 "\001\024\000") at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:460
#10 0x000055a6e7105c4b in panic_unwind::__rust_maybe_catch_panic () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
#11 0x000055a6e708054b in std::panicking::try<core::result::Result<(), std::io::error::Error>,std::panic::AssertUnwindSafe<closure>> (f=...) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
#12 std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,core::result::Result<(), std::io::error::Error>> (f=...) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
#13 std::thread::{{impl}}::spawn::{{closure}}<closure,core::result::Result<(), std::io::error::Error>> () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/mod.rs:357
#14 alloc::boxed::{{impl}}::call_box<(),closure> (self=0x7f7589890000, args=<optimized out>) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:605
#15 0x000055a6e70fdb25 in alloc::boxed::{{impl}}::call_once<(),()> () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
#16 std::sys_common::thread::start_thread () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
#17 std::sys::imp::thread::{{impl}}::new::thread_start () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
#18 0x00007f75937396ca in start_thread () from /lib64/libpthread.so.0
#19 0x00007f759325cf7f in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7f7589ee1700 (LWP 32049)):
#0  0x00007f759373f460 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000055a6e70ef059 in std::sys::imp::condvar::Condvar::wait () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/condvar.rs:64
#2  std::sys_common::condvar::Condvar::wait () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/condvar.rs:51
#3  std::sync::condvar::Condvar::wait<bool> () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sync/condvar.rs:126
#4  std::thread::park () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/mod.rs:571
#5  0x000055a6e70f6660 in std::sync::mpsc::blocking::WaitToken::wait () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sync/mpsc/blocking.rs:81
#6  0x000055a6e6ff7e0f in std::sync::mpsc::oneshot::Packet<notify::Event>::recv<notify::Event> (deadline=..., self=<optimized out>) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sync/mpsc/oneshot.rs:163
#7  std::sync::mpsc::Receiver<notify::Event>::recv<notify::Event> (self=<optimized out>) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sync/mpsc/mod.rs:875
#8  alacritty::config::{{impl}}::new::{{closure}}<alacritty::display::Notifier,&std::path::Path> () at /home/rick/Projects/alacritty/src/config.rs:1140
#9  0x000055a6e6fdb2f8 in std::panic::{{impl}}::call_once<(),closure> (self=..., _args=<optimized out>) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:296
#10 std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()> (data=<optimized out>) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:460
#11 0x000055a6e7105c4b in panic_unwind::__rust_maybe_catch_panic () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
#12 0x000055a6e6fed12a in std::panicking::try<(),std::panic::AssertUnwindSafe<closure>> (f=...) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
#13 std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()> (f=...) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
#14 std::thread::{{impl}}::spawn::{{closure}}<closure,()> () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/mod.rs:357
#15 alloc::boxed::{{impl}}::call_box<(),closure> (self=0x7f758bdfde80, args=<optimized out>) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:605
#16 0x000055a6e70fdb25 in alloc::boxed::{{impl}}::call_once<(),()> () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
#17 std::sys_common::thread::start_thread () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
#18 std::sys::imp::thread::{{impl}}::new::thread_start () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
#19 0x00007f75937396ca in start_thread () from /lib64/libpthread.so.0
#20 0x00007f759325cf7f in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7f7594653d00 (LWP 32047)):
#0  0x00007f759373f460 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f7591aa4f87 in _xcb_conn_wait () from /lib64/libxcb.so.1
#2  0x00007f7591aa67cf in wait_for_reply () from /lib64/libxcb.so.1
#3  0x00007f7591aa6941 in xcb_wait_for_reply64 () from /lib64/libxcb.so.1
#4  0x00007f7591d02bd8 in _XReply () from /lib64/libX11.so.6
#5  0x00007f758ffdf9c8 in ?? () from /lib64/libGLX_nvidia.so.0
#6  0x00007f758ffe02a5 in ?? () from /lib64/libGLX_nvidia.so.0
#7  0x00007f758ffe3ab9 in ?? () from /lib64/libGLX_nvidia.so.0
#8  0x00007f7590054234 in ?? () from /lib64/libGLX_nvidia.so.0
#9  0x00007f759445f1a8 in _dl_fini () from /lib64/ld-linux-x86-64.so.2
#10 0x00007f759318f410 in __run_exit_handlers () from /lib64/libc.so.6
#11 0x00007f759318f46a in exit () from /lib64/libc.so.6
#12 0x000055a6e70f6514 in std::sys::imp::os::exit () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/os.rs:526
#13 std::process::exit () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/process.rs:897
#14 0x000055a6e7026a2d in alacritty::tty::sigchld (_a=<optimized out>) at /home/rick/Projects/alacritty/src/tty.rs:55
#15 <signal handler called>
#16 0x00007f759325101d in poll () from /lib64/libc.so.6
#17 0x00007f7591aa4d10 in _xcb_conn_wait () from /lib64/libxcb.so.1
#18 0x00007f7591aa6aa9 in xcb_wait_for_event () from /lib64/libxcb.so.1
#19 0x00007f7591d028a8 in _XReadEvents () from /lib64/libX11.so.6
#20 0x00007f7591cf4180 in XPeekEvent () from /lib64/libX11.so.6
#21 0x000055a6e70a6c9a in glutin::api::x11::window::{{impl}}::next (self=0x7ffc6ef98730) at /home/rick/.cargo/git/checkouts/glutin-2b5ecc80feb2e4c5/af7fe34/src/api/x11/window.rs:297
#22 0x000055a6e6ffd993 in glutin::platform::platform::api_dispatch::{{impl}}::next (self=<optimized out>) at /home/rick/.cargo/git/checkouts/glutin-2b5ecc80feb2e4c5/af7fe34/src/platform/linux/api_dispatch.rs:169
#23 glutin::window::{{impl}}::next (self=<optimized out>) at /home/rick/.cargo/git/checkouts/glutin-2b5ecc80feb2e4c5/af7fe34/src/window.rs:584
#24 alacritty::event::Processor<alacritty::event_loop::Notifier>::process_events<alacritty::event_loop::Notifier> (term=<optimized out>, self=<optimized out>, window=<optimized out>) at /home/rick/Projects/alacritty/src/event.rs:196
#25 alacritty::run (config=..., options=...) at /home/rick/Projects/alacritty/src/main.rs:139
#26 0x000055a6e6ffbc80 in alacritty::main () at /home/rick/Projects/alacritty/src/main.rs:59
#27 0x000055a6e7105c4b in panic_unwind::__rust_maybe_catch_panic () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
#28 0x000055a6e70ff437 in std::panicking::try<(),fn()> () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
#29 std::panic::catch_unwind<fn(),()> () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
#30 std::rt::lang_start () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/rt.rs:57
#31 0x00007f7593175401 in __libc_start_main () from /lib64/libc.so.6
#32 0x000055a6e6fd583a in _start ()
```

**Comment by rrichardson** [comment]
referencing #119

**Comment by jwilm** [comment]
That was fast, thanks! For the record, this was on Fedora 25, right?

**Comment by rrichardson** [comment]
yep.

**Comment by rrichardson** [comment]
I have verified that the latest master fixes this on F25.

**Comment by jwilm** [comment]
:+1: thanks for following up!

**Comment by wintermute101** [comment]
I have exactly the same issue on latest master 715d4f8be8b80604a0b6a8464e55a60660f810a0.
Sabayon + awesome. Nvidia drivers.

**Comment by wintermute101** [comment]
I use fish and when I start directly fish I can not reproduce this. When I start fish from bashrc and then I close terminal by ctrl+d bash sometimes lags (it's not instant) close. Maybe some race when bash takes more time to close?

**Comment by jwilm** [comment]
Is this still an issue?
