### ISSUE TITLE
`C-c` panic in fish shell

### ISSUE THREAD

**Issue by quininer** [jwilm/alacritty#25]
Reproducing step:

0. open `alacritty` and `fish`
1. `a`
2. `C-c`

log:

```[I] ➜  alacritty git:(master) ✗ cargo run
    Finished debug [unoptimized + debuginfo] target(s) in 0.1 secs
     Running `target/debug/alacritty`
device_pixel_ratio: 1
width: 1024, height: 768
Initializing glyph cache
Finished initializing glyph cache in 0.124546754
set_inner_size: 804 x 604
set_inner_size: 804 x 604; pts: 804 x 604
width: 804, height: 604
Cell Size: (10 x 25)
num_cols, num_lines = Column(80), Line(24)
num_cols, num_lines = Column(102), Line(30)
width: 1024, height: 768
num_cols, num_lines = Column(80), Line(24)
width: 804, height: 604
[unhandled osc_start]
[unhandled osc_put] byte='5'
[unhandled osc_put] byte='0'
[unhandled osc_put] byte=';'
[unhandled osc_put] byte='C'
[unhandled osc_put] byte='u'
[unhandled osc_put] byte='r'
[unhandled osc_put] byte='s'
[unhandled osc_put] byte='o'
[unhandled osc_put] byte='r'
[unhandled osc_put] byte='S'
[unhandled osc_put] byte='h'
[unhandled osc_put] byte='a'
[unhandled osc_put] byte='p'
[unhandled osc_put] byte='e'
[unhandled osc_put] byte='='
[unhandled osc_put] byte='0'
[unhandled osc_end] byte=0
[unhandled osc_start]
[unhandled osc_put] byte='0'
[unhandled osc_put] byte=';'
[unhandled osc_put] byte='f'
[unhandled osc_put] byte='i'
[unhandled osc_put] byte='s'
[unhandled osc_put] byte='h'
[unhandled osc_put] byte=' '
[unhandled osc_put] byte=' '
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='h'
[unhandled osc_put] byte='o'
[unhandled osc_put] byte='m'
[unhandled osc_put] byte='e'
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='q'
[unhandled osc_put] byte='u'
[unhandled osc_put] byte='i'
[unhandled osc_put] byte='n'
[unhandled osc_put] byte='i'
[unhandled osc_put] byte='n'
[unhandled osc_put] byte='e'
[unhandled osc_put] byte='r'
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='t'
[unhandled osc_put] byte='e'
[unhandled osc_put] byte='s'
[unhandled osc_put] byte='t'
[unhandled osc_put] byte='s'
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='u'
[unhandled osc_put] byte='i'
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='a'
[unhandled osc_put] byte='l'
[unhandled osc_put] byte='a'
[unhandled osc_put] byte='c'
[unhandled osc_put] byte='r'
[unhandled osc_put] byte='i'
[unhandled osc_put] byte='t'
[unhandled osc_put] byte='t'
[unhandled osc_put] byte='y'
[unhandled osc_end] byte=0
Set Attribute: Foreground(Black)
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
Set Attribute: Reset
carriage_return
linefeed
Set Attribute: Foreground(Green)
Set Attribute: Foreground(Black)
Set Attribute: Reset
[Unhandled CSI] action='m', args=[0, 10], intermediates=[]
carriage_return
linefeed
[unhandled osc_start]
[unhandled osc_put] byte='5'
[unhandled osc_put] byte='0'
[unhandled osc_put] byte=';'
[unhandled osc_put] byte='C'
[unhandled osc_put] byte='u'
[unhandled osc_put] byte='r'
[unhandled osc_put] byte='s'
[unhandled osc_put] byte='o'
[unhandled osc_put] byte='r'
[unhandled osc_put] byte='S'
[unhandled osc_put] byte='h'
[unhandled osc_put] byte='a'
[unhandled osc_put] byte='p'
[unhandled osc_put] byte='e'
[unhandled osc_put] byte='='
[unhandled osc_put] byte='0'
[unhandled osc_end] byte=0
[unhandled osc_start]
[unhandled osc_put] byte='5'
[unhandled osc_put] byte='0'
[unhandled osc_put] byte=';'
[unhandled osc_put] byte='C'
[unhandled osc_put] byte='u'
[unhandled osc_put] byte='r'
[unhandled osc_put] byte='s'
[unhandled osc_put] byte='o'
[unhandled osc_put] byte='r'
[unhandled osc_put] byte='S'
[unhandled osc_put] byte='h'
[unhandled osc_put] byte='a'
[unhandled osc_put] byte='p'
[unhandled osc_put] byte='e'
[unhandled osc_put] byte='='
[unhandled osc_put] byte='0'
[unhandled osc_end] byte=0
[unhandled osc_start]
[unhandled osc_put] byte='0'
[unhandled osc_put] byte=';'
[unhandled osc_put] byte='f'
[unhandled osc_put] byte='i'
[unhandled osc_put] byte='s'
[unhandled osc_put] byte='h'
[unhandled osc_put] byte=' '
[unhandled osc_put] byte=' '
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='h'
[unhandled osc_put] byte='o'
[unhandled osc_put] byte='m'
[unhandled osc_put] byte='e'
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='q'
[unhandled osc_put] byte='u'
[unhandled osc_put] byte='i'
[unhandled osc_put] byte='n'
[unhandled osc_put] byte='i'
[unhandled osc_put] byte='n'
[unhandled osc_put] byte='e'
[unhandled osc_put] byte='r'
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='t'
[unhandled osc_put] byte='e'
[unhandled osc_put] byte='s'
[unhandled osc_put] byte='t'
[unhandled osc_put] byte='s'
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='u'
[unhandled osc_put] byte='i'
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='a'
[unhandled osc_put] byte='l'
[unhandled osc_put] byte='a'
[unhandled osc_put] byte='c'
[unhandled osc_put] byte='r'
[unhandled osc_put] byte='i'
[unhandled osc_put] byte='t'
[unhandled osc_put] byte='t'
[unhandled osc_put] byte='y'
[unhandled osc_end] byte=0
Set Attribute: Foreground(Black)
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
Set Attribute: Reset
Set Attribute: Dim
Term got unhandled attr: Dim
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
Set Attribute: Reset
carriage_return
carriage_return
clear_line: All
Set Attribute: Bold
Set Attribute: Foreground(White)
Set Attribute: Background(Green)
Set Attribute: Foreground(Black)
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
Set Attribute: Reset
Set Attribute: Bold
Set Attribute: Foreground(Green)
Set Attribute: Bold
Set Attribute: Foreground(Cyan)
Set Attribute: Bold
Set Attribute: Foreground(Blue)
Set Attribute: Bold
Set Attribute: Foreground(Red)
Set Attribute: Bold
Set Attribute: Foreground(Blue)
Set Attribute: Bold
Set Attribute: Foreground(Yellow)
Set Attribute: Foreground(Black)
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
Set Attribute: Reset
clear_line: Right
backspace
Set Attribute: Foreground(Red)
Set Attribute: Bold
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
Set Attribute: Reset
Set Attribute: ForegroundSpec(Rgb { r: 85, g: 85, b: 85 })
move_backward: Column(9)
Set Attribute: Foreground(Black)
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
Set Attribute: Reset
Set Attribute: Reverse
Set Attribute: CancelReverse
clear_line: Right
carriage_return
linefeed
backspace
thread 'pty reader' panicked at 'attempt to subtract with overflow', src/index.rs:251
stack backtrace:
   1:     0x563ad40383aa - std::sys::imp::backtrace::tracing::imp::write::hbea47d9dd19b523c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x563ad403d9af - std::panicking::default_hook::{{closure}}::h6875a2976258b020
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:247
   3:     0x563ad403d5ae - std::panicking::default_hook::h88ffbc5922643264
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:263
   4:     0x563ad403de57 - std::panicking::rust_panic_with_hook::hc790e47d4ecc86cd
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:451
   5:     0x563ad403dce4 - std::panicking::begin_panic::hc066339e2fdc17d1
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:413
   6:     0x563ad403dc09 - std::panicking::begin_panic_fmt::h5912b2d2df332044
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:397
   7:     0x563ad403db97 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:373
   8:     0x563ad407a53d - core::panicking::panic_fmt::h561c5ee168a3d2cb
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/panicking.rs:69
   9:     0x563ad407a474 - core::panicking::panic::h194ce5d68a8f28a1
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/panicking.rs:49
  10:     0x563ad3cd1c36 - <alacritty::index::Column as core::ops::SubAssign<usize>>::sub_assign::h0d91353cd4e41af1
                        at /home/quininer/tests/ui/alacritty/src/index.rs:251
  11:     0x563ad3cbee0a - <alacritty::term::Term as alacritty::ansi::Handler>::backspace::h0f69366576cc537e
                        at /home/quininer/tests/ui/alacritty/src/term.rs:573
  12:     0x563ad3cd7322 - <alacritty::ansi::Performer<'a, H> as vte::Perform>::execute::h13c990c23c2f5e84
                        at /home/quininer/tests/ui/alacritty/src/ansi.rs:403
  13:     0x563ad3c5d2d8 - vte::Parser::perform_action::h8e9207d2609e34af
                        at /home/quininer/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.1.2/src/lib.rs:190
  14:     0x563ad3c5d8fe - vte::Parser::perform_state_change::h9a56f079e43e56e3
                        at /home/quininer/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.1.2/src/lib.rs:167
  15:     0x563ad3c5dc74 - vte::Parser::advance::he199b620df8be155
                        at /home/quininer/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.1.2/src/lib.rs:137
  16:     0x563ad3d14bcc - alacritty::ansi::Processor::advance::hef377be56860e454
                        at /home/quininer/tests/ui/alacritty/src/ansi.rs:81
  17:     0x563ad3cac8fe - <alacritty::event_loop::EventLoop<Io>>::pty_read::h1fd65b9f29f2a13b
                        at /home/quininer/tests/ui/alacritty/src/event_loop.rs:192
  18:     0x563ad3cac098 - <alacritty::event_loop::EventLoop<Io>>::spawn::{{closure}}::h0bb425cd2fe8582f
                        at /home/quininer/tests/ui/alacritty/src/event_loop.rs:281
  19:     0x563ad3cdf804 - <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once::heccf5411cd66eb39
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:295
  20:     0x563ad3c5cf7f - std::panicking::try::do_call::h546e5663bd72af75
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:356
  21:     0x563ad40468ba - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  22:     0x563ad3c5c7db - std::panicking::try::h2364aec27ae8e5f6
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
  23:     0x563ad3c5a9e4 - std::panic::catch_unwind::ha436adb5d97f012c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
  24:     0x563ad3c5c34c - std::thread::Builder::spawn::{{closure}}::h9d2c7b9b28783ee1
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/thread/mod.rs:287
  25:     0x563ad3ca46e9 - <F as alloc::boxed::FnBox<A>>::call_box::hbd32ccd14fb32e99
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/boxed.rs:595
  26:     0x563ad403cca4 - std::sys::imp::thread::Thread::new::thread_start::h8084b1107992ae5b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/boxed.rs:605
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/unix/thread.rs:84
  27:     0x7fc80624e453 - start_thread
  28:     0x7fc805d7a7de - __GI___clone
  29:                0x0 - <unknown>
Goodbye
```

**Comment by jwilm** [comment]
I just pushed b6c372ab4800b8dbc9e3efb042e369c9980c607a which should fix this problem. Please let me know how it goes!

**Comment by quininer** [comment]
it work! :)

**Comment by quininer** [comment]
Probably panic at release build, I can't reproduce it stably.

```
thread 'pty reader' panicked at 'slice index starts at 18446744073709551597 but ends at 216', ../src/libcore/slice.rs:566
```

**Comment by jwilm** [comment]
This should be a similarly simple fix, but I won't be able to get to it until tonight. Thanks for filing these reports!

**Comment by jwilm** [comment]
I think the patch on master should fix this.

Would you mind contributing a ref test for this behavior? The ref tests help prevent regressions. No worries if not, but they're really easy to record if you can spare a few minutes. Instructions:

Start alacritty with

```sh
target/release/alacritty --ref-test
```

and do something in the terminal (just don't resize it). In this case, it's the two sequences that you experienced a crash with. After performing those actions, close alacritty by hitting the window close X button. There should be some files in your alacritty folder now: `alacritty.recording`, `grid.json`, and `size.json`. Upload those here or commit them to a folder in `tests/ref` and add the folder name to the list at the end of `tests/ref.rs`.
