### ISSUE TITLE
Closing alacritty with `Ctrl+D` when recording `ref-test` can result in panic on Wayland

### ISSUE THREAD

**Issue by kchibisov** [jwilm/alacritty#2625]
Linux, Wayland.

if you run `alacritty --ref-test`, press `Ctrl+D` and then press some other key, `alacritty` will panic.
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: EventsLoopClosed', src/libcore/result.rs:999:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::unwrap
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/result.rs:800
  10: winit::platform::platform::wayland::keyboard::init_keyboard::{{closure}}
             at /home/kchibisov/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.1/src/platform/linux/wayland/keyboard.rs:111
  11: smithay_client_toolkit::keyboard::implement_kbd::{{closure}}::{{closure}}::{{closure}}
             at /home/kchibisov/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-client-toolkit-0.4.6/src/keyboard/mod.rs:720
``` 

Closing with system `shortcut` is always fine.
Closing with `Ctrl+D` and not pressing any key is fine though.

**Comment by chrisduerr** [comment]
This is likely a winit/glutin issue, however before reporting it upstream it might be worthwhile to first create a minimal example for reproducing it and then checking out if this issue still exists on the event loop 2 rework.

The ref test saving could likely be simulated by just blocking for a few seconds, so the following diff might be enough to reproduce. Note that this change is based on the v0.21.0 git tag of glutin.

```diff
diff --git a/glutin/src/lib.rs b/glutin/src/lib.rs
index 33b0b93..5f83b78 100644
--- a/glutin/src/lib.rs
+++ b/glutin/src/lib.rs
@@ -323,7 +323,7 @@ impl<'a, T: ContextCurrentState> ContextBuilder<'a, T> {
 pub enum CreationError {
     OsError(String),
     NotSupported(String),
-    NoBackendAvailable(Box<std::error::Error + Send + Sync>),
+    NoBackendAvailable(Box<dyn std::error::Error + Send + Sync>),
     RobustnessNotSupported,
     OpenGlVersionNotSupported,
     NoAvailablePixelFormat,
@@ -403,7 +403,7 @@ impl std::error::Error for CreationError {
         self.to_string()
     }
 
-    fn cause(&self) -> Option<&std::error::Error> {
+    fn cause(&self) -> Option<&dyn std::error::Error> {
         match *self {
             CreationError::NoBackendAvailable(ref err) => Some(&**err),
             CreationError::Window(ref err) => Some(err),
diff --git a/glutin_examples/examples/window.rs b/glutin_examples/examples/window.rs
index 6e23485..66dc568 100644
--- a/glutin_examples/examples/window.rs
+++ b/glutin_examples/examples/window.rs
@@ -17,26 +17,33 @@ fn main() {
 
     let gl = support::load(&windowed_context.context());
 
-    let mut running = true;
-    while running {
+    loop {
+        let mut b = false;
         el.poll_events(|event| {
             println!("{:?}", event);
             match event {
                 glutin::Event::WindowEvent { event, .. } => match event {
-                    glutin::WindowEvent::CloseRequested => running = false,
+                    // glutin::WindowEvent::CloseRequested => running = false,
                     glutin::WindowEvent::Resized(logical_size) => {
                         let dpi_factor =
                             windowed_context.window().get_hidpi_factor();
                         windowed_context
                             .resize(logical_size.to_physical(dpi_factor));
-                    }
+                    },
+                    glutin::WindowEvent::KeyboardInput { input, .. } if input.virtual_keycode == Some(glutin::VirtualKeyCode::D) => {
+                        b = true;
+                    },
                     _ => (),
                 },
                 _ => (),
             }
         });
 
+        if b { break; }
+
         gl.draw_frame([1.0, 0.5, 0.7, 1.0]);
         windowed_context.swap_buffers().unwrap();
     }
+
+    std::thread::sleep_ms(3000);
 }
```

If that doesn't do it, it might be worth trying to simplify Alacritty a bit and just moving/deleting stuff until a minimal repro case can be found.

**Comment by kchibisov** [comment]
I was able to reproduce the issue with the patch you've provided on `glutin` `v0.21.0`. But wasn't able with `evlp2`. Here this the patch I was using.
```diff
diff --git a/glutin_examples/examples/window.rs b/glutin_examples/examples/window.rs
index f7da6c4..c97c891 100644
--- a/glutin_examples/examples/window.rs
+++ b/glutin_examples/examples/window.rs
@@ -1,12 +1,12 @@
 mod support;
-
-use glutin::event::{Event, WindowEvent};
+use glutin::platform::desktop::EventLoopExtDesktop;
+use glutin::event::{Event, WindowEvent, VirtualKeyCode};
 use glutin::event_loop::{ControlFlow, EventLoop};
 use glutin::window::WindowBuilder;
 use glutin::ContextBuilder;

 fn main() {
-    let el = EventLoop::new();
+    let mut el = EventLoop::new();
     let wb = WindowBuilder::new().with_title("A fantastic window!");

     let windowed_context =
@@ -21,7 +21,7 @@ fn main() {

     let gl = support::load(&windowed_context.context());

-    el.run(move |event, _, control_flow| {
+    el.run_return(|event, el, control_flow| {
         println!("{:?}", event);
         *control_flow = ControlFlow::Wait;

@@ -41,9 +41,14 @@ fn main() {
                 WindowEvent::CloseRequested => {
                     *control_flow = ControlFlow::Exit
                 }
+                WindowEvent::KeyboardInput { input, .. } if input.virtual_keycode  == Some(VirtualKeyCode::D) => {
+                    *control_flow = ControlFlow::Exit;
+                }
                 _ => (),
             },
             _ => (),
         }
     });
+
+    std::thread::sleep_ms(3000);
 }
```
Let me know if there are issues with my patch.

**Comment by chrisduerr** [comment]
Sounds like it's fixed in the latest glutin master then. I'll add this to the issues closed by the evlp2 PR, thanks for testing.
