### ISSUE TITLE
Unable to launch when a virtual display is connected: 'assertion failed: validate_hidpi_factor(dpi_factor)'

### ISSUE THREAD

**Issue by Zer0897** [jwilm/alacritty#2694]
Arch 5.2.4 and X11.

```sh
[11:17] zer0 $ alacritty
thread 'main' panicked at 'assertion failed: validate_hidpi_factor(dpi_factor)', /build/.cargo/git/checkouts/winit-081229dbb0c89e9b/57680d2/src/platform/linux/x11/util/randr.rs:36:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I am using `intel-virtual-output` for my virtual display.

[here](https://gist.github.com/Zer0897/4ac7d084fd9c924ad76f445ca3cd643d) is the output of `xrandr`.

Let me know if you need anything else.

**Comment by chrisduerr** [comment]
I'd assume when you clone https://github.com/rust-windowing/winit and then run `cargo run --example window`, you get the same crash?

**Comment by Zer0897** [comment]
Everything seems to work fine with `winit`
```
[11:42] zer0:winit (master) $ cargo run --example window
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/examples/window`
NewEvents(Init)
EventsCleared
NewEvents(WaitCancelled { start: Instant { tv_sec: 2492, tv_nsec: 564817985 }, requested_resume: None })
WindowEvent { window_id: WindowId(X(WindowId(54525953))), event: Resized(LogicalSize { width: 1186.0, height: 1038.0 }) }
WindowEvent { window_id: WindowId(X(WindowId(54525953))), event: RedrawRequested }
WindowEvent { window_id: WindowId(X(WindowId(54525953))), event: Focused(true) }
...
```

**Comment by kchibisov** [comment]
@Zer0897 Could you test #2438 ?

**Comment by Zer0897** [comment]
No luck with #2438 
```sh
[11:53] zer0:alacritty (master) $ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/alacritty`
thread 'main' panicked at 'assertion failed: validate_hidpi_factor(dpi_factor)', /home/zer0/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.1/src/platform/linux/x11/util/randr.rs:36:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by Zer0897** [comment]
`winit v0.10.1` does give me the same error
```
[12:10] zer0:winit-0.19.1 $ cargo run --example window
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/examples/window`
thread 'main' panicked at 'assertion failed: validate_hidpi_factor(dpi_factor)', src/platform/linux/x11/util/randr.rs:36:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by kchibisov** [comment]
Do you have `Xft.dpi` set in `.Xresources`?

**Comment by Zer0897** [comment]
I did not. Adding it has no affect.
```
[12:33] zer0 $ xrdb -query -all
Xft.dpi:        96
[12:33] zer0 $ alacritty
thread 'main' panicked at 'assertion failed: validate_hidpi_factor(dpi_factor)', /build/.cargo/git/checkouts/winit-081229dbb0c89e9b/57680d2/src/platform/linux/x11/util/randr.rs:36:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by kchibisov** [comment]
Odd, would you mind restarting x11/rebooting. The assertion that was triggered can be reached if winit fails to retrieve Xft.dpi.

**Comment by Zer0897** [comment]
No change
```py
User: zer0
 Uptime: 1 minute
 Version: 5.2.4-arch1-1-ARCH GNU/Linux
 Storage:
        /        46G / 475G  11%
 Network:
        wlp2s0  10.1.10.232
        wlp2s0  2603:3004:3a:d800::70
        wlp2s0  2603:3004:3a:d800:e898:b87e:4a9c:92ab

[12:46] zer0 $ alacritty
thread 'main' panicked at 'assertion failed: validate_hidpi_factor(dpi_factor)', /build/.cargo/git/checkouts/winit-081229dbb0c89e9b/57680d2/src/platform/linux/x11/util/randr.rs:36:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I am using [a minimal display manager](https://wiki.archlinux.org/index.php/CDM) and [xmonad](https://xmonad.org/) as my window manager. Not sure if that means anything.

**Comment by kchibisov** [comment]
Could you try this one `env WINIT_HIDPI_FACTOR=1 alacritty`?

**Comment by Zer0897** [comment]
That worked! The virtual display must not be picking up the settings correctly.

**Comment by chrisduerr** [comment]
If winit works, but v0.19.1 doesn't, that sounds like it has been fixed in the latest winit. Could you test the latest glutin (https://github.com/rust-windowing/glutin) and downgrading glutin to the latest release in case the latest master works.

**Comment by Zer0897** [comment]
Both `gluten` master and `v0.21.0` work fine.

**Comment by chrisduerr** [comment]
Are you *positive* you've tested #2438? The text in the code snippet says you're on your master branch.

**Comment by Zer0897** [comment]
Oh nice catch! Forgot to checkout the branch after cloning the fork. 

That runs perfectly! @chrisduerr

**Comment by chrisduerr** [comment]
Thanks for checking again, then everything makes sense. Marking this issue as fixed by the mentioned PR.
