### ISSUE TITLE
Alacritty using up multiple X-clients for each terminal

### ISSUE THREAD

**Issue by stefanberndtsson** [jwilm/alacritty#2735]
Which operating system does the issue occur on?
Archlinux

If on linux, are you using X11 or Wayland?
X11

I currently have 46 terminals running (having lots of terminals is a normal workflow for me, on multiple displays with multiple virtual screens). There are also a few other applications such as Firefox running, but in comparison those are few.

When starting the next alacritty I get:
```
Maximum number of clients reachedthread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: XcbConn(Connection)', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

This is clearly an issue reaching the maximum number of clients in the Xorg server, however if I now start xterm it works fine. I can open four xterms fine before the fifth stops me, leading me to believe that alacritty consumed somewhere around five X-clients for each window.

Whether or not this is anything that can be dealt with, I don't know, but it's preventing me from using alacritty as I'd like. Changing the maximum number of clients requires a recompilation of Xorg, which is too much work keeping up with patching and new versions.

**Comment by chrisduerr** [comment]
There might be some improvements Alacritty can make in this regard. But I'd assume some of the differences between Alacritty and XTerm would be that I think Alacritty spawns separate Windows for the X11 clipboard, since that uses a library that is completely disconnected from Alacritty.

Assuming that XTerm creates exactly one connection that would still leave about one connection over. Which I'd say isn't a massive deal but there might be some chance for optimization. We could also look into integrating our X11 clipboard handling deeper into Alacritty.

I don't expect this to be solved soon though, since I don't think many people have this problem. However if your goal is to just fix it, I think the default limit of X connections is 256 and you can switch that to 512 in the X config. So that would likely resolve it for you already.

**Comment by stefanberndtsson** [comment]
Thank you for the quick reply. It was possible to change it all the way up to 2048, which from a clean system gives me around 160 terminals available before things go belly up (possibly for other reasons than max clients). At the same time I can start 1000 xterms, but 160 terminals is more than enough.

From my perspective, my actual problem has been dealt with, so feel free to do whatever seems suitable with this github issue.

**Comment by chrisduerr** [comment]
I think it's worth at least investigating what each X session is used for, even if we do not decide to do anything about it. Just to make sure we're not just pointlessly wasting resources.

I doubt I'll get to it anytime soon, but I don't think it will hurt to keep this around.

**Comment by haarp** [comment]
I ran into this issue today with a mere 15 terminals open. It seems it's rather easy to overhwelm Xorg. 
@stefanberndtsson how did you change the number of clients in X?

**Comment by stefanberndtsson** [comment]
@haarp I added `-maxclients 2048` in my `/etc/X11/xinit/xserverrc` and restarted X. I'm running Arch on this machine, so it may be in some other location in other distributions.

**Comment by hiredman** [comment]
I run out of clients with around 20 alacritty terminals. It starts to effect other programs (they can't launch). My work around at the moment is to close some alacritty instances and replace them xterms when I hit the limit (I can always open xterms even if other things error out with on the client limit)

**Comment by ilmagico** [comment]
This just happened to me as well, only alacritty has this issue, every other X11 application works fine as far as I can tell (xterm, urxvt,  st, roxterm, as well as every other X11 application I tried). I had about 37 alacritty terminals open.
```
$ alacritty --version
alacritty 0.4.2

$ pidof alacritty | wc -w
37

$ alacritty
Maximum number of clients reachedthread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: XcbConn(Connection)', alacritty_terminal/src/clipboard.rs:57:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

$ xterm
< xterm windows comes up, everything's good >
```
I did a quick experiment to see how many connection `alacritty` uses: I opened as many `xterm`s as I could before `xterm` itself gave me that error, then I closed exactly one `alacritty` terminal, and counted how many `xterm` I could open then.
I found that I could open an extra 5 `xterm` instances after closing one `alacritty` instance.

Assuming xterm uses only one connection, I'd have to guess `alacritty` uses 5, so with 37 running `alacritty` terminals I'm using 185 connection, which is quite a bit if the default is 256 (as it is for me, using Manjaro). I think it would be nice if `alacritty` could use only one connection instead of 5, pretty please ;)

**Comment by dkowis** [comment]
I just ran into this today on `alacritty 0.6.0`. And of course, during a production incident. Was rather shocking to not be able to open a terminal. And I only have like 7 of them open :(

**Comment by lf-** [comment]
I ran into this and nearly filed a duplicate issue. Regrettably it has already been reported, so I don't get to use the title I came up with: "Terminal terminal hoarding uses excessive X11 connections, becoming terminal for the terminal"

I can confirm that it is 5 connections per process:

```
$ sudo lsof +E -aUc Xorg | grep alacritty
<...>
alacritty 3712477 jade    3u  unix 0x00000000b9926acf      0t0 49290431 type=STREAM ->INO=49284737 1511,Xorg,100u (CONNECTED)
alacritty 3712477 jade   34u  unix 0x000000000f665b3e      0t0 49267262 type=STREAM ->INO=49299525 1511,Xorg,201u (CONNECTED)
alacritty 3712477 jade   35u  unix 0x000000001ede0f62      0t0 49267263 type=STREAM ->INO=49299526 1511,Xorg,242u (CONNECTED)
alacritty 3712477 jade   36u  unix 0x00000000bcb72961      0t0 49267264 type=STREAM ->INO=49299527 1511,Xorg,243u (CONNECTED)
alacritty 3712477 jade   37u  unix 0x000000001e039e0e      0t0 49267265 type=STREAM ->INO=49299528 1511,Xorg,244u (CONNECTED)

alacritty 3894287 jade    3u  unix 0x00000000553201eb      0t0 50058299 type=STREAM ->INO=50048588 1511,Xorg,179u (CONNECTED)
alacritty 3894287 jade   34u  unix 0x000000005138d5ac      0t0 50038764 type=STREAM ->INO=50041517 1511,Xorg,180u (CONNECTED)
alacritty 3894287 jade   35u  unix 0x00000000f2f8f453      0t0 50038765 type=STREAM ->INO=50041518 1511,Xorg,181u (CONNECTED)
alacritty 3894287 jade   36u  unix 0x00000000b0be08e2      0t0 50038766 type=STREAM ->INO=50056553 1511,Xorg,182u (CONNECTED)
alacritty 3894287 jade   37u  unix 0x00000000f9db9ce1      0t0 50038767 type=STREAM ->INO=50048590 1511,Xorg,183u (CONNECTED)
```

**Comment by lf-** [comment]
OK so I figured out why alacritty is doing this:  this unexplained commit was made to x11_clipboard: https://github.com/quininer/x11-clipboard/commit/7420fb059b9921081e34ec48166b982247aa0d83 which makes it use two connections and make it impossible to pass in our own connection. We then have two instances of this plus a connection for our window. I have tried making it into a single connection, but I have some bugs left that I don't understand (read: it doesn't work) left. So I still have some work on fixing this which I don't have time to in the immediate future.

**Comment by chrisduerr** [comment]
I think a better solution to this might be to replace `x11-clipboard` with a clipboard crate that tries to reuse our existing winit facilities. That should make it possible to completely skip any need for separate X clients.

Unfortunately our suggestion to integrate clipboard handling into winit has been denied, so we can't just implement things in winit directly without forking the project.

**Comment by lf-** [comment]
> I think a better solution to this might be to replace `x11-clipboard` with a clipboard crate that tries to reuse our existing winit facilities. That should make it possible to completely skip any need for separate X clients.
> 
> Unfortunately our suggestion to integrate clipboard handling into winit has been denied, so we can't just implement things in winit directly without forking the project.

I have looked on crates, it seems like we would have to rewrite the actual x11 clipboard handling bits as everything there I could find was based on x11_clipboard (for instance clipboard_x11) and has the duplicate connections issue. Another thing we *could* do is copy what neovim did and give up and just shell out to `xsel`/`xclip` on x11, `pbcopy` on mac, `win32yank` on windows. This is not the ideal way to do it in that it requires external programs, and doesn't resolve the current apparent gap in the ecosystem, but it would fix this bug, be very easy, and delegate owning the cursed x11 code to someone else.

**Comment by quininer** [comment]
Hi, `x11-clipboard` is somewhat poorly maintained, I now recommend using [arboard](https://github.com/ArturKovacs/arboard). see https://github.com/quininer/x11-clipboard/issues/19

**Comment by chrisduerr** [comment]
Arboard is the completely wrong approach for Alacritty. We have existing display server connections so we should not rely on hacky window-less solutions. Since we have the `copypasta` crate that shouldn't be much of a problem, someone just needs to put in the work to hook it up to winit properly. IIRC the GLFW code for X11 clipboard handling is about 30 LoCs, it's relatively simple.

**Comment by quininer** [comment]
I agree with this, it would be nice to have support in winit.

**Comment by Xuanwo** [comment]
Hi @chrisduerr, I'm interested in implement  X11 clipboard support in `copypasta` without setting up extra X clients, can you guide me the way there?

**Comment by chrisduerr** [comment]
> can you guide me the way there?

It's gonna be somewhat difficult. The hardest part is probably figuring out how all of this should plug into winit, since that's the place where the primary X client resides. Implementing the actual clipboard logic should be pretty simple and the same as you see in glfw for example.

**Comment by Xuanwo** [comment]
> It's gonna be somewhat difficult. The hardest part is probably figuring out how all of this should plug into winit, since that's the place where the primary X client resides. Implementing the actual clipboard logic should be pretty simple and the same as you see in glfw for example.

I'm a bit confused about winit.

What's the relation between alacrity with winit? I tried to grep `winit` insides alacrity repo, but only find the following comments:

```
:) rg winit .
./Cargo.lock
708: "winit",
1891:name = "winit"

./alacritty/src/event.rs
1061:        // NOTE: Since this takes a pointer to the winit event loop, it MUST be dropped first.

./alacritty/src/display/mod.rs
319:        // Upstream issue: https://github.com/rust-windowing/winit/issues/806.

./alacritty/src/display/window.rs
226:        // Handle winit reporting invalid values due to incorrect XRandr monitor metrics.
```

**Comment by chrisduerr** [comment]
Winit is a crate Alacritty depends on. If that confuses you I'm not sure this is the best issue to work on.

**Comment by Xuanwo** [comment]
> Winit is a crate Alacritty depends on. If that confuses you I'm not sure this is the best issue to work on.

Well, thanks for the advice.
