### ISSUE TITLE
alacritty 0.3.3 from .deb fails with "X11 status: LibraryOpenError libXcursor.so.1 "

### ISSUE THREAD

**Issue by mbarkhau** [jwilm/alacritty#2777]
When I try to start alacritty version 0.3.3, installed from the .deb file, I get the following error

```
$ RUST_BACKTRACE=full /usr/bin/alacritty
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: LibraryOpenError(OpenError { kind: Library, detail: "opening library failed (libXcursor.so.1: cannot open shared object file: No such file or directory); opening library failed (libXcursor.so: cannot open shared object file: No such file or directory)" })', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.1/src/platform/linux/mod.rs:450:9
stack backtrace:
   0: 0x569f5ede - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h48170a09a1feab1c
                       at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: 0x569f4112 - std::panicking::default_hook::{{closure}}::hae343d7db7f96772
                       at src/libstd/sys_common/backtrace.rs:71
                       at src/libstd/sys_common/backtrace.rs:59
                       at src/libstd/panicking.rs:197
   2: 0x569f3696 - std::panicking::rust_panic_with_hook::h42f90d4077699504
                       at src/libstd/panicking.rs:211
                       at src/libstd/panicking.rs:474
   3: 0x568fa65e - std::panicking::begin_panic::h1393e6fd00c6a3d6
                       at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panicking.rs:408
   4: 0x5667ae81 - alacritty::main::h04645f7d96367f01
                       at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.1/src/platform/linux/mod.rs:450
                       at alacritty/src/main.rs:114
   5: 0x566567a5 - std::rt::lang_start::{{closure}}::hc0ffe7eac5260f70
                       at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/rt.rs:64
   6: 0x56a07f05 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4845a84a915322b5
                       at src/libstd/rt.rs:49
                       at src/libstd/sys_common/backtrace.rs:136
   7: 0x5667c77d - main
   8: 0xf7b6f750 - __libc_start_main
   9: 0x56650410 - <unknown>
```

My system info:

```
$ uname -a
Linux mb-office-201810 5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ echo $XDG_SESSION_TYPE
x11
$ echo $DESKTOP_SESSION
gnome-flashback-metacity
```

I tried installing the lib, but it appears to already be installed.

```
$ sudo apt install libxcursor1
Reading package lists... Done
Building dependency tree
Reading state information... Done
libxcursor1 is already the newest version (1:1.2.0-1).
```

I also have alacritty version 0.2.0 installed, which is working fine.

**Comment by mbarkhau** [comment]
Terribly sorry, I installed the i386 version by mistake.
