### ISSUE TITLE
Crash under wayland if fullscreen configured

### ISSUE THREAD

**Issue by jodh-intel** [jwilm/alacritty#2980]
Which operating system does the issue occur on?

> Running HEAD (561063b) on Fedora 31 with gnomel.

If on linux, are you using X11 or Wayland?

> Wayland

I've configured `window.startup_mode = Fullscreen`. That works fine if I set 
`WAYLAND_DISPLAY=""` or `WINIT_UNIX_BACKEND=x11`, but crashes if neither variable is set:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0:     0x5650c5c258fc - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x5650c5c258fc - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x5650c5c258fc - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x5650c5c258fc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x5650c5ae6a2c - core::fmt::write::h01edf6dd68a42c9c
                               at src/libcore/fmt/mod.rs:1030
   5:     0x5650c5c250f6 - std::io::Write::write_fmt::hf15985f193f03c04
                               at src/libstd/io/mod.rs:1412
   6:     0x5650c5c24d70 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x5650c5c24d70 - std::sys_common::backtrace::print::hf89a79e3921a2366
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x5650c5c24d70 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
                               at src/libstd/panicking.rs:196
   9:     0x5650c5c244bf - std::panicking::default_hook::h8f803b0bc31a5c37
                               at src/libstd/panicking.rs:210
  10:     0x5650c5c244bf - std::panicking::rust_panic_with_hook::h825f041245da8739
                               at src/libstd/panicking.rs:473
  11:     0x5650c5c23fef - std::panicking::continue_panic_fmt::hbe0378e33481e81b
                               at src/libstd/panicking.rs:380
  12:     0x5650c5c384f6 - rust_begin_unwind
                               at src/libstd/panicking.rs:307
  13:     0x5650c5ae0ca9 - core::panicking::panic_fmt::h527855ce0bc891f6
                               at src/libcore/panicking.rs:85
  14:     0x5650c5ae2508 - core::panicking::panic::h2f49f09cf859b728
                               at src/libcore/panicking.rs:49
  15:     0x5650c5c8b169 - core::option::Option<T>::unwrap::h6bc293abd8d632d2
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/macros.rs:12
  16:     0x5650c5c8b169 - winit::platform_impl::platform::wayland::window::Window::current_monitor::h9657923e1e0be145
                               at /home/james/.cargo/git/checkouts/winit-c2fdb27092aba5a7/9828f36/src/platform_impl/linux/wayland/window.rs:334
  17:     0x5650c58f9029 - winit::platform_impl::platform::Window::current_monitor::hc6b2e4c7c9603868
                               at /home/james/.cargo/git/checkouts/winit-c2fdb27092aba5a7/9828f36/src/platform_impl/linux/mod.rs:433
  18:     0x5650c58f9029 - winit::window::Window::current_monitor::h6f380ea3a714a466
                               at /home/james/.cargo/git/checkouts/winit-c2fdb27092aba5a7/9828f36/src/window.rs:744
  19:     0x5650c58f9029 - alacritty::window::Window::set_fullscreen::h3b97f60e9e204ef8
                               at alacritty/src/window.rs:349
  20:     0x5650c58eafcb - alacritty::display::Display::new::hc02047fe1797065d
                               at alacritty/src/display.rs:227
  21:     0x5650c592e369 - alacritty::run::h2df2ba017202784d
                               at alacritty/src/main.rs:138
  22:     0x5650c592e369 - alacritty::main::h0cbfe772fa0772c1
                               at alacritty/src/main.rs:107
  23:     0x5650c5936d03 - std::rt::lang_start::{{closure}}::hc4804fc9bc09ac10
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  24:     0x5650c59288ee - main
  25:     0x7f3e72c681a3 - __libc_start_main
  26:     0x5650c58b320e - _start
  27:                0x0 - <unknown>
```

A workaround is to disable fullscreen by setting `window.startup_mode = Windowed` and then toggling fullscreen mode.

**Comment by kchibisov** [comment]
duplicate #2714

**Comment by kchibisov** [comment]
Oh, and a proper workaround is to start in Windowed and the toggle fullscreen.
