### ISSUE TITLE
Crash on assertion since 36185c47533d6189c9116df7a41a13766ca2b40c

### ISSUE THREAD

**Issue by kchibisov** [jwilm/alacritty#3088]
I've managed to repro it only with the following thing.

Enter `tmux`, run `watch -n 1 sensors`, toggle fullscreen, toggle it once again. So it crashes during shrinking.

Backtrace
```
thread 'main' panicked at 'assertion failed: mid <= self.len()', /rustc/412f43ac5b4ae8c3599e71c6972112e9be4758fa/src/libcore/macros/mod.rs:15:40
stack backtrace:
   0:     0x555881bb5204 - backtrace::backtrace::libunwind::trace::h1702f02e9561de90
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x555881bb5204 - backtrace::backtrace::trace_unsynchronized::h1c634812fc0220cb
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x555881bb5204 - std::sys_common::backtrace::_print_fmt::h9d5a053d21e8c033
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x555881bb5204 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc65c735014fa52d2
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x555881bdc42c - core::fmt::write::h125da652425b39e8
                               at src/libcore/fmt/mod.rs:1030
   5:     0x555881bb1ec7 - std::io::Write::write_fmt::h20322e8675759303
                               at src/libstd/io/mod.rs:1412
   6:     0x555881bb74fe - std::sys_common::backtrace::_print::h56bfd19cdffe3007
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x555881bb74fe - std::sys_common::backtrace::print::h76b7a0cb6d897cab
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x555881bb74fe - std::panicking::default_hook::{{closure}}::h7cd2878d4328ecd0
                               at src/libstd/panicking.rs:188
   9:     0x555881bb71f1 - std::panicking::default_hook::hf3eaa2d2726e3f01
                               at src/libstd/panicking.rs:205
  10:     0x555881bb7bfb - std::panicking::rust_panic_with_hook::h5240f420a7eb117e
                               at src/libstd/panicking.rs:464
  11:     0x555881bb779e - std::panicking::continue_panic_fmt::h2c13cd042727582d
                               at src/libstd/panicking.rs:373
  12:     0x555881bb7686 - rust_begin_unwind
                               at src/libstd/panicking.rs:302
  13:     0x555881bd87de - core::panicking::panic_fmt::h57471c12138e404c
                               at src/libcore/panicking.rs:82
  14:     0x555881bd872a - core::panicking::panic::h7404c94bad530272
                               at src/libcore/panicking.rs:50
  15:     0x555880eec48f - core::slice::<impl [T]>::rotate_left::h13f94fd86904cf5d
                               at /rustc/412f43ac5b4ae8c3599e71c6972112e9be4758fa/src/libcore/macros/mod.rs:15
  16:     0x55588106e326 - alacritty_terminal::grid::storage::Storage<T>::truncate::h5508c9038938e6e5
                               at /home/kchibisov/Developer/rust/forks/alacritty/alacritty_terminal/src/grid/storage.rs:178
  17:     0x55588106e1b2 - alacritty_terminal::grid::storage::Storage<T>::drain::h87088e6a5164a5d7
                               at /home/kchibisov/Developer/rust/forks/alacritty/alacritty_terminal/src/grid/storage.rs:270
  18:     0x55588108026a - alacritty_terminal::grid::Grid<T>::shrink_cols::ha34ef8a5338254ad
                               at /home/kchibisov/Developer/rust/forks/alacritty/alacritty_terminal/src/grid/mod.rs:359
  19:     0x555881082240 - alacritty_terminal::grid::Grid<T>::resize::h1a930b03137c2d69
                               at /home/kchibisov/Developer/rust/forks/alacritty/alacritty_terminal/src/grid/mod.rs:237
  20:     0x55588105d995 - alacritty_terminal::term::Term<T>::resize::h7ef294159e3b0d04
                               at /home/kchibisov/Developer/rust/forks/alacritty/alacritty_terminal/src/term/mod.rs:1088
  21:     0x555880f73737 - alacritty::display::Display::handle_update::hd96fbd4d30cae7ed
                               at alacritty/src/display.rs:341
  22:     0x555880ecd106 - alacritty::event::Processor<N>::run::{{closure}}::h21e74911f7b53142
                               at alacritty/src/event.rs:406
  23:     0x55588113d42f - winit::platform_impl::platform::sticky_exit_callback::h471ea39a234a94f3
                               at /home/kchibisov/.cargo/git/checkouts/winit-c2fdb27092aba5a7/1a514df/src/platform_impl/linux/mod.rs:693
  24:     0x555881070904 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return::h6bad7188bee3c1f7
                               at /home/kchibisov/.cargo/git/checkouts/winit-c2fdb27092aba5a7/1a514df/src/platform_impl/linux/wayland/event_loop.rs:522
  25:     0x55588113c73d - winit::platform_impl::platform::EventLoop<T>::run_return::h13f7b604448cc640
                               at /home/kchibisov/.cargo/git/checkouts/winit-c2fdb27092aba5a7/1a514df/src/platform_impl/linux/mod.rs:629
  26:     0x555880ff2f25 - <winit::event_loop::EventLoop<T> as winit::platform::desktop::EventLoopExtDesktop>::run_return::he973a4d82bc8cf23
                               at /home/kchibisov/.cargo/git/checkouts/winit-c2fdb27092aba5a7/1a514df/src/platform/desktop.rs:43
  27:     0x555880ecc78b - alacritty::event::Processor<N>::run::h0e9448c5bab1a9c1
                               at alacritty/src/event.rs:350
  28:     0x555880f7a7df - alacritty::run::hb8ec30082b1f608e
                               at alacritty/src/main.rs:223
  29:     0x555880f7922d - alacritty::main::h0c04137696c12767
                               at alacritty/src/main.rs:114
  30:     0x5558810a1260 - std::rt::lang_start::{{closure}}::h3036f85b091705eb
                               at /rustc/412f43ac5b4ae8c3599e71c6972112e9be4758fa/src/libstd/rt.rs:61
  31:     0x555881bb7623 - std::rt::lang_start_internal::{{closure}}::h16dc1ac2088d9f7a
                               at src/libstd/rt.rs:48
  32:     0x555881bb7623 - std::panicking::try::do_call::h0ce6ab68fad638ec
                               at src/libstd/panicking.rs:287
  33:     0x555881bc01ca - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:81
  34:     0x555881bb80dd - std::panicking::try::hc9afc7e8c88da3b3
                               at src/libstd/panicking.rs:265
  35:     0x555881bb80dd - std::panic::catch_unwind::hda5772ede2be7694
                               at src/libstd/panic.rs:395
  36:     0x555881bb80dd - std::rt::lang_start_internal::h5c5e596798427697
                               at src/libstd/rt.rs:47
  37:     0x5558810a1239 - std::rt::lang_start::h91350cc24be06879
                               at /rustc/412f43ac5b4ae8c3599e71c6972112e9be4758fa/src/libstd/rt.rs:61
  38:     0x555880f7ad6a - main
  39:     0x7f1fee29ff1b - __libc_start_main
  40:     0x555880e4d1aa - _start
  41:                0x0 - <unknown>

```

**Comment by joaomatos02** [comment]
Same here.

**Comment by chrisduerr** [comment]
@kchibisov I'd assume that my recent change to fix the `yes` issue broke this?

I'd be curious how `self.zero` ever gets above `self.inner.len()`. I thought I made sure that wasn't possible.

**Comment by sterlingjensen** [comment]
I replicated the crash and can confirm that the patch resolves the problem.

**Comment by sterlingjensen** [comment]
```
fn wrap_index(&self, index: usize) -> usize {
        if index >= self.inner.len() {
            index - self.inner.len() // <----------- Off by one?
        } else {
            index
        }
    }
```
https://github.com/jwilm/alacritty/commit/36185c47533d6189c9116df7a41a13766ca2b40c#diff-f4d2c650ece44a016be37049a78804b4R280-R292

**Comment by chrisduerr** [comment]
>             index - self.inner.len() // <----------- Off by one?

No. Indexing starts at 0, so if the index is equal to `len`, then we need to subtract `len`, so it indexes to the first element correctly. It's not possible to index an array with the array's `len` in 0-index based systems.

**Comment by sterlingjensen** [comment]
Yes. `index` is the product of a prior sum, and there are conditions that somehow result in `self.zero + count + self.inner.len() == self.inner.len() * 2 + 1`, leading to an off by one error following the subtraction of `self.inner.len()` inside `wrap_index`, which gets assigned to `self.zero`, ending in `rotate_left` choking on it. The modulo operation made it impossible for that miscalculation to hit `self.zero`, but the new `wrap_index` function isn't so lucky. I'm working on figuring out the cause, because it seems to me to predate #3060, with modulo masking an earlier miscalculation.

**Comment by chrisduerr** [comment]
This was not an off by one error...

And it doesn't predate #3060 either. The issue was addressed correctly in #3089 and it had absolutely nothing to do with an off by one.

**Comment by sterlingjensen** [comment]
```
grid::storage:257  self.wrap_index((self.zero=1071 + count=19 + len=1089)=2179)
grid::storage:287  if index=2179 >= self.inner.len()=1089 { (index=2179 - self.inner.len()=1089)=1090 }
grid::storage:257  self.zero = 1090
grid::storage:178  rotate_left(self.zero=1090)
core::slice:2042   assert!(mid=1090 <= self.len()=1089);
panicked at 'assertion failed: mid <= self.len()', src\libcore\slice\mod.rs:1962:9
```
Pretty classic example of mixing lengths and indexes and coming up off by one, but I guess it could be a coincidence and I'm presuming too much about how you expected that `index` variable to behave. Interestingly (to me at least), the same trace yields the same values that get summed into `self.zero` - in commits that predate `wrap_index`. The only difference being the modulo just prior to assignment.
My point being: that sum can't function as an index or a length (unless modified further up the chain). The closest you can get within the `wrap_index` function involves breaking the first ge comparison up to handle gt and eq on different match arms - but it couldn't pass 2 of the ref tests without changes that would defeat its purpose.

**Comment by chrisduerr** [comment]
I'm not really sure what your point is. I don't see why it wouldn't work, since it has been working just fine for years.

This bug was just a minor oversight due to exceeding the 2 * inner.len() limit for the wrap_index function, but that is completely unrelated to the function of the ringbuffer.

**Comment by sterlingjensen** [comment]
Oh I'll readily admit that I find the setup fairly opaque. That isn't a value judgement, lots of tradeoffs are needed for a performant scrollback implementation - complexity being one such trade. I am curious about the interaction of those variables in relation to `self.zero` though, I don't think I'll find satisfaction until I run them through an SMT solver - but that is a personal problem :no_mouth:
I did spend some time in the debugger though, and found some pathological cases that would likely require more than three branches (gt, lt, eq) to fully cover. At least two of those branches require an additional guard, without which you get either an overflow or an off by one (seriously, two more happen whichever method you try). So performance would suffer. I doubt recursion would improve performance over the modulo, but it would work.
I guess my point is that without some modification to those input variables, I don't believe that you can outperform the existing solution. Not that I'm wishing failure on such an endeavor. Actually... did you considered a function signature that breaks those summed variables up? `const fn` grows by the day :grin:
