### ISSUE TITLE
Index out of bounds (scroll-back)

### ISSUE THREAD

**Issue by sQVe** [jwilm/alacritty#3112]
Hey :wave:,

I noted today when running `jest` (_a JavaScript test runner_) that `alacritty` crashed consistently. This is only happening when running it `jest` with the `--watch` option and scrolling.

Reproduce the following way:
- Run `jest --watch` in a project with a couple of failing tests.
- Scroll up to, lets say, the first failing test.
- Modify and save a watched file, triggering a rerun of `jest` and resulting in `alacritty` crashing (output available below with `RUST_BACKTRACE=full`).

### System

OS: Arch Linux
Version: `alacritty 0.4.0` output
Linux/BSD: X11, i3wm only

### Logs

Crashes:
```
thread 'main' panicked at 'index out of bounds: the len is 34 but the index is 39', /build/rust/src/rustc-1.39.0-src/src/libcore/slice/mod.rs:2717:10
stack backtrace:
   0:     0x55954082ad6c - <unknown>
   1:     0x5595406eac8c - <unknown>
   2:     0x55954082a446 - <unknown>
   3:     0x55954082a060 - <unknown>
   4:     0x5595408297af - <unknown>
   5:     0x5595408292df - <unknown>
   6:     0x55954083dfb6 - <unknown>
   7:     0x5595406e4ec9 - <unknown>
   8:     0x5595406e49e4 - <unknown>
   9:     0x55954062f959 - <unknown>
  10:     0x5595404f3f9c - <unknown>
  11:     0x559540579e77 - <unknown>
  12:     0x5595405d9fad - <unknown>
  13:     0x5595405360dd - <unknown>
  14:     0x559540636de3 - <unknown>
  15:     0x55954052cf2e - <unknown>
  16:     0x7f2628649153 - __libc_start_main
  17:     0x5595404b40de - <unknown>
  18:                0x0 - <unknown>
```
Font/Terminal size:
```
[2019-12-19 21:46] [INFO] Welcome to Alacritty
[2019-12-19 21:46] [INFO] Configuration loaded from "/home/sqve/.config/alacritty/alacritty.yml"
[2019-12-19 21:46] [DEBUG] Estimated DPR: 2
[2019-12-19 21:46] [DEBUG] Estimated Cell Size: 12 x 30
[2019-12-19 21:46] [DEBUG] Estimated Dimensions: None
[2019-12-19 21:46] [INFO] Device pixel ratio: 2
[2019-12-19 21:46] [INFO] Initializing glyph cache...
[2019-12-19 21:46] [INFO] ... finished initializing glyph cache in 0.017487031s
[2019-12-19 21:46] [INFO] Cell Size: 12 x 30
[2019-12-19 21:46] [INFO] Padding: 8 x 8
[2019-12-19 21:46] [INFO] Width: 1600, Height: 1200
[2019-12-19 21:46] [INFO] PTY Dimensions: Line(39) x Column(132)
[2019-12-19 21:46] [INFO] Initialisation complete
[2019-12-19 21:46] [DEBUG] New num_cols is 98 and num_lines is 69
[2019-12-19 21:46] [INFO] Width: 1192, Height: 2092
```

:pray:

**Comment by kchibisov** [comment]
Could you compile `alacritty` with debug symbols? `alacritty` compiling with it by default (I guess your distro stripped them), so just cloning repo and running `RUST_BACKTRACE=full cargo run --release` + your program should be enough.

**Comment by sQVe** [comment]
@kchibisov You can find my config at: https://github.com/sQVe/dotfiles/blob/59d2ec83c4679eb6a9d16173a79da188cfa35b9e/config/alacritty/alacritty.yml

I'll try to get back to you with the rest ASAP.

**Comment by kchibisov** [comment]
@sQVe Could you try changing `tabspaces: 2` to `tabspaces: 8`?

**Comment by sQVe** [comment]
@kchibisov Made no difference.

**Comment by sQVe** [comment]
@kchibisov I hope this is what you wanted :confused: :smile: 

```
% RUST_BACKTRACE=full cargo run --
Finished dev [unoptimized + debuginfo] target(s) in 0.20s
     Running `target/debug/alacritty`
thread 'main' panicked at 'assertion failed: requested < self.len', alacritty_terminal/src/grid/storage.rs:207:9
stack backtrace:
   0:     0x56111dd6f4f4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h21699a12ad89cf9f
   1:     0x56111dd930ec - core::fmt::write::he12294695f2778ef
   2:     0x56111dd6c0d7 - std::io::Write::write_fmt::h44777a27e04ddecd
   3:     0x56111dd71b65 - std::panicking::default_hook::{{closure}}::h7e923e764d745d9a
   4:     0x56111dd71856 - std::panicking::default_hook::h6f2cc98a7e41cc12
   5:     0x56111dd72265 - std::panicking::rust_panic_with_hook::h41fbff0b3efc0b6b
   6:     0x56111d835513 - std::panicking::begin_panic::h7b5944eacc2c368a
                               at /build/rust/src/rustc-1.39.0-src/src/libstd/panicking.rs:407
   7:     0x56111ce8397d - alacritty_terminal::grid::storage::Storage<T>::compute_index::h9d15631a563c7e45
                               at /home/sqve/code/alacritty/<::std::macros::panic macros>:3
   8:     0x56111ce83077 - <alacritty_terminal::grid::storage::Storage<T> as core::ops::index::Index<usize>>::index::h1d2c205692cadbac
                               at /home/sqve/code/alacritty/alacritty_terminal/src/grid/storage.rs:298
   9:     0x56111cf425d3 - <alacritty_terminal::grid::DisplayIter<T> as core::iter::traits::iterator::Iterator>::next::hbda330fcea47c0a0
                               at /home/sqve/code/alacritty/alacritty_terminal/src/grid/mod.rs:942
  10:     0x56111d02fdb6 - <alacritty_terminal::term::RenderableCellsIter<C> as core::iter::traits::iterator::Iterator>::next::hbc2ada4044b698fa
                               at /home/sqve/code/alacritty/alacritty_terminal/src/term/mod.rs:424
  11:     0x56111ce5dde6 - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter::h45c74335abe468cd
                               at /build/rust/src/rustc-1.39.0-src/src/liballoc/vec.rs:1923
  12:     0x56111ce6477d - <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::h2a0f3bb2aea1f6dc
                               at /build/rust/src/rustc-1.39.0-src/src/liballoc/vec.rs:1836
  13:     0x56111d035a7b - core::iter::traits::iterator::Iterator::collect::he718b421f8119dbf
                               at /build/rust/src/rustc-1.39.0-src/src/libcore/iter/traits/iterator.rs:1478
  14:     0x56111d05dc37 - alacritty::display::Display::draw::h69e776e1cfd22c3e
                               at alacritty/src/display.rs:363
  15:     0x56111cf06489 - alacritty::event::Processor<N>::run::{{closure}}::h371cee7f5a0603b1
                               at alacritty/src/event.rs:421
  16:     0x56111d05bd5d - winit::platform_impl::platform::sticky_exit_callback::hd9b62c2511296517
                               at /home/sqve/.cargo/git/checkouts/winit-c2fdb27092aba5a7/1a514df/src/platform_impl/linux/mod.rs:693
  17:     0x56111cf79340 - winit::platform_impl::platform::x11::EventLoop<T>::run_return::hf0f977b3ce7e837e
                               at /home/sqve/.cargo/git/checkouts/winit-c2fdb27092aba5a7/1a514df/src/platform_impl/linux/x11/mod.rs:307
  18:     0x56111d05b09c - winit::platform_impl::platform::EventLoop<T>::run_return::h5aec28dd2c2c9b9b
                               at /home/sqve/.cargo/git/checkouts/winit-c2fdb27092aba5a7/1a514df/src/platform_impl/linux/mod.rs:630
  19:     0x56111cf3fdd5 - <winit::event_loop::EventLoop<T> as winit::platform::desktop::EventLoopExtDesktop>::run_return::h324d089cd5b171d4
                               at /home/sqve/.cargo/git/checkouts/winit-c2fdb27092aba5a7/1a514df/src/platform/desktop.rs:43
  20:     0x56111cf059fb - alacritty::event::Processor<N>::run::h815d573c8106bb6c
                               at alacritty/src/event.rs:347
  21:     0x56111cff59a1 - alacritty::run::he2df2e80786827b7
                               at alacritty/src/main.rs:204
  22:     0x56111cff448b - alacritty::main::hcd793457f7129a2c
                               at alacritty/src/main.rs:112
  23:     0x56111d0749d0 - std::rt::lang_start::{{closure}}::h18ccda6b18ecd848
                               at /build/rust/src/rustc-1.39.0-src/src/libstd/rt.rs:64
  24:     0x56111dd71c93 - std::panicking::try::do_call::h124c6ea999389772
  25:     0x56111dd7a93a - __rust_maybe_catch_panic
  26:     0x56111dd7275d - std::rt::lang_start_internal::hb16191a81589c44a
  27:     0x56111d0749a9 - std::rt::lang_start::h3311952adc794e8d
                               at /build/rust/src/rustc-1.39.0-src/src/libstd/rt.rs:64
  28:     0x56111cff5f6a - main
  29:     0x7fdb1d2ce153 - __libc_start_main
  30:     0x56111ce4610e - _start
  31:                0x0 - <unknown>
```

**Comment by kchibisov** [comment]
Oh, thx, so it's crashing on assertion now.

**Comment by kchibisov** [comment]
@sQVe Could you test v0.3.3? just `git checkout v0.3.3`.

**Comment by sQVe** [comment]
@kchibisov I'll try is as soon as I get to work tomorrow!

**Comment by sQVe** [comment]
@kchibisov Working fine in `alacritty 0.3.3`.

**Comment by kchibisov** [comment]
Could you test this commit 182a9d5c2e01ec9b155fc7edf547e8e6de2f2bd5 and the one before it?

**Comment by sQVe** [comment]
@kchibisov Getting this output when trying:
```
% RUST_BACKTRACE=full cargo run --
    Updating git repository `https://github.com/chrisduerr/glutin`
error: failed to load source for a dependency on `glutin`

Caused by:
  Unable to update https://github.com/chrisduerr/glutin#89aed1cb

Caused by:
  revspec '89aed1cbfe38532c15d073e3b0822362cab3e044' not found; class=Reference (4); code=NotFound (-3)
```

**Comment by kchibisov** [comment]
@sQVe try running `cargo update -p glutin`, it should compile just fine after it.

**Comment by sQVe** [comment]
@kchibisov 182a9d5c2e01ec9b155fc7edf547e8e6de2f2bd5 fails but bcdc605436ebe137173c531844a739eda6ee41ae works fine, i.e. 182a9d5c2e01ec9b155fc7edf547e8e6de2f2bd5 introduced the problem.

**Comment by kchibisov** [comment]
@sQVe thanks for bisecting.

cc @nixpulvis

**Comment by kchibisov** [comment]
Ok. I found an easy repro. Just output something to create a scroll back (e.g. `ls -lah`), then do `sleep 3; clear` and scroll up.
