### ISSUE TITLE
thread 'main' panicked at 'expected send event loop msg'

### ISSUE THREAD

**Issue by Swiiip** [jwilm/alacritty#320]
Hello guys,

I tried to install allacritty on macOS Yosemite 10.10.5. It went well but when I launch it and press any key, I have this error:

- Macbook pro retina early 2015 
- OS: macOS Yosemite 10.10.5
- Chipset gpu: Intel Iris Graphics 6100 1536 Mo
- Keyboard layout: fr

```Initializing glyph cache
Finished initializing glyph cache in 0.036782698
set_inner_size: 1124px × 676px
width: 1124, height: 676
Cell Size: (14 x 28)
PTY Dimensions: Line(24) x Column(80)
thread 'pty reader' panicked at 'unexpected err: Error { repr: Os { code: 5, message: "Input/output error" } }', src/event_loop.rs:283
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'expected send event loop msg', src/event_loop.rs:65```

**Comment by jwilm** [comment]
That's really quite strange. This says you got an `EIO` during `write`. No idea what that means in the context of a pty.

Could you run with `RUST_BACKTRACE=1` and provide the log?

**Comment by Swiiip** [comment]
Here is the backtrace: 

```device_pixel_ratio: 2
device_pixel_ratio: 2
width: 2048, height: 1510
Initializing glyph cache
Finished initializing glyph cache in 0.033883028
set_inner_size: 1124px × 676px
width: 1124, height: 676
Cell Size: (14 x 28)
PTY Dimensions: Line(24) x Column(80)
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
Jan 17 11:20:21 fr-c02pxnl4fvh5 alacritty[45063] <Warning>: CGSLookupServerPort: _CGSSessionDeathWatchPort(gSessionPort) returns 268435459
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
child finished with error '11'

**Comment by jwilm** [comment]
Is this still a problem for you?
