### ISSUE TITLE
Displaying Certain Unicode Characters Crashes Alacritty

### ISSUE THREAD

**Issue by zinic** [jwilm/alacritty#473]
Ran into this while on IRC via `tmux` and `weechat`. The characters being displayed were unicode emoji code points. I saw some rumbling on the `#alacritty` freenode channel about double-width characters and figured that this might be related.

### Bug Details
**Platform:** `Linux - 4.10.0 #2 SMP - x86_64 GNU/Linux`
**Compiled with:** `rustc 1.17.0-nightly (b1e31766d 2017-03-03)`

#### Offending input
```
2017-03-09 12:32:03     GolBot  [ twitter - it's B! Cavello ✊ on Twitter: "The "gig economy" is literally killing us.  Most depressing ad of the day goes to: @fiverr 🙃 https://t.co/xq0sxsL55t" ]
```

#### Backtrace
```
got font path="/usr/share/fonts/dejavu/DejaVuSansMono.ttf"
got font path="/usr/share/fonts/dejavu/DejaVuSansMono-Bold.ttf"
got font path="/usr/share/fonts/dejavu/DejaVuSansMono-Oblique.ttf"
num_cols, num_lines = 85, 36
num_cols, num_lines = 80, 24
num_cols, num_lines = 213, 65
[Unhandled CSI] action='l', args=[1005], intermediates=[63]
thread 'main' panicked at 'index 82 out of range for slice of length 80', /checkout/src/libcore/slice.rs:578
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: core::slice::slice_index_len_fail
             at /checkout/src/libcore/slice.rs:578
   1: font::ft::FreeTypeRasterizer::get_rendered_glyph
             at /checkout/src/libcore/slice.rs:709
             at /checkout/src/libcore/slice.rs:560
             at ./rsys/packages/alacritty/master/font/src/ft/mod.rs:217
   2: font::ft::FreeTypeRasterizer::get_rendered_glyph
             at ./rsys/packages/alacritty/master/font/src/ft/mod.rs:194
   3: alacritty::renderer::GlyphCache::get
             at ./rsys/packages/alacritty/master/font/src/ft/mod.rs:85
             at /checkout/src/libstd/collections/hash/map.rs:1873
             at ./rsys/packages/alacritty/master/src/renderer/mod.rs:267
   4: alacritty::run
             at ./rsys/packages/alacritty/master/src/renderer/mod.rs:785
   5: alacritty::main
             at ./rsys/packages/alacritty/master/src/main.rs:64
```

**Comment by zinic** [comment]
Just noticed that this is a dupe. Closing.

**Comment by jwilm** [comment]
Thanks for the report! I think there's actually a PR up that fixes this, but I haven't had time to investigate. Maybe you'd like to try it out? #465 

Would you mind linking the other issue?
