### ISSUE TITLE
thread 'main' panicked at 'index 50 out of range for slice of length 48', /checkout/src/libcore/slice.rs:578

### ISSUE THREAD

**Issue by gutigen** [jwilm/alacritty#482]
```RUST_BACKTRACE=1 alacritty
thread 'main' panicked at 'index 50 out of range for slice of length 48', /checkout/src/libcore/slice.rs:578
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: __libc_start_main
  15: <unknown>
```

Arch Linux, `alacritty-git`, happens with both rust stable and nightly from rustup.

**Comment by stammw** [comment]
I am running into the same problem, it seems to crash in glyph loading :

``` 
7:     0x56036793b023 - core::slice::slice_index_len_fail::h32dba95666464c4a
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/slice.rs:578
   8:     0x5603678e29f4 - font::ft::FreeTypeRasterizer::get_rendered_glyph::h4dec5f9eab2e4824
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/slice.rs:709
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/slice.rs:560
                        at /home/jc/.local/src/alacritty/font/src/ft/mod.rs:219
   9:     0x5603678e25a0 - font::ft::FreeTypeRasterizer::get_rendered_glyph::h4dec5f9eab2e4824
                        at /home/jc/.local/src/alacritty/font/src/ft/mod.rs:196
  10:     0x5603677f520d - alacritty::renderer::GlyphCache::load_and_cache_glyph::h5bcbd8e45ef20dc8
                        at /home/jc/.local/src/alacritty/font/src/ft/mod.rs:85
  11:     0x5603677f2559 - alacritty::display::Display::new::h59275a39cc7a9c46
```

I tried to do a `git bisect` on this, and I found 4b4a187fbd0cd47cdf6be5614ccfa473f356dac0 was responsible. But this commit does not build : 

```
   Compiling font v0.1.0 (file:///home/jc/.local/src/alacritty/font)
error: this file contains an un-closed delimiter
   --> font/src/ft/list_fonts.rs:587:2
    |
587 | 
    |  ^
    |
help: did you mean to close this delimiter?
   --> font/src/ft/list_fonts.rs:518:11
    |
518 | mod tests {
    |           ^

error: aborting due to previous error

error: Could not compile `font`.
```

**Comment by stammw** [comment]
@gutigen, you still can use 28700ed for the moment but I don't know how to tell it to AUR.

**Comment by N-006** [comment]
@stammw use `source=($pkgname::git+https://github.com/jwilm/alacritty.git#commit=28700ed)`

**Comment by mrkgnao** [comment]
For me this happens if the `x`/`y` offsets are so big that the glyph size becomes negative. (I'm not sure if I'm using those words correctly; I know very little about font rendering.)

**Comment by stammw** [comment]
I just checked out master, and the problem seems to have disapeared.

**Comment by mthssdrbrg** [comment]
Was testing out Alacritty earlier today and ran into this. Built from master (using Rust 1.16.0), running on Arch Linux, and it only happens when I set the font size to something smaller than `10.0` (though the "breaking point" appears to be at `9.5` but I initially wanted to set it to `9.0`).

**Comment by carl-lucas** [comment]
You've got what may be a duplicate bug here: #185 

I'll cross-post some digging I did (seems to have to do with pitch and width calculations, and perhaps width being larger than pitch?):

I've run into this issue as well (specifically the 'index 68 out of range for slice of length 64' version of the panic). Here is some gdb info at the point where the panic occurs in font/src/mod.rs:
```
(gdb) next
212             let mut packed = Vec::with_capacity((bitmap.rows() * bitmap.width()) as usize);
(gdb)
213             for i in 0..bitmap.rows() {
(gdb)
214                 let start = (i as usize) * pitch;
(gdb)
215                 let stop = start + bitmap.width() as usize;
(gdb)
216                 packed.extend_from_slice(&buf[start..stop]);
(gdb) info locals
stop = 8
start = 0
i = 0
iter = core::ops::Range<i32> {start: 1, end: 16}
packed = collections::vec::Vec<u8> {buf: alloc::raw_vec::RawVec<u8> {ptr: core::ptr::Unique<u8> {pointer: core::nonzero::NonZero<*const u8> (0x7ffff511a080 "\000"), _marker: core::marker::PhantomData<u8>}, cap: 128}, len: 0}
pitch = 4
buf = &[u8] {data_ptr: 0x7ffff07f5b80 "\000", length: 64}
bitmap = freetype::bitmap::Bitmap {raw: 0x7ffff50855d8}
glyph = 0x7ffff07e1c08
index = 128
c = 127 '\x7f'
size = 10
face = 0x7ffff07e1bf8
faces = std::collections::hash::map::HashMap<font::FontKey, freetype::face::Face, std::collections::hash::map::RandomState> {hash_builder: std::collections::hash::map::RandomState {k0: 810756667983202956, k1: 9049055774554616794}, table:
std::collections::hash::table::RawTable<font::FontKey, freetype::face::Face> {capacity: 32, size: 4, hashes: std::collections::hash::table::TaggedHashUintPtr (core::ptr::Unique<usize> {pointer: core::nonzero::NonZero<*const usize> (0x7ffff07e1a00), _marker: core::marker::PhantomData<usize>}), marker: core::marker::PhantomData<(font::FontKey, freetype::face::Face)>}, resize_policy: std::collections::hash::map::DefaultResizePolicy}
self = 0x7fffffff4f78
glyph_key = 0x7fffffff3c80
have_recursed = true
```
Note that pitch = 4, while the difference between start and end (i.e. bitmap.width()) is 8. On our last iteration, we end up here (some variables omitted):
```
(gdb) info locals
stop = 68
start = 60
i = 15
iter = core::ops::Range<i32> {start: 16, end: 16}
pitch = 4
buf = &[u8] {data_ptr: 0x7ffff07f5b80 "\000", length: 64}
c = 127 '\x7f'
```
Not sure how best to fix it. My stopgap is to replace line 216 in mod.rs with:
```
let stop = cmp::min(buf.len() as usize, start + bitmap.width() as usize);
```
...but I'm sure there's a better way. Let me know if there is any other info from the trace you need.
