### ISSUE TITLE
Alacritty fails when opening neovim

### ISSUE THREAD

**Issue by hkupty** [jwilm/alacritty#484]
This happens for master and it immediately closes after I try to open `nvim`:

```
got font path="/usr/share/fonts/TTF/iosevka-term-medium.ttf"
got font path="/usr/share/fonts/TTF/iosevka-term-regular.ttf"
got font path="/usr/share/fonts/TTF/iosevka-term-mediumitalic.ttf"
num_cols, num_lines = 136, 54
[Unhandled CSI] action='q', args=[2], intermediates=[32]
[Unhandled CSI] action='h', args=[1004], intermediates=[63]
[Unhandled CSI] action='t', args=[8, 54, 136], intermediates=[]
thread 'main' panicked at 'index 61 out of range for slice of length 60', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/slice.rs:578
stack backtrace:
   1:     0x55cac5bbb14a - <unknown>
   2:     0x55cac5bba5d1 - <unknown>
   3:     0x55cac5bb9730 - <unknown>
   4:     0x55cac5bb9281 - <unknown>
   5:     0x55cac5bb91f9 - <unknown>
   6:     0x55cac5bceba6 - <unknown>
   7:     0x55cac5bce9c3 - <unknown>
   8:     0x55cac5b9a004 - <unknown>
   9:     0x55cac5b99bb0 - <unknown>
  10:     0x55cac5abb1a0 - <unknown>
  11:     0x55cac5a11ec6 - <unknown>
  12:     0x55cac5a0a016 - <unknown>
  13:     0x55cac5a18560 - <unknown>
  14:     0x7f649259e510 - __libc_start_main
  15:     0x55cac59d8a59 - <unknown>
  16:                0x0 - <unknown>
```

**Comment by dylanmc** [comment]
I tried to reproduce this problem, but nvim runs fine for me under alacritty on MacOS X, 10.12.3. More details about configuration/versions?

**Comment by jwilm** [comment]
This is probably an issue with font rendering. There's actually a PR up which works around the problem #465.

**Comment by hkupty** [comment]
While it makes sense that a font rendering bug is involved, I must say that opening the terminal works with the font set.

I just tested and `nvim -u NORC` works as well, which does not load `airline` glyphs.

**Comment by jwilm** [comment]
@hkupty Would you mind trying this with a debug build? Then we can know for certain (backtrace).

**Comment by hkupty** [comment]
It yielded the same log.. Do I need to pass any additional flag?
This is what I just did:
```bash
rustup override set stable
rustup update stable
cargo build
```
It yielded the same output:
```
got font path="/usr/share/fonts/TTF/iosevka-term-medium.ttf"
got font path="/usr/share/fonts/TTF/iosevka-term-regular.ttf"
got font path="/usr/share/fonts/TTF/iosevka-term-mediumitalic.ttf"
num_cols, num_lines = 182, 73
[Unhandled CSI] action='q', args=[2], intermediates=[32]
[Unhandled CSI] action='h', args=[1004], intermediates=[63]
[Unhandled CSI] action='t', args=[8, 73, 182], intermediates=[]
thread 'main' panicked at 'index 61 out of range for slice of length 60', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/slice.rs:578
stack backtrace:
   1:     0x55ff4ef86b0c - <unknown>
   2:     0x55ff4ef8d3de - <unknown>
   3:     0x55ff4ef8cfe4 - <unknown>
   4:     0x55ff4ef8d87b - <unknown>
   5:     0x55ff4ef8d714 - <unknown>
   6:     0x55ff4ef8d639 - <unknown>
   7:     0x55ff4ef8d5c7 - <unknown>
   8:     0x55ff4efb990d - <unknown>
   9:     0x55ff4efb9a09 - <unknown>
  10:     0x55ff4ef37e37 - <unknown>
  11:     0x55ff4ef2ae9e - <unknown>
  12:     0x55ff4ef3ccf8 - <unknown>
  13:     0x55ff4ef3c805 - <unknown>
  14:     0x55ff4ef3abcd - <unknown>
  15:     0x55ff4ea7f0ba - <unknown>
  16:     0x55ff4ea32aac - <unknown>
  17:     0x55ff4ea7efb6 - <unknown>
  18:     0x55ff4ea8272a - <unknown>
  19:     0x55ff4ea7aa6e - <unknown>
  20:     0x55ff4ea80de5 - <unknown>
  21:     0x55ff4ea7a65d - <unknown>
  22:     0x55ff4e8dd961 - <unknown>
  23:     0x55ff4e8dc096 - <unknown>
  24:     0x55ff4ef947ba - <unknown>
  25:     0x55ff4ef8dfe6 - <unknown>
  26:     0x55ff4e8de1f2 - <unknown>
  27:     0x7f6209818510 - __libc_start_main
  28:     0x55ff4e82bf89 - <unknown>
  29:                0x0 - <unknown>
```

**Comment by jwilm** [comment]
That's strange! What platform are you on?

**Comment by hkupty** [comment]
I'm on an Arch Linux box.
I'm building Alacritty using a modified version of the AUR package: https://aur.archlinux.org/packages/alacritty-git/

**Comment by albertorestifo** [comment]
I have the same issue, Arch Linux, same package. Disabling `vim-airline` seems to work for me too

**Comment by jwilm** [comment]
Making #515 the canonical issue for this
