### ISSUE TITLE
Config watcher crashes for No Space Left on Device

### ISSUE THREAD

**Issue by riquito** [jwilm/alacritty#548]
Alacritty starts but the thread supposed to watch the config file for changes dies for no space left on device. The device has space left.

```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/dm-0       368G   31G    336G   9% /
/dev/dm-0       368G   31G    336G   9% /home
tmpfs           9,7G  7,5M    9,7G   1% /tmp
```

```
# Partial `mount` output
/ type btrfs (rw,relatime,seclabel,ssd,space_cache,subvolid=257,subvol=/root)
/home type btrfs (rw,relatime,seclabel,ssd,space_cache,subvolid=258,subvol=/home)
```

```
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 25 (Twenty Five)
Release:	25
Codename:	TwentyFive
```

```
$ rustup --version
rustup 1.2.0 (70faf07 2017-04-08)
$ rustc --version
rustc 1.17.0 (56124baa9 2017-04-24)
```

```
# alacritty "version"
$  git log --oneline | head -n 1
573c503 Fix sign error in CoreText font rasterizer
```

```
# Output of ` RUST_BACKTRACE=1 ./target/release/alacritty`
thread 'config watcher' panicked at 'watch alacritty yml: Io(Error { repr: Os { code: 28, message: "No space left on device" } })', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:71
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   2: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:371
             at /checkout/src/libstd/panicking.rs:549
   3: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   4: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   5: core::panicking::panic_fmt
             at /checkout/src/libstd/panicking.rs:471
   6: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:29
   7: alacritty::config::Monitor::new::{{closure}}
             at /checkout/src/libcore/result.rs:761
             at ./src/config.rs:1374
   8: <F as alloc::boxed::FnBox<A>>::call_box
             at /checkout/src/libstd/panic.rs:296
             at /checkout/src/libstd/panicking.rs:454
             at /checkout/src/libpanic_unwind/lib.rs:98
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/thread/mod.rs:360
             at /checkout/src/liballoc/boxed.rs:640
   9: std::sys::imp::thread::Thread::new::thread_start
             at /checkout/src/liballoc/boxed.rs:650
             at /checkout/src/libstd/sys_common/thread.rs:21
             at /checkout/src/libstd/sys/unix/thread.rs:84
  10: start_thread
  11: clone
```

**Comment by jwilm** [comment]
@passcod have you seen an issue like this with `notify` before?

**Comment by passcod** [comment]
Yep, that's an "inotify limit" error: see https://github.com/passcod/notify/issues/103 and https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers

**Comment by riquito** [comment]
I can confirm that increasing the inotify limit the problem disappears.
If alacritty is correctly watching the minimun number of files (1 I suppose here? I'm not proficient in rust) and not thousands I suppose that we can close this issue.

**Comment by riquito** [comment]
Of course if the error can be distinguished a better error message would be welcome.

**Comment by jwilm** [comment]
@passcod thanks for the tip!

@riquito We just watch the config file (and optionally shader files when building with `live-reload-shaders` feature). Going to close this. Thanks for the report!
