### ISSUE TITLE
'pty reader' panic: Interrupted System Call when using ^Z and fg/bg

### ISSUE THREAD

**Issue by antekone** [jwilm/alacritty#76]
Hello,

I'm using Linux (ArchLinux 64-bit).

When I'm running `alacritty` from other terminal, i.e. gnome-terminal, it runs fine. But when I use `^Z` to suspend `alacritty`'s process and try to put it to background with `^Z` + `bg`, it panics:

```
$ bg
[1]  + 25442 continued  RUST_BACKTRACE=1 ./alacritty
thread 'pty reader' panicked at 'poll ok: Error { repr: Os { code: 4, message: "Interrupted system call" } }', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:845
stack backtrace:
   1:     0x5632fcd6216c - std::sys::imp::backtrace::tracing::imp::write::h9c41d2f69e5caabf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x5632fcd6740e - std::panicking::default_hook::{{closure}}::h1f61f3c769fffe7a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x5632fcd67014 - std::panicking::default_hook::hd5bda4e453dfb4be
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x5632fcd678b7 - std::panicking::rust_panic_with_hook::hffbc74969c7b5d87
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x5632fcd67744 - std::panicking::begin_panic::h3bbdbb2a23440035
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x5632fcd67669 - std::panicking::begin_panic_fmt::h34f5b320b0f94559
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x5632fcd675f7 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x5632fcd9370d - core::panicking::panic_fmt::h1016b85b51d1931f
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x5632fcc526bf - core::result::unwrap_failed::hc1006aeafe0fe326
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/macros.rs:29
  10:     0x5632fcc5aee6 - <alacritty::event_loop::EventLoop<Io>>::spawn::{{closure}}::he56070339a51619b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:769
                        at /home/antek/dev/source/alacritty/src/event_loop.rs:292
  11:     0x5632fcc4618b - std::panicking::try::do_call::ha092a96b23936108
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:296
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:460
  12:     0x5632fcd6e7aa - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  13:     0x5632fcc580fa - <F as alloc::boxed::FnBox<A>>::call_box::ha8fd9a2a9bb1f7ba
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/mod.rs:357
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:605
  14:     0x5632fcd66704 - std::sys::imp::thread::Thread::new::thread_start::h76badbf9b0ecaf58
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  15:     0x7f03ab61b453 - start_thread
  16:     0x7f03ab1477de - __GI___clone
  17:                0x0 - <unknown>
child finished with error '256'
```

Same thing when I use `fg`.

Exactly the same panic is triggered when suspending the system (`systemctl suspend`) and resuming it. All `alacritty` windows are gone after resuming, terminated with the same panic as above (seems it's triggered by `result.rs:292`'s `expect()` call).

**Comment by quininer** [comment]
```diff
--- a/src/event_loop.rs
+++ b/src/event_loop.rs
@@ -289,7 +289,13 @@ impl<Io> EventLoop<Io>
             };
 
             'event_loop: loop {
-                self.poll.poll(&mut events, None).expect("poll ok");
+                self.poll.poll(&mut events, None)
+                    .or_else(|err| if err.kind() == io::ErrorKind::Interrupted {
+                        Ok(0)
+                    } else {
+                        Err(err)
+                    })
+                    .expect("poll ok");
 
                 for event in events.iter() {
                     match event.token() {
```

It just seems to ignore Interrupted Error, I don't know if this is correct.

**Comment by jwilm** [comment]
Thanks for the report. The issue should be resolved on master.
