### ISSUE TITLE
Panic on exit

### ISSUE THREAD

**Issue by michaelmior** [jwilm/alacritty#81]
I get the following panic when exiting alacritty. Just started, did nothing, then closed.

```
thread 'main' panicked at 'window closed', src/event.rs:133
stack backtrace:
   1:     0x563b804b1cda - std::sys::imp::backtrace::tracing::imp::write::h2b860f17b6b0f511
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x563b804b70ff - std::panicking::default_hook::{{closure}}::hedea7d569eb1e6b8
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:349
   3:     0x563b804b6cfe - std::panicking::default_hook::he87e0c76c89c52a4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:365
   4:     0x563b804b75a7 - std::panicking::rust_panic_with_hook::h304127bde2d3d5e2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:553
   5:     0x563b800add63 - std::panicking::begin_panic::h1dc990fced681ffe
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:515
   6:     0x563b800b8e8b - <alacritty::event::Processor<N>>::handle_event::hcbab74fd6e05e51a
                        at /home/mmior/apps/alacritty/<panic macros>:3
   7:     0x563b800b95c3 - <alacritty::event::Processor<N>>::process_events::h09b1b556b138156a
                        at /home/mmior/apps/alacritty/src/event.rs:189
   8:     0x563b801310d8 - alacritty::run::h73c8277231d577c8
                        at /home/mmior/apps/alacritty/src/main.rs:135
   9:     0x563b80130135 - alacritty::main::h41659946f30639e3
                        at /home/mmior/apps/alacritty/src/main.rs:55
  10:     0x563b804be46a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  11:     0x563b804b7ce6 - std::rt::lang_start::h832f9067ed8c4dd4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:434
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/rt.rs:57
  12:     0x563b80131a52 - main
  13:     0x7f3a0f72c82f - __libc_start_main
  14:     0x563b8008dc28 - _start
  15:                0x0 - <unknown>
```

Full output prior to the crash in case it's relevant

```
Config file not found; using defaults
device_pixel_ratio: 1
width: 1024, height: 768
Initializing glyph cache
num fonts = 2661
num fonts = 2661
num fonts = 2661
Finished initializing glyph cache in 0.097084392
set_inner_size: 644px × 436px
width: 644, height: 436
Cell Size: (8 x 18)
PTY Dimensions: Line(24) x Column(80)
num_cols, num_lines = 128, 42
width: 1024, height: 768
num_cols, num_lines = 80, 24
width: 644, height: 436
Set Attribute: Bold
Set Attribute: Reverse
Set Attribute: CancelReverse
Set Attribute: Bold
Set Attribute: Reset
carriage_return
carriage_return
[unhandled osc_start]
[unhandled osc_put] byte='2'
[unhandled osc_put] byte=';'
[unhandled osc_put] byte='m'
[unhandled osc_put] byte='m'
[unhandled osc_put] byte='i'
[unhandled osc_put] byte='o'
[unhandled osc_put] byte='r'
[unhandled osc_put] byte='@'
[unhandled osc_put] byte='s'
[unhandled osc_put] byte='c'
[unhandled osc_put] byte='s'
[unhandled osc_put] byte='p'
[unhandled osc_put] byte='c'
[unhandled osc_put] byte='4'
[unhandled osc_put] byte='8'
[unhandled osc_put] byte='1'
[unhandled osc_put] byte=':'
[unhandled osc_put] byte=' '
[unhandled osc_put] byte='~'
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='a'
[unhandled osc_put] byte='p'
[unhandled osc_put] byte='p'
[unhandled osc_put] byte='s'
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='a'
[unhandled osc_put] byte='l'
[unhandled osc_put] byte='a'
[unhandled osc_put] byte='c'
[unhandled osc_put] byte='r'
[unhandled osc_put] byte='i'
[unhandled osc_put] byte='t'
[unhandled osc_put] byte='t'
[unhandled osc_put] byte='y'
[unhandled osc_end] byte=0
[unhandled osc_start]
[unhandled osc_put] byte='1'
[unhandled osc_put] byte=';'
[unhandled osc_put] byte='.'
[unhandled osc_put] byte='.'
[unhandled osc_put] byte='p'
[unhandled osc_put] byte='p'
[unhandled osc_put] byte='s'
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='a'
[unhandled osc_put] byte='l'
[unhandled osc_put] byte='a'
[unhandled osc_put] byte='c'
[unhandled osc_put] byte='r'
[unhandled osc_put] byte='i'
[unhandled osc_put] byte='t'
[unhandled osc_put] byte='t'
[unhandled osc_put] byte='y'
[unhandled osc_end] byte=0
carriage_return
Set Attribute: Reset
Set Attribute: CancelReverse
Set Attribute: CancelUnderline
clear_screen: Below
Set Attribute: Foreground(Named(Cyan))
Set Attribute: Reset
Set Attribute: Foreground(Indexed(117))
Set Attribute: Reset
Set Attribute: Foreground(Indexed(12))
Set Attribute: Foreground(Indexed(118))
Set Attribute: Foreground(Indexed(12))
Set Attribute: Foreground(Indexed(133))
Set Attribute: Reset
Set Attribute: Foreground(Indexed(77))
Set Attribute: Reset
clear_line: Right
set_mode: CursorKeys
set mode::APP_KEYPAD
set_mode: BracketedPaste
```

**Comment by michaelmior** [comment]
As further info, this only occurs when I click the close button in my window manager, not when I explicitly exit the shell (i.e. type `exit` at the prompt).

**Comment by jwilm** [comment]
Thanks for the report! Fixed on master.

**Comment by michaelmior** [comment]
@jwilm Thanks for the quick fix! Confirmed that this is indeed solved :)
