### ISSUE TITLE
alacritty+tmux crash on `cat /dev/random`

### ISSUE THREAD

**Issue by snatchev** [jwilm/alacritty#814]
> Which operating system does the issue occur on?
macOS 10.12, tmux 2.3

To reproduce the crash, create a new tmux session and `cat /dev/random`. Sometimes it crashes right away, sometimes it takes a few seconds.

```
[Unhandled CSI] action='l', args=[1005], intermediates=[63]
[unhandled osc_dispatch]: [['1','1','2',],] at line 804
thread 'pty reader' panicked at 'index out of bounds: the len is 24 but the index is 24', /Users/travis/build/rust-lang/rust/src/liballoc/vec.rs:1561:14
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic
   4: std::panicking::begin_panic_fmt
   5: core::panicking::panic_fmt
   6: core::panicking::panic_bounds_check
   7: <alacritty::term::Term as alacritty::ansi::Handler>::input
   8: <alacritty::event_loop::EventLoop<Io>>::spawn::{{closure}}
thread 'main' panicked at 'index out of bounds: the len is 24 but the index is 24', /Users/travis/build/rust-lang/rust/src/liballoc/vec.rs:1552:10
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic
   4: std::panicking::begin_panic_fmt
   5: core::panicking::panic_fmt
   6: core::panicking::panic_bounds_check
   7: alacritty::display::Display::draw
   8: alacritty::run
   9: alacritty::main
  10: main
```

**Comment by chrisduerr** [comment]
I can't reproduce this. Might have been fixed with the atlas changes?

**Comment by snatchev** [comment]
@chrisduerr confirming that I cannot reproduce this any longer with master. Great project!
