### ISSUE TITLE
Freezing after <Alt-N> keys combination on Mac Os

### ISSUE THREAD

**Issue by yanlobkarev** [jwilm/alacritty#82]
Hi!
Alacritty window is freeezing after I do keys combinations like `<Alt-N>`, `<Alt-H>` and `<Ctrl-Space>`. OS is `Mac OS Sierra10.12.1 (16B2657)`. In source terminal output I see following:
```bash
alacritty/target/release ಠ_ಠ (master) # export RUST_BACKTRACE=1
alacritty/target/release ಠ_ಠ (master) # ./alacritty
Config file not found; using defaults
device_pixel_ratio: 1
device_pixel_ratio: 1
width: 1024, height: 768
Initializing glyph cache
Finished initializing glyph cache in 0.044627559
set_inner_size: 484px × 316px
width: 484, height: 316
Cell Size: (6 x 13)
PTY Dimensions: Line(24) x Column(80)
thread 'main' panicked at 'window closed', src/event.rs:133
stack backtrace:
   1:        0x101d3993a - std::sys::imp::backtrace::tracing::imp::write::h1461f67be4bf68a9
   2:        0x101d3ba4f - std::panicking::default_hook::{{closure}}::h6dba65b2b498d274
   3:        0x101d3b6f7 - std::panicking::default_hook::ha8ecbcff1f59e805
   4:        0x101d3bf16 - std::panicking::rust_panic_with_hook::h5ceed7bd7aef311a
   5:        0x101c7eb24 - std::panicking::begin_panic::hac4cfc1999155f3b
   6:        0x101c85ef8 - <alacritty::event::Processor<N>>::handle_event::ha2aefe0613e20e4e
   7:        0x101c9f2e3 - alacritty::run::hb24e186a0c9a26a5
   8:        0x101c9d375 - alacritty::main::h6cfa89d1e4d178de
   9:        0x101d3cd6a - __rust_maybe_catch_panic
  10:        0x101d3c2b6 - std::rt::lang_start::ha9be7b379cf1665e
alacritty/target/release ಠ_ಠ (master) #
```

Also, If I do `<Alt-N>` and switching window focus back and forth- the output message a lil bit differs:
```bash
alacritty/target/release ಠ_ಠ (master) # ./alacritty
Config file not found; using defaults
device_pixel_ratio: 1
device_pixel_ratio: 1
width: 1024, height: 768
Initializing glyph cache
Finished initializing glyph cache in 0.048570795
set_inner_size: 484px × 316px
width: 484, height: 316
Cell Size: (6 x 13)
PTY Dimensions: Line(24) x Column(80)
2017-01-06 22:21:39.000 alacritty[87263:31585840] IMKInputSession presentFunctionRowItemTextInputViewWithEndpoint:completionHandler: : *NO* NSRemoteViewController to client, NSError=Error Domain=NSCocoaErrorDomain Code=4097 "connection from pid 0" UserInfo={NSDebugDescription=connection from pid 0}, com.apple.inputmethod.EmojiFunctionRowItem
thread 'main' panicked at 'window closed', src/event.rs:133
stack backtrace:
   1:        0x1085e893a - std::sys::imp::backtrace::tracing::imp::write::h1461f67be4bf68a9
   2:        0x1085eaa4f - std::panicking::default_hook::{{closure}}::h6dba65b2b498d274
   3:        0x1085ea6f7 - std::panicking::default_hook::ha8ecbcff1f59e805
   4:        0x1085eaf16 - std::panicking::rust_panic_with_hook::h5ceed7bd7aef311a
   5:        0x10852db24 - std::panicking::begin_panic::hac4cfc1999155f3b
   6:        0x108534ef8 - <alacritty::event::Processor<N>>::handle_event::ha2aefe0613e20e4e
   7:        0x10854e2e3 - alacritty::run::hb24e186a0c9a26a5
   8:        0x10854c375 - alacritty::main::h6cfa89d1e4d178de
   9:        0x1085ebd6a - __rust_maybe_catch_panic
  10:        0x1085eb2b6 - std::rt::lang_start::ha9be7b379cf1665e
alacritty/target/release ಠ_ಠ (master) #
``` 

*PS*: Great job, looks like Alacritty indeed smoother than iTerm!

With best regards,
Yan

**Comment by davesque** [comment]
I am having the same issue with <Ctrl-Space>.

**Comment by yanlobkarev** [comment]
Thanks for linking @davesque )

**Comment by jwilm** [comment]
Closing in favor of #93.
