### ISSUE TITLE
"out of bounds" crash - access beyond last row?

### ISSUE THREAD

**Issue by metayan** [jwilm/alacritty#855]
Running the irssi irc client continuously in tmux on a remote machine causes alacritty to always crash after irregular amounts of time.

The window has 81 rows, so it seems something is trying to access rows that don't exist.

Alacritty version is 9f79d72109b5745c32a8c0bdd4d17799f827fbba from github.

Run as:
```RUST_LOG=full RUST_BACKTRACE=full ./target/debug/deps/alacritty-b2da0394a0ca1112```

Full backtrace:
```
thread 'main' panicked at 'index out of bounds: the len is 82 but the index is 82', /Users/travis/build/rust-lang/rust/src/libcollections/vec.rs:1552
stack backtrace:
  0:        0x10d970043 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h884a721e113c3303
  1:        0x10d975113 - std::panicking::default_hook::{{closure}}::h7a7d734b2824d103
  2:        0x10d974d5c - std::panicking::default_hook::h3eb11bd6cbfdc331
  3:        0x10d977287 - std::panicking::rust_panic_with_hook::h8b9b25777425677b
  4:        0x10d977124 - std::panicking::begin_panic::h69fe06a9d67b6165
  5:        0x10d977092 - std::panicking::begin_panic_fmt::haf8695bfb6c52436
  6:        0x10d976ff7 - rust_begin_unwind
  7:        0x10d99d820 - core::panicking::panic_fmt::hfedd6515bcee8bb1
  8:        0x10d99d798 - core::panicking::panic_bounds_check::h7e54553d1bd69142
  9:        0x10d3e9d28 - <collections::vec::Vec<T> as core::ops::Index<usize>>::index::h385d942757023add
 10:        0x10d408b1f - <alacritty::grid::Grid<T> as core::ops::Index<&'point alacritty::index::Point>>::index::h2a7413910317e701
 11:        0x10d4183e8 - alacritty::term::RenderableCellsIter::populate_no_cursor::h895cc7459e0f8b7a
 12:        0x10d418552 - alacritty::term::RenderableCellsIter::initialize::h9f6592acd443ac18
 13:        0x10d417953 - alacritty::term::RenderableCellsIter::new::hb73e002fe676d3c4
 14:        0x10d41bf82 - alacritty::term::Term::renderable_cells::hecd7505a9250eecd
 15:        0x10d406ebe - alacritty::display::Display::draw::{{closure}}::hebea04e907d57673
 16:        0x10d40e1aa - alacritty::renderer::QuadRenderer::with_api::h3450a8f2b1aaef03
 17:        0x10d406a1b - alacritty::display::Display::draw::hf41d6aeb6b513ec8
 18:        0x10d28538d - alacritty::run::he26f75e5563d5b1e
 19:        0x10d283a3f - alacritty::main::h015c9c3f7e93b13b
 20:        0x10d97831a - __rust_maybe_catch_panic
 21:        0x10d977704 - std::rt::lang_start::h6e7c6ad302fab11a
 22:        0x10d285bf9 - main
thread 'pty reader' panicked at 'index out of bounds: the len is 82 but the index is 82', /Users/travis/build/rust-lang/rust/src/libcollections/vec.rs:1561
stack backtrace:
  0:        0x10d970043 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h884a721e113c3303
  1:        0x10d975113 - std::panicking::default_hook::{{closure}}::h7a7d734b2824d103
  2:        0x10d974d5c - std::panicking::default_hook::h3eb11bd6cbfdc331
  3:        0x10d977287 - std::panicking::rust_panic_with_hook::h8b9b25777425677b
  4:        0x10d977124 - std::panicking::begin_panic::h69fe06a9d67b6165
  5:        0x10d977092 - std::panicking::begin_panic_fmt::haf8695bfb6c52436
  6:        0x10d976ff7 - rust_begin_unwind
  7:        0x10d99d820 - core::panicking::panic_fmt::hfedd6515bcee8bb1
  8:        0x10d99d798 - core::panicking::panic_bounds_check::h7e54553d1bd69142
  9:        0x10d2620b8 - <collections::vec::Vec<T> as core::ops::IndexMut<usize>>::index_mut::h80b2a1fd0adbdbad
 10:        0x10d0e9c3f - <alacritty::grid::Grid<T> as core::ops::IndexMut<&'point alacritty::index::Point>>::index_mut::he2f2b33300115f7b
 11:        0x10d238238 - <alacritty::term::Term as alacritty::ansi::Handler>::input::h38b25ef3b43b5502
 12:        0x10d26f1cc - <alacritty::ansi::Performer<'a, H, W> as vte::Perform>::print::h1bbcd6503e2a2250
 13:        0x10d17d9a0 - vte::Parser::perform_action::ha5470c3c1c3e22e2
 14:        0x10d17e66a - vte::Parser::perform_state_change::ha59191296917e01e
 15:        0x10d17e9db - vte::Parser::advance::h060f2b296d3adeef
 16:        0x10d27a336 - alacritty::ansi::Processor::advance::hadba47c2171baa34
 17:        0x10d20717c - <alacritty::event_loop::EventLoop<Io>>::pty_read::h8c0c86f61ccffee4
 18:        0x10d206226 - <alacritty::event_loop::EventLoop<Io>>::spawn::{{closure}}::h0db2a67f949da023
 19:        0x10d173c75 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9e5f8791a6b57a35
 20:        0x10d17c69e - std::thread::Builder::spawn::{{closure}}::{{closure}}::hf8f80e7bd991c509
 21:        0x10d270e65 - <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once::h434813d67c2348e4
 22:        0x10d17d59e - std::panicking::try::do_call::h61a1b9db16b3a2d9
 23:        0x10d97831a - __rust_maybe_catch_panic
 24:        0x10d17d04c - std::panicking::try::h44a3b0daba729aec
 25:        0x10d17acc5 - std::panic::catch_unwind::h15134a4717a565c6
 26:        0x10d17c0bb - std::thread::Builder::spawn::{{closure}}::h55b2c6785ba8d20e
 27:        0x10d1fefa3 - <F as alloc::boxed::FnBox<A>>::call_box::hc2de7fc48eb0897a
 28:        0x10d974745 - std::sys::imp::thread::Thread::new::thread_start::h993b7e5cb7871f66
 29:     0x7fff8323e99c - _pthread_body
 30:     0x7fff8323e919 - _pthread_start
```

The durations after which crashes have occurred:
```
14936.222349
72115.422882
43475.226691
25231.261642
31821.904172
18509.776205
29194.054814
15107.070347
32855.495703
99737.405839
15130.510268
30697.664912
91362.931336
29762.215947
76674.832828
15152.655278
16026.488250
14962.226446
3933.400551
21053.432503
15114.813950
29907.619427
15108.094483
```

Running on OSX 10.11.6.

**Comment by metayan** [comment]
Added
```
diff --git a/src/term/mod.rs b/src/term/mod.rs
index 59cf6ba..7e6ef7c 100644
--- a/src/term/mod.rs
+++ b/src/term/mod.rs
@@ -235,11 +235,20 @@ impl<'a> RenderableCellsIter<'a> {
 
     /// Populates list of cursor cells with the original cell
     fn populate_no_cursor(&mut self) {
-        self.cursor_cells.push_back(Indexed {
-            line: self.cursor.line,
-            column: self.cursor.col,
-            inner: self.grid[self.cursor],
-        });
+        eprintln!("in populate_no_cursor: line: {}/{} col: {}/{}",
+                  self.cursor.line, self.grid.num_lines(),
+                  self.cursor.col, self.grid.num_cols());
+        if self.cursor.line < self.grid.num_lines() {
+            self.cursor_cells.push_back(Indexed {
+                line: self.cursor.line,
+                column: self.cursor.col,
+                inner: self.grid[self.cursor],
+            });
+        } else {
+            eprintln!("ERROR: in populate_no_cursor: out of bounds! line: {}/{} col: {}/{}",
+                      self.cursor.line, self.grid.num_lines(),
+                      self.cursor.col, self.grid.num_cols());
+        }
     }
 
     fn initialize(mut self, cursor_style: CursorStyle) -> Self {
```
to see what's going on, and this is the result:
```
27.766116      Running `target/debug/alacritty -v -v -v -d 222 82`
40.905544 in populate_no_cursor: line: 62/82 col: 66/222
44.834063 in populate_no_cursor: line: 63/82 col: 94/222
348.115005 in populate_no_cursor: line: 5/82 col: 8/222
355.532341 in populate_no_cursor: line: 63/82 col: 23/222
507.849088 in populate_no_cursor: line: 59/82 col: 68/222
2905.149526 in populate_no_cursor: line: 82/82 col: 0/222
2905.149603 ERROR: in populate_no_cursor: out of bounds! line: 82/82 col: 0/222
2905.162146 thread 'pty reader' panicked at 'index out of bounds: the len is 82 but the index is 82', /Users/travis/build/rust-lang/rust/src/libcollections/vec.rs:1561
2905.162206 stack backtrace:
2905.162611    0:        0x10d8e2863 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h884a721e113c3303
2905.162981    1:        0x10d8e7933 - std::panicking::default_hook::{{closure}}::h7a7d734b2824d103
2905.163259    2:        0x10d8e757c - std::panicking::default_hook::h3eb11bd6cbfdc331
2905.163509    3:        0x10d8e9aa7 - std::panicking::rust_panic_with_hook::h8b9b25777425677b
2905.163765    4:        0x10d8e9944 - std::panicking::begin_panic::h69fe06a9d67b6165
2905.164010    5:        0x10d8e98b2 - std::panicking::begin_panic_fmt::haf8695bfb6c52436
2905.164247    6:        0x10d8e9817 - rust_begin_unwind
2905.164463    7:        0x10d910040 - core::panicking::panic_fmt::hfedd6515bcee8bb1
2905.164677    8:        0x10d90ffb8 - core::panicking::panic_bounds_check::h7e54553d1bd69142
2905.164889    9:        0x10d1d4108 - <collections::vec::Vec<T> as core::ops::IndexMut<usize>>::index_mut::h797cf362b5cfe4fc
2905.165108   10:        0x10d05c01f - <alacritty::grid::Grid<T> as core::ops::IndexMut<&'point alacritty::index::Point>>::index_mut::he0b15a4cb24c6f63
2905.165319   11:        0x10d1aa208 - <alacritty::term::Term as alacritty::ansi::Handler>::input::h5a5f51e443951d05
2905.165535   12:        0x10d1e116c - <alacritty::ansi::Performer<'a, H, W> as vte::Perform>::print::h9d3477262f82ac84
2905.165825   13:        0x10d0efaa0 - vte::Parser::perform_action::h42fc1fbe7d3bc36e
2905.166047   14:        0x10d0f076a - vte::Parser::perform_state_change::hb003be778f41e214
2905.166259   15:        0x10d0f0adb - vte::Parser::advance::h7f9321ff7b97666d
2905.166475   16:        0x10d1ec146 - alacritty::ansi::Processor::advance::h9c7012e0a57ce16f
2905.166690   17:        0x10d1791dc - <alacritty::event_loop::EventLoop<Io>>::pty_read::h21f6a6ef5d00b14e
2905.166905   18:        0x10d178286 - <alacritty::event_loop::EventLoop<Io>>::spawn::{{closure}}::h2bd6f3262c59ae6c
2905.167124   19:        0x10d0e5d75 - std::sys_common::backtrace::__rust_begin_short_backtrace::heb86b776b608e763
2905.167341   20:        0x10d0ee79e - std::thread::Builder::spawn::{{closure}}::{{closure}}::hfb1dcd9d9e0d2bc3
2905.167567   21:        0x10d1e2eb5 - <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once::ha9c52a35ae2a72c0
2905.167784   22:        0x10d0ef69e - std::panicking::try::do_call::ha01e93e26d732b9e
2905.168010   23:        0x10d8eab3a - __rust_maybe_catch_panic
2905.168215   24:        0x10d0ef32c - std::panicking::try::he6b1d5950e3e08e9
2905.168424   25:        0x10d0ecdc5 - std::panic::catch_unwind::h77d46f851bc5399f
2905.168633   26:        0x10d0ee4eb - std::thread::Builder::spawn::{{closure}}::hed2976a4aa2d96d1
2905.168849   27:        0x10d171093 - <F as alloc::boxed::FnBox<A>>::call_box::hb1df48d579df47f9
2905.169078   28:        0x10d8e6f65 - std::sys::imp::thread::Thread::new::thread_start::h993b7e5cb7871f66
2905.169103   29:     0x7fff8323e99c - _pthread_body
2905.169113   30:     0x7fff8323e919 - _pthread_start
```
so the cursor appears at column 0 one line beyond the screen.
Hope it helps in tracking the error down.

The error is triggered when my network connection has issues and my ssh session - running irssi in tmux - goes down.

I'll add
```
            self.cursor.line = self.grid.num_lines();
```
to the `else` for now to see what happens...

**Comment by metayan** [comment]
An instance with the solution in 559cfabbe198dbbf21804c201dca46d070eb6cf6 has been running for over a week now without any crashes. Before applying the fix, alacritty would crash several times per day.

It can be tested with:
```sh
tput csr 10 20; tput cup 25; for ((i=0; i<200; i++)); do echo; done;
```
which sets the scroll region to 10 - 20, positions the cursor on line 25, and emits linefeeds, or - simpler -
```sh
tput csr 10 20; tput cup 300;
```

I also noticed that a test for newline_with_cursor_beyond_scroll_region was added in 87468b5c00858684ab0a17f9e1821aa374f74924 but not activated. Maybe it can be done with:
```diff
diff --git a/tests/ref.rs b/tests/ref.rs
index cea814e..7b820d3 100644
--- a/tests/ref.rs
+++ b/tests/ref.rs
@@ -31,6 +31,7 @@ ref_tests! {
     fish_cc
     indexed_256_colors
     ll
+    newline_with_cursor_beyond_scroll_region
     tab_rendering
     tmux_git_log
     tmux_htop
```

**Comment by jwilm** [comment]
This was resolved.
