### ISSUE TITLE
fontconfig: vertical subpixel geometry no longer works

### ISSUE THREAD

**Issue by jbeich** [jwilm/alacritty#962]
After 31d1087b8614ddd423a6c522d91a1d93a37cd92e `rgba` set to either `vrgb` and `vbgr` aborts startup. Tested in a X11 jail on FreeBSD with alacritty package update to 3472921c7d0b20e57f3aa953f92b525ef2729287 snapshot.

```
$ pkg install alacritty mesa-dri libXi libXcursor dejavu
$ fgrep edit /usr/local/etc/fonts/conf.avail/10-sub-pixel-vrgb.conf
    <edit name="rgba" mode="append"><const>vrgb</const></edit>
$ ln -s ../conf.avail/10-sub-pixel-vrgb.conf /usr/local/etc/fonts/conf.d/
$ rm -rf ~/.config/alacritty
$ RUST_BACKTRACE=1 alacritty
thread 'main' panicked at 'unhandled pixel mode: LcdV', font/src/ft/mod.rs:433:24
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:69
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:381
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:397
             at src/libstd/panicking.rs:577
   3: std::panicking::begin_panic
             at src/libstd/panicking.rs:538
   4: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:522
   5: <font::ft::FreeTypeRasterizer as font::Rasterize>::get_glyph
             at font/src/ft/mod.rs:433
             at font/src/ft/mod.rs:295
             at font/src/ft/mod.rs:112
   6: alacritty::display::Display::new
             at src/renderer/mod.rs:186
             at src/display.rs:228
             at src/renderer/mod.rs:686
             at src/display.rs:227
             at src/display.rs:153
   7: alacritty::run
             at src/main.rs:103
   8: alacritty::main
             at src/main.rs:53
   9: main
  10: _start
             at /usr/src/lib/csu/amd64/crt1.c:74
```

**Comment by ldmldmldm** [comment]
The same issue occurs for me. This is frustrating as I find vertical monitors fantastic to program on. Is there any logging output that I could provide to help the progression of this issue? Thanks!

**Comment by chrisduerr** [comment]
No, the issue is simply that it's not implemented yet. It's a LcdV support is simply a missing feature.

**Comment by ldmldmldm** [comment]
Ah OK, the OP's post title is misleading then. Thanks for the information. Might want to update the title or add the label enhancement or something.

**Comment by chrisduerr** [comment]
Yeah I just looked it up to make sure, the title is misleading unless someone has removed this feature in the past. Currently there's an explicit panic in the code at that point.

**Comment by chasevasic** [comment]
It would be good if it at least gave an informative error message. I didn't understand the error until I came here. I can't use this application without this being fixed, but unfortunately, I can't contribute to fixing this.
