### ISSUE TITLE
Segfault on X11 Linux

### ISSUE THREAD

**Issue by osa1** [jwilm/alacritty#980]
Which operating system does the issue occur on?

Linux x86_64 (Xubuntu 16.04)

If on linux, are you using X11 or Wayland?

X11 (i3 window manager)

Version

8ce553f

---

When I run alacritty in release mode (debug mode works fine) it segfaults directly without printing anything.

I tried removing my config files but got the same output.

Stack trace:

```
#0  0x0000000000000000 in ?? ()
#1  0x000055555580f504 in glutin::api::glx::ffi::glx_extra::Glx::SwapIntervalEXT::ha832efad79070a2a (interval=1, self=<optimized out>, dpy=<optimized out>, drawable=<optimized out>)
    at /home/omer/rust/alacritty/target/release/build/glutin-fc5681b4476584a0/out/glx_extra_bindings.rs:593
#2  glutin::api::glx::ContextPrototype::finish::hea806e244e24ee17 (self=..., window=<optimized out>) at /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.11.0/src/api/glx/mod.rs:252
#3  0x0000555555804e48 in glutin::platform::platform::x11::Context::new::h209159face65e7a9 (window_builder=..., events_loop=<optimized out>, pf_reqs=<optimized out>, gl_attr=<optimized out>)
    at /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.11.0/src/platform/linux/x11.rs:217
#4  0x000055555580077a in glutin::platform::platform::Context::new::hde3556c342568aa2 (window_builder=..., events_loop=0x7fffffffa340, pf_reqs=<optimized out>, gl_attr=<optimized out>)
    at /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.11.0/src/platform/linux/mod.rs:58
#5  glutin::GlWindow::new::h2293a9bd6e9bdebb (window_builder=..., context_builder=..., events_loop=0x7fffffffa340) at /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.11.0/src/lib.rs:322
#6  0x000055555565a62b in alacritty::window::Window::new::hd57571420e67a9e7 (title=..., window_config=0x7fffffffc4b8) at src/window.rs:203
#7  0x0000555555628c69 in alacritty::display::Display::new::hb2503e60a7097e41 (config=0x7fffffffc3d0, options=0x7fffffffd528) at src/display.rs:140
#8  0x0000555555683868 in alacritty::run::hc2eda810edf4ce0a (options=<optimized out>, config=...) at src/main.rs:103
#9  alacritty::main::hddd2bd38ccac6e4b () at src/main.rs:53
#10 0x0000555555660256 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h8f369ceb4f6e618f () at /checkout/src/libstd/rt.rs:74
#11 0x0000555555895568 in std::rt::lang_start_internal::_$u7b$$u7b$closure$u7d$$u7d$::haefc7fa79ac54b63 () at /checkout/src/libstd/rt.rs:59
#12 std::panicking::try::do_call::h8154dbcab3f4d602 () at /checkout/src/libstd/panicking.rs:480
#13 0x000055555589e8ae in __rust_maybe_catch_panic () at /checkout/src/libpanic_unwind/lib.rs:101
#14 std::panicking::try::h3315662ae9ec5656 () at /checkout/src/libstd/panicking.rs:459
#15 std::panic::catch_unwind::h9138e7d39c984961 () at /checkout/src/libstd/panic.rs:365
#16 std::rt::lang_start_internal::h6e5de529be6cef59 () at /checkout/src/libstd/rt.rs:58
#17 0x00005555556849e2 in main ()
```

**Comment by chrisduerr** [comment]
Are you using the stable or nightly compiler?

**Comment by osa1** [comment]
Nightly.

**Comment by chrisduerr** [comment]
Try using stable. Nightly has had some issues for a while. If you really want to use nightly make sure it's on the latest nightly, that seems to work for me again.

But generally going with stable is the safer bet.
